### ISSUE TITLE
Selected language resets back to default on finishing test

### ISSUE THREAD

**Issue by barthakstege** [Miodec/monkeytype#1002]
**Describe the bug**
A custom selected language resets after finishing a test. 

**To Reproduce**
1. Select Dutch 1k as the language
2. Finish a typing test
3. On the results page it shows English as language instead of Dutch 1k
4. On pressing tab (to start a new test) the language is defaulted back to English

**Expected behavior**
When selecting a custom language the choice should not reset after a test and the results screen should show the correct language.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version: 85.02

**Comment by Miodec** [comment]
Fixed
