### ISSUE TITLE
Ctrl+Backspace deletes multiple words if they are connected with dashes

### ISSUE THREAD

**Issue by bilfri** [Miodec/monkeytype#1012]
**Describe the bug**
When I write multiple words connected with dashes (eg. foo-bar) and press ctrl+backspace, all words get deleted. Only the word closest to the cursor should be deleted. That's how it is implemented in my OS anyway.

**To Reproduce**
1. Go to zen mode
2. Type "foo-bar"
3. Press Ctrl+Backspace

**Expected behavior**
Only "bar" should be deleted

**Desktop (please complete the following information):**
 - Linux Mint 20
 - Chromium 88.0.4324.150 and Firefox 85.0.1
 - monkeytype 1.7.5

**Comment by Miodec** [comment]
Fixed, will be live soon
