### ISSUE TITLE
safari and firefox sound on click is laggy

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1014]

**Comment by MysteriousLog6** [comment]
I haven't detected lag on Mac os Safari (It was a few months ago but I don't remember it being laggy but it is a bit quicker on windows I do agree on that)

**Comment by dst27** [comment]
I can reproduce this issue on Firefox 88.0 on Windows. The lag is noticeably reduced on Chromium browsers.
