### ISSUE TITLE
Site breaks on languages without quotes

### ISSUE THREAD

**Issue by Esemesek** [Miodec/monkeytype#1030]
**Describe the bug**
Whenever I change the language to Polish and go into `quote` mode, the site breaks. Cannot change the mode back or go into settings to revert it. The only way to fix the issue is to go into DevTools and clear site data.

Initially, I discovered the issue because I was in the quote mode in English and I switched to Polish.

**To Reproduce**
1. Go to settings and change the language to Polish
2. Go to typing test and change the mode to `quote`

or

1. Select quote mode
2. Go to settings and change the language to Polish
3. go to the typing test

**Expected behavior**
I get the error, that there are no `quotes` in my language, but I am able to switch the mode back.
or
There is not `quote` mode available.

**Screenshots**
![image](https://user-images.githubusercontent.com/9092510/109220110-d10e5f80-77b8-11eb-9d07-a5040c7ea7ba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 88.0.4324.182

**Comment by Miodec** [comment]
Fix is live now
