### ISSUE TITLE
Alt Gr key not supported on QWERTZ E2 keyboards

### ISSUE THREAD

**Issue by ItWorkedInCAD** [Miodec/monkeytype#1037]
**Describe the bug**
Similar to issue #970 from about two weeks ago. I'm using a german QWERTZ E2 keyboard (standard DIN 2137:2018-12), and 
when trying to type special characters that require the Alt Gr key, such as "[" and "}", the Alt Gr key doesn't get recognized and "8" and "0" are typed instead. This issue doesn't seem to appear on the more common german T2 layout.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.150

**Comment by Miodec** [comment]
The Alt layer will not work if you have layout override set to anything other than `default`.
