### ISSUE TITLE
Compose key does not work

### ISSUE THREAD

**Issue by barthakstege** [Miodec/monkeytype#1040]
**Describe the bug**
The compose key is used in Linux for typing special characters such as 'é'. This however does not work when typing in Monkeytype. After pressing the desired key combination (for example compose key + ' + e) no characters are inputted.

**To Reproduce**
1. Start a new test
2. Try to compose a special character using the compose key
3. Notice that after inputting the key combination the desired character does not show up

**Expected behavior**
The expected behavior would be for Monkeytype to recognize the special character constructed using the compose key

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 86

**Additional context**
Tested on GNOME Xorg and Wayland in Firefox and Chrome.

**Comment by Miodec** [comment]
(make sure layout override is set to default, but that probably wont fix it)

This is related to other issues that are open about Linux and dead keys / compose keys. They all involve rewriting the input system. I will close this because its well known.

**Comment by Lilalas** [comment]
This issue has been duplicated by #1403 and that issue fortunately includes a fix that works for me.

I think it is important to reference this here because searching for “compose key” on the issue tracker only brings up this issue.
