### ISSUE TITLE
Move Terminal Button during Screenshot

### ISSUE THREAD

**Issue by uShldGetCeleste** [Miodec/monkeytype#1043]
**Describe the bug**
Terminal button gets in the way when taking a screenshot so it would would be nice if it got hidden during the screenshot so it's not covering anything

**To Reproduce**
1. Finish a typing test
2. Take a screenshot

**Expected behavior**
Terminal button should not be in the way of information

**Screenshots**
![image](https://user-images.githubusercontent.com/68669265/109916276-8b4a0f00-7c70-11eb-9e58-f59967d09fa5.png)

**Additional context**
First 100 wpm even though it was on the 10 word test :o

**Comment by Miodec** [comment]
Fixed in the next update
