### ISSUE TITLE
[Improvement] Disable Funbox on Settings Page

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1047]
When you enable some funbox modes like nausea or spaceballs, it makes it almost possible to change any other setting until you go to the command line and turn funbox off, disabling funbox on the settings page would make it easier to change settings with funbox modes like nausea and spaceballs on.

**Comment by TheeKevin** [comment]
I don't know about you but disabling funbox's would kind of waste some of the "fun" potential they have. Besides, if you know the command line exists why not just use that to disable it? You can also simply reload the page to reset Monkeytype.

**Comment by UnrealApex** [comment]
I agree, but its something thats always a little bit annoying to deal with
