### ISSUE TITLE
Could not implement locally - firebase free App

### ISSUE THREAD

**Issue by stargazer36** [Miodec/monkeytype#1053]
Could there be firebase free Version, can not implement. 

Firebase is overkill for small orject. 

Another typing test App works just with 4kb html and 9kb (vanilla javascript)
 - - These projects are kind of making ornaments out of stones. 

There is no reason to use firebase, at least not for me.

**Comment by Miodec** [comment]
Currently, there is no plan to create a light version - maybe in the future.
