### ISSUE TITLE
Typo in the description of version 1.7.6

### ISSUE THREAD

**Issue by Cosme1** [Miodec/monkeytype#1054]
In the description of version 1.7.6 where new features, quotes, bug fixes, and other changes/improvements are presented. See screenshot for exact location. Typo is circled in red.
![Screenshot 2021-03-06 163638](https://user-images.githubusercontent.com/29796915/110212182-6afd9880-7e9a-11eb-8025-18222eb55278.png)

**Comment by Miodec** [comment]
Fixed
