### ISSUE TITLE
Add an option to force opposite shifts.

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#1059]
- Use `event.code` to determine which side of the keyboard the key was pressed.
- Use `event.location` to determine which shift key was pressed 
- Either ignore or allow that keypress if correct shift was pressed.
- Show a notice to the user that this will only work with layouts changed on the system level. Using programmable keyboards and changing the layout on the keyboard level (for example with QMK) will not work.

**Comment by angularorbit** [comment]
I just want to note that `event.code` is enough to determine which shift key has been pressed. It has `ShiftRight` and 'ShiftLeft` options.

**Comment by angularorbit** [comment]
I also want to say that, neither `event.code` or `event.location` can work out which shift was pressed if the event is not a shift, it would only tell you the `code` or `location` of the particular key that caused the event, not the shift, and `event.shiftKey`  wouldn't be the more informative. So I think you have to track `RightShift` and `LeftShift` key down and up events.

**Comment by Miodec** [comment]
Added

**Comment by angularorbit** [comment]
Thanks a ton! Can you also make this work as well for the symbols at the top and the right of the keyboard like `!@#$%` ,` &*(-= `and `{}:">?`? If so, you might want to keep `^` neutral as well.
