### ISSUE TITLE
How exactly does global leaderboard work?

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#1063]
I'm not sure if it's a bug so I won't be filling out the guidelines. Also, I don't think it's my device and I can't really do anything specific to make it happen so perhaps it's how the code was designed.

![image](https://user-images.githubusercontent.com/58377021/110371081-b97d7500-8009-11eb-865d-ecc21b7cb48f.png)

So Litevx (random person) got a 191.97 on the daily leaderboard. So therefore he should be on the global leaderboard too right? He should be at 260/261 but he's not. This is the same with other typists. So how exactly does this work?

**Comment by angularorbit** [comment]
I think it is because `litvex` already has one higher up so it doesn't make sense to have it twice.
![Screenshot_2021-03-09 Monkeytype(1)](https://user-images.githubusercontent.com/55037535/110374616-fba7c480-80a4-11eb-8870-d18d3907ff99.png)

**Comment by Miodec** [comment]
Answered by @angularorbit

**Comment by TheeKevin** [comment]
Ah... Okay I already knew that it shouldn't count twice. I just didn't check if they had a higher score or not. Well thanks for telling me @angularorbit
