### ISSUE TITLE
How do i make it run on my local machine 

### ISSUE THREAD

**Issue by pratik6158** [Miodec/monkeytype#1069]
I am just starting with opensource and would really love if some one could make a tutorial about how to setup this monkeyType on my local machine 

Thanks.

i tried opening index.html in static directory but it is showing me everything with css so i think thats not how you are supposed to open this?

Please use GitHub Discussions:
https://github.com/Miodec/monkeytype/discussions

**Comment by joaodanilo123** [comment]
Well, I'm in the same situation, but I succesfully set up the project following the steps in  [CONTRIBUTING.md](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)

**Comment by Miodec** [comment]
As @joaodanilo123 - follow the steps in `contributing.md`
