### ISSUE TITLE
[can't reproduce] [bug]  Monkeytype Shows Wrong Accuracy For Tests With No Mistakes

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1072]
**Describe the bug**
Monkeytype shows accuracy as `99.59%` even though no mistakes were made during the test. 
**To Reproduce**

1. Set your test type to  `time 30 english` 
2. Start the test
3. Finish the test with no mistakes
4. See what the accuracy is 

**Expected behavior**
The accuracy would be 100% if there were no mistakes

**Screenshots**
![bug](https://user-images.githubusercontent.com/79121360/110700765-2ed17d00-81a5-11eb-8b6c-2e81b4187c3b.png)

**Desktop**
 - OS: [ChromeOS]
 - Browser [Google Chrome]
 - Version [89.0.4389.82 (Official Build) (64-bit)]
 - Javascript Version [ V8 8.9.255.20]
- I also will see if this bug happens on my Windows machine and using a different browser

**Additional context**
note: I have noticed that this bug is not consistent and appears at random

**Comment by Miodec** [comment]
Im pretty sure this could be because you pressed space too early?

**Comment by UnrealApex** [comment]
I tested that, but pressing space early did not affect it.

**Comment by Miodec** [comment]
What about one key, then space, then back again.

**Comment by UnrealApex** [comment]
I think that might be it, I typed the first letter of the test, pressed space, then went back to correct the mistake. The accuracy is shown as 99.5% but the graph doesn't display the error. 
### **Screenshot**
---
![bug](https://user-images.githubusercontent.com/79121360/110874452-9c0a0e80-8288-11eb-9a62-425d9c613197.png)

**Comment by Miodec** [comment]
Fixed, will be live soon.

**Comment by UnrealApex** [comment]
pog
