### ISSUE TITLE
Buttons below results dissapear after screenshot is taken

### ISSUE THREAD

**Issue by lukew3** [Miodec/monkeytype#1083]
**Describe the bug**
After taking a screenshot, the buttons below the results are gone.

**To Reproduce**
1. Take a test and click on the "Save Screenshot" button
2. After seeing screenshot popup tab, go back to the browser tab with the test results page
3. Notice that buttons are gone

**Expected behavior**
After a screenshot is taken, the buttons below the results should reappear

**Screenshots**
![Screenshot from 2021-03-11 13-41-42](https://user-images.githubusercontent.com/47042841/110837705-948a3b80-826f-11eb-97c0-77bc6182608b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Firefox
 - Version: 86.0

**Comment by Miodec** [comment]
Fixed, should be live soon.
