### ISSUE TITLE
remember pre-funbox settings and revert to them when going back to funbox: none

### ISSUE THREAD

**Issue by lukew3** [Miodec/monkeytype#1085]
**Describe the bug**
I didn't have the on-screen keyboard on before I tried simon-says funbox. Then, after using the Simon-says funbox and switching out, the on-screen keyboard didn't disappear.

**To Reproduce**
1. Activate simon says mode
2. Switch out of funbox mode
3. See keyboard hangs

**Expected behavior**
After simon-says mode is exited, keyboard should dissapear

**Screenshots**
Before:
![Screenshot from 2021-03-12 00-30-56](https://user-images.githubusercontent.com/47042841/110896806-52421800-82ca-11eb-88cd-db9734dccc07.png)
After:
![Screenshot from 2021-03-12 00-31-20](https://user-images.githubusercontent.com/47042841/110896811-55d59f00-82ca-11eb-9731-c1c72a9f6c5f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Firefox
 - Version: 86.0

**Comment by lukew3** [comment]
Also, it's hard to find the keymap setting if you don't know what you're doing. I was looking for a setting named `keyboard` or `visual keyboard` for a while until I found the right setting.

**Comment by Miodec** [comment]
Not necessarily a bug. Since some people the keymap in normal tests, its not simply tied to the funbox. Its just enabled when enabling the funbox, but its state is not remembered from before using the funbox.
