### ISSUE TITLE
My Login is no longer Remembered

### ISSUE THREAD

**Issue by Chuck-7** [Miodec/monkeytype#1086]
For the Past Five Weeks, I have used MonkeyType on the Brave Browser:: And My Login Data was Remembered Just Fine!!

Then, just 2 Days Ago, I CHANGED Browsers From: Brave .. TO:: Firefox.
It Appears that Now on Firefox ... While Cookies ARE Being Saved–Since my Settings (Preferred Themes, The Test Font, Etc.) are being Remembered, __**BUT**___ NOW (in Firefox) my LOGIN Data (Email & Password) is **ALWAYS** Forgotten; {I have tested this a HUGE number of times}.

**EVERY** Time I Exit Firefox & Relaunch it, I **_ALWAYS_** HAVE to RE-Enter _**ALL**_ Login Data.
I would greatly prefer that it would Remember my Login Data Just Like EVERY Other Website Still Does!!

**Comment by lukew3** [comment]
Weird, Firefox works for me.

**Comment by Miodec** [comment]
It's also working for me so I don't even know where to look for the issue to be honst

**Comment by UnrealApex** [comment]
@Chuck-7   Did you try clearing cache and did you check the `[ ] remember me ` option before signing in ?

**Comment by Chuck-7** [comment]
Yes, UnrealApex, I did those things.  Thank You!

**Comment by UnrealApex** [comment]
Well,  @Miodec is on it

**Comment by Miodec** [comment]
> Yes, UnrealApex, I did those things. Thank You!

Wait, so its working now?

**Comment by MysteriousLog6** [comment]
I have had the same problem on Edge fixed it by clearing dnscache

**Comment by Miodec** [comment]
Wait, are you still experiencing this?

**Comment by Chuck-7** [comment]
Thank You Very Much for Asking!!

I Believe that I Have __Finally__ Solved the Mystery!! —>>

Just until a couple days ago, I was using an {Ashampoo} Cleaning Utility that was set to run every time I exited the internet.  The reason that I previously did Not suspect that Cleaning Utility was because it is set STRICTLY to Clear items like Cache—And **ZERO** Cookies.  But I tested it anyway & turns out that, Despite its setting, it _**WAS**_ removing Cookies from Firefox.  Furthermore, I have Also, After that incident, now made **_OPERA_** my Default Browser. {I Cannot use Chrome OR Edge as Default since they have declared themselves Antagonists of Certain types of Blocking.}

**Comment by Miodec** [comment]
Alright, glad you got it sorted out
