### ISSUE TITLE
[bug] Leaderboard Time Filter Not Responding On Click

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1090]
**Describe the bug**
When switching the leader board scores from the 15 second scores to the 60 seconds scores, the `time 60` button does not change the leaderboards to the 60 second scores.

**To Reproduce**
1. Click on the Leaderboards button (crown icon)
2. Click the `time 60` button
3. See if 60 second score are displayed

**Expected behavior**
If there was no error, the leaderboards would display the scores of users that did the 60 second test 

**Screenshots**

https://user-images.githubusercontent.com/79121360/111013405-19e71c00-8354-11eb-83c2-9e905fe5ed5a.mp4

**Desktop :**
 - OS: [Chrome OS]
 - Browser [Google Chrome]
 - Version [89.0.4389.82 (Official Build) (64-bit)]

**Additional context**
The bug also happens vice versa, sometimes the time 60 scores are shown and pressing the `time 15` button will not work

**Comment by Miodec** [comment]
Fixed it just now. It should be live.
