### ISSUE TITLE
Terminal button doesn't work before accessing the terminal using Esc

### ISSUE THREAD

**Issue by uShldGetCeleste** [Miodec/monkeytype#1092]
**Describe the bug**
If you click on the terminal button before pressing esc to access the terminal then it doesn't work

**To Reproduce**
1. Refresh
2. Click on the terminal button

**Expected behavior**
Should pull up a working terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/68669265/111020407-cdff9b80-8382-11eb-9e27-752dca443cdc.png)

**Desktop:**
 - OS: Windows 10 1909
 - Browser Chrome Beta 90.0.4430.19

**Comment by Miodec** [comment]
Fixed 2633167f1d1cbed95e6594f9572e1bb69a4c7699
