### ISSUE TITLE
issues with special characters

### ISSUE THREAD

**Issue by oriquami** [Miodec/monkeytype#1093]
special characters involving the alt key can't be typed at all
dead keys combining issues: when using dead keys combine the character that should be replaced gets inserted too

Chrome: Version 89.0.4389.82 (Official Build) (64-bit)
Microsoft Windows 10 Pro 10.0.19042 Build 19042
MSKLC Version 1.4

**Comment by Miodec** [comment]
Set the layout override to default and try again

**Comment by oriquami** [comment]
layout override was on default the entire time; issue not solved
