### ISSUE TITLE
How is "opposite" shift defined? 

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#1096]
I know I may be wrong here since I might have a different understanding of "opposite shift" but doesn't "opposite shift" means whenever your pressing a key you use your opposite hand to press the shift key?

Since the way the feature is designed it forces you to use the same hand to type the shift key which I think isn't correct.

**Comment by Miodec** [comment]
Yes, for right hand keys you should use left hand shift. Is it not working like that? Try clearing your cache and testing again?

**Comment by TheeKevin** [comment]
Welp it's a bug only for the layout that I use. Which is dvorak. When trying to use default or other keyboard layouts opposite shift works perfectly fine. However, when you change to dvorak opposite shift doesn't work properly.

**Comment by Miodec** [comment]
Right, i forgot to add a message that say it will not work if your default layout is not qwerty (since there is no way of detecting system layout)

**Comment by TheeKevin** [comment]
Ah that makes sense.
