### ISSUE TITLE
Error downloading user data

### ISSUE THREAD

**Issue by cx1201** [Miodec/monkeytype#1099]
After refreshing the web page, it only shows "Error downloading user data". I can only see the blank page with the warning now. It looks like the connect to the backend was blocked.

**Comment by Ahmad-A0** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/71089234/111082540-bea65c80-8500-11eb-951d-922ec35b98b0.png)

**Comment by Miodec** [comment]
Clear cache, its the latest update with a lot of code changes that caused that.

**Comment by cx1201** [comment]
Oh wow, it works!
