### ISSUE TITLE
[language] [future plans] [improvement] Some Filipino words are too informal! Please Help... It's boring

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1112]
Referring to discussion #1103

**Comment by Miodec** [comment]
Any language tweaks other than English I can't do myself and rely on other native speakers - if there are any mistakes or a better list available, make a pull request or provide the list.

**Comment by UnrealApex** [comment]
Will be closed by pr #1118

**Comment by UnrealApex** [comment]
> Any language tweaks other than English I can't do myself and rely on other native speakers
Same here
