### ISSUE TITLE
Cannot read property 'insertedAt' of undefined

### ISSUE THREAD

**Issue by Aidan-OS** [Miodec/monkeytype#1113]
**Did you make sure to clear cache before opening an issue?**
Sometimes your browser has old files cached and the bug you are experiencing might be already fixed, or a side effect of a new update. If you've already tried that, please delete this section. If you don't know how to do that, this website should help: https://clear-my-cache.com/

Yes, multiple times in fact.

**Describe the bug**

Whenever I finish a typing test, I get the following error:
![image](https://user-images.githubusercontent.com/1919827/111544753-57301d00-874b-11eb-8c9a-a5a2a84ea42c.png)

**To Reproduce**

Select any typing test.
Complete the typing test.
Error will appear in the top right.

I know this won't reproduce it for just anyone, but I couldn't figure out what caused it to happen. It doesn't even appear to do anything, as the results are recorded as normal. It's just annoying that it keeps popping up.

**Expected behavior**

Error should not appear

**Screenshots**

![image](https://user-images.githubusercontent.com/1919827/111545685-d114d600-874c-11eb-9721-21cc28621019.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.82

**Additional context**

**Comment by Iipal** [comment]
+1

**Comment by Miodec** [comment]
Its because of an update that was pushed just now, clearing cache should work eventually.
