### ISSUE TITLE
add some sort of lag check

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1131]

**Comment by TheeKevin** [comment]
Does Monkeytype even lag? Aside from using "toggle all lines" and inputting a custom test for 10,000 words Monkeytype shouldn't lag. Unless this means a different thing @Miodec

**Comment by Miodec** [comment]
Some people are experiencing lag spikes even on 60 second tests, and because they type while the lag spike is happening, they get like 500 raw.

**Comment by pingshunhuangalex** [comment]
If I use average PB and start the test before the average PB was calculated, it'll lag for a sec the moment when things are calculated. And somehow that PB does take quite a while to load which can be quite annoying.

**Comment by UnrealApex** [comment]
I would say the only time Monkeytype lags for me is when I have ads on.

**Comment by UnrealApex** [comment]
Possibly also add an internet connection check?

**Comment by redarguireda** [comment]
probably a good idea, checking the connection with a basic timeout? Just to know if the website is taking to much to load or even when typing if the user experience some sort of lag we check it with a timeout, if it requires too much time we block the typing test. Just an idea again, tell me what you guys think about it

**Comment by Miodec** [comment]
Added a check if the timer step execution didn't take too long. If it did, the test is stopped.
