### ISSUE TITLE
Remove Space Bars from adding the amount of words typed

### ISSUE THREAD

**Issue by MysteriousLog6** [Miodec/monkeytype#1132]
**Explanation**
If I were to spam the test by only clicking the space bar it will still count the clicks of the space bar in the raw speed (Not the total but the raw speed).

**Expected Behaviour**
The raw words per minute should be 0

**Comment by Miodec** [comment]
Im not sure what do you mean, pressing space is ignored at the beginning of a word is ignored.

**Comment by Miodec** [comment]
Maybe you are talking about strict space actually: increasing raw with spaces is fine since spaces are included in the wpm calculation - meaning also should be in raw.
