### ISSUE TITLE
PB caret not shown in quote mode

### ISSUE THREAD

**Issue by jvonk** [Miodec/monkeytype#1141]
**Describe the bug**
When logged in and using quote mode, with a PB caret selected, it does not appear.

**Did it happen in incognito mode?**
Issue persists in incognito mode when signed in.

**To Reproduce**
1. Go to quote mode
2. Change pace caret mode to PB
3. Navigate through, skipping quotes
4. See no PB pace or cursor

**Expected behavior**
Expect to see PB caret appear.

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version: 89

**Additional Information**
Caret works for average and custom pacing or for time, words, and custom modes.
Caret appears in PB if we switch to average or custom pacing and back on the same quote.

**Comment by Miodec** [comment]
PB's are not tracked for quote mode so pb caret will not work
