### ISSUE TITLE
can't press right-hand keys

### ISSUE THREAD

**Issue by Iipal** [Miodec/monkeytype#1144]
https://user-images.githubusercontent.com/31858171/112744212-d34c1100-8f52-11eb-81fb-428e36113622.mp4

using opposite shift if it's helps

Windows 10
Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Is this consistent, or did only happen once?

**Comment by Iipal** [comment]
> Is this consistent, or did only happen once?

only once

**Comment by Miodec** [comment]
Alright, i assume the shift detection code got stuck somehow. Without a way to reproduce this I don't think ill be able to fix it. If you find a way to get it consistently, let me know.
