### ISSUE TITLE
Exact result time for 30 second test incorrect [bug] [can't reproduce]

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1156]
**Describe the bug**
Time Tool Tip shown when hovering over time taken to take 30 second test shows time as 30.01 seconds.

**To Reproduce**
1. Change test type to `time 30`
2. Complete the test
3. View the time it took on the bottom right of the screen 
4. Hover over the time to get more a more exact time
5. A small onMouseOver Tool Tip will appear showing the time as `30.01s (0s afk 0%)`.

**Expected behavior**
The Tool Tip would display the exact time as `30s (0s afk 0%)`

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [Google Chrome]
 - Version [89.0.4389.95 (Official Build) (64-bit)]

**Additional context**
I have noticed that this bug is not consistent throughout multiple tests.

**Comment by Miodec** [comment]
I cant really do much about it. Small variations like pc speed, maybe a lag spike, will cause the timer to not be perfect all the time.
