### ISSUE TITLE
add report quote featrue

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1158]

**Comment by TheeKevin** [comment]
Are there any quotes that could be offensive? I thought you checked them before putting them into the site? Unless this person is talking about grammatical errors.

**Comment by Miodec** [comment]
Yeah, I'm more talking about grammatical errors.

**Comment by UnrealApex** [comment]
> Are there any quotes that could be offensive? I believe that you've checked them before implementing them into the site. Unless your talking about grammatical errors.

FAIK there are no offensive quotes, but there are some offensive words in the language files that some users have unearthed.

**Comment by PianoReflex** [comment]
If you're talking more about quotes with grammatical errors in them, then is <kbd>Report Quote</kbd> really a good wording idea? Maybe <kbd>Fix Quote</kbd> or something like that would be more appropriate.

**Comment by maixnor** [comment]
Should the reporting user be allowed to fix it immediately :hammer: (or hand in a change request) or just highlight :bulb: the quote for later inspections of the admins.

**Comment by UnrealApex** [comment]
Having flagged quotes be reviewed by admins would be a good idea but I'm not sure if there are any people other than Miodec willing to do that. The easiest solution would be telling users to file an issue on GitHub or talk to Miodec on the Monkeytype discord server.

**Comment by maixnor** [comment]
How about a "report quote" button which redirects to a new github issue with a template? 
In this template, the quotes' ID has to be included along with the reason for the report. 
The template also has a "quote report" label to be easily distinguishable from the dev tasks.

**Comment by UnrealApex** [comment]
That's a good idea. We could have users send in reports and @monkeytypegeorge could turn them into issues.

**Comment by Miodec** [comment]
The plan then:

- Add a button that allows to report the quote
- Show a popup where the user can add a message (with minimum length requirement) saying whats wrong
- Send a request to the api where a command is added to the bot (add a strict rate limit to avoid flooding issues and potentially getting the bot blocked form the github api)
- Bot creates the issue including the message and the username 

If users misuse the feature add a flag to their account which blocks them from the api endpoint and hides the button.

**Comment by timleg002** [comment]
> If you're talking more about quotes with grammatical errors in them, then is Report Quote really a good wording idea? Maybe Fix Quote or something like that would be more appropriate.

It could also be "Something wrong with the quote?" as to convey osmething more abstract. It's a bit longer though

**Comment by Bruception** [comment]
> The plan then:
> 
> * Add a button that allows to report the quote
> * Show a popup where the user can add a message (with minimum length requirement) saying whats wrong
> * Send a request to the api where a command is added to the bot (add a strict rate limit to avoid flooding issues and potentially getting the bot blocked form the github api)
> * Bot creates the issue including the message and the username
> 
> If users misuse the feature add a flag to their account which blocks them from the api endpoint and hides the button.

I think instead of enforcing a minimum length requirement, users can select an option from a dropdown with various issue options (Bad grammar, Obscenity, etc). Then they can elaborate with a message if needed.

Is anyone actively working on this feature?

**Comment by Miodec** [comment]
> I think instead of enforcing a minimum length requirement, users can select an option from a dropdown with various issue options (Bad grammar, Obscenity, etc). Then they can elaborate with a message if needed.

Sounds good.

> Is anyone actively working on this feature?

I dont think so.

**Comment by Bruception** [comment]
> I dont think so.

Do you think I can give it a shot?

**Comment by UnrealApex** [comment]
I you want to, go for it!

**Comment by Miodec** [comment]
Sure thing
