### ISSUE TITLE
Custom theme can't be toggled after refreshing site

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#1159]
After the big rewrite (1.8), the custom theme can no longer be toggled properly. It'll be lost after every refresh even it's toggled in the setting.

**Comment by Shazbot-cybersec** [comment]
I am also having the same Problem

**Comment by pingshunhuangalex** [comment]
It's changing a lot and is still ongoing. Feels like there's a rebranding going on. Instead of looking minimalist, it now looks gimmicky... I have a bad feeling

**Comment by Supesu** [comment]
Date: 1st of april

:)

**Comment by Supesu** [comment]
Its probably a April fools update....

:)

**Comment by Miodec** [comment]
Check now, custom themes should be fixed

**Comment by pingshunhuangalex** [comment]
Thanks @Miodec Everything is back to normal now.
Glad it's just an April's Fool thing. It's definitely not good for the heart. Didn't know MonkeyType means that much to me tho
