### ISSUE TITLE
Monkey type underwear links to wrong thing.

### ISSUE THREAD

**Issue by gmatlock** [Miodec/monkeytype#1160]
Using windows 10 on internet explorer, I think the monkeytype underwear is supposed to link to a video but its coming back as not found. IDK if its on my end or what. Ive tried resetting PC and clearing cache.

**Comment by UnrealApex** [comment]
this is serious, massive vulnerability in security, user data compromised, help monkey fix this by buying monkeytype special edition monkeytype boxers

**Comment by hashyxx** [comment]
the link opens up to never gonna give you up by Rick Astley. I wish I was joking haha. 


https://user-images.githubusercontent.com/79390283/113339318-35758f00-9322-11eb-97fe-9d497f66bdfe.mov

**Comment by Miodec** [comment]
Sorry, will get that fixed asap
