### ISSUE TITLE
can't use custom background images

### ISSUE THREAD

**Issue by Nishida02** [Miodec/monkeytype#1179]
**Did you make sure to clear cache before opening an issue?**
Sometimes your browser has old files cached and the bug you are experiencing might be already fixed, or a side effect of a new update. If you've already tried that, please delete this section. If you don't know how to do that, this website should help: https://clear-my-cache.com/
[I tried doing this but it still didn't work´]

**Describe the bug**
[I dont kno what is happening i just can't use background images]

**Did it happen in incognito mode?**
Sometimes things work in incognito mode, which allows me to further track down the issue.
[I tried on incognito mode as well but it still the same thing ]

**To Reproduce**
1. Go to 'settings'
2. Click on 'theme'
3. Scroll down to 'custom background'
4. Paste the link of the image 
5. And nothing happens 

**Expected behavior*
[I expected to apear the disired image on the back ground]

**Screenshots**
![adsfff](https://user-images.githubusercontent.com/81939140/113527897-60b3e480-9595-11eb-95c2-ca6db77717f4.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. opera gx]
 - Version [e.g. Early Access]

**Smartphone (please complete the following information):**

**Additional context**
[I don't know if i need to put anything else, i don't know if all the information needed is correct and sorry for my bad english if i miss typed anything.
But the rest of the site it's perfect. Thanks for the attention]

**Comment by Miodec** [comment]
Whats the image url?

**Comment by Nishida02** [comment]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fall-images.net%2Fwp-content%2Fuploads%2F2020%2F05%2FWallpaper-aesthetic-145.jpg&imgrefurl=https%3A%2F%2Fall-images.net%2Fwallpaper-aesthetic-145%2F&tbnid=NuCU87Jjm6mK2M&vet=12ahUKEwjeqamb6-nvAhV4ArkGHeYXARgQMyg_egQIARB1..i&docid=a34Agnr1qJe4nM&w=1920&h=1080&q=aesthetic%20images&client=opera-gx&ved=2ahUKEwjeqamb6-nvAhV4ArkGHeYXARgQMyg_egQIARB1]

**Comment by Nishida02** [comment]
forget for some reason it worked now
