### ISSUE TITLE
Add keymap legend style

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#1183]
Allow lowercase uppercase and blank. Default lowercase.

**Comment by seaerchin** [comment]
i'm interested in this issue - could i get some context on what you mean by keymap legend style?

**Comment by Miodec** [comment]
Basically add an option to toggle between theese:
![image](https://user-images.githubusercontent.com/13181393/113893462-f67e8800-97be-11eb-8547-da3d54e95812.png)
![image](https://user-images.githubusercontent.com/13181393/113893497-fed6c300-97be-11eb-8dce-5618f838dc3c.png)
![image](https://user-images.githubusercontent.com/13181393/113893571-10b86600-97bf-11eb-87f5-2a03910afe71.png)

**Comment by seaerchin** [comment]
is the css already done? i'm updating the related js files in settings but unsure if i need to do so for the sass file

**Comment by Miodec** [comment]
You will need to add a config property, add buttons to the settings page, settings to the command line and edit the css.

**Comment by seaerchin** [comment]
ran into a bit of a stumbling block - the html elements in the settings page aren't being updated by `updateButton`; i've created a `settingsGroup` to encapsulate the keyboard legend style settings and i'm not sure why this isn't being updated

**Comment by seaerchin** [comment]
@Miodec fyi, this is fixed in #1200

**Comment by t-e-r-m** [comment]
Yes!  Thanks a ton for implementing this!
