### ISSUE TITLE
Opposite shift not working with other system keyboard layouts

### ISSUE THREAD

**Issue by qupufu** [Miodec/monkeytype#1199]
**Describe the bug**
The opposite shift feature won't work when using a different keyboard layout and only checks to use the opposite of the qwerty key

**To Reproduce**
1. Turn on opposite shift
2. Switch to a keyboard layout other than qwerty
3. Start typing a test that requires you to use the shift key

**Expected behavior**
Should work on any keyboard layout and not just qwerty

**Desktop (please complete the following information):**
 - OS: Windows 10 OS Version 1909 (Build 18363.1379)
 - Browser: Chrome Beta 90.0.4430.51

**Additional context**
I don't know if this matters, but I'm using workman. I also tried to turn off portable keyboard layout and use the built keyboard remapping but that still didn't work either.

**Comment by Miodec** [comment]
I think this will happen if your system layout is anything other than qwerty.

**Comment by Miodec** [comment]
Can you test if its working correctly while your system layout is qwerty?

**Comment by uShldGetCeleste** [comment]
tested and it works fine when using qwerty

**Comment by Miodec** [comment]
Yeah, currently the only way to get that to work with other layouts is to use qwerty as system layout and use the website's layout override feature, since there is no way for me to detect the system layout.

**Comment by Estebene** [comment]
I was unable to replicate this with the Dvorak system layout and Windows 10. This may have something to do with the workman keyboard file changing the key codes that the browser reads.
