### ISSUE TITLE
Tests would refresh after automatically signed-in

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#1210]
Tests would refresh after automatically signed-in which is annoying...

**Comment by pingshunhuangalex** [comment]
Seems to be fixed

**Comment by pingshunhuangalex** [comment]
The bug came back again with the rolling out of v1.9...

**Comment by Miodec** [comment]
Happens on every login?

**Comment by pingshunhuangalex** [comment]
Yes, after the loading circle stops spinning, the test will get refreshed.

**Comment by Miodec** [comment]
There should be a console log - something like "db config is different "time" != "words"" Do you have anything like that?

**Comment by pingshunhuangalex** [comment]
Yeap, look like it's caused by the new funbox config features.
![image](https://user-images.githubusercontent.com/17170199/117572877-47fc9880-b118-11eb-9cc0-2c80a43ad2c4.png)

**Comment by Miodec** [comment]
If you change one thing about the config it will update it to your account after a second i think. Then if you refresh it should no longer apply the db config.

**Comment by pingshunhuangalex** [comment]
Works, not ideal tho.

Another baffling thing is the custom layout for fluid. Not sure how I can use `colemak dh` in the setting as items are separated by space... It keeps saying layout not recognised and reverting to default.

The input box also behaves a bit weird as it keeps selecting all of the text in the input box.

**Comment by Miodec** [comment]
For layouts like colemak dh you need to type in `colemak_dh`

**Comment by Miodec** [comment]
I just made a commit that should completely fix the refreshing. With this change it will refresh at most one time to load that missing key into the DB config.
