### ISSUE TITLE
Test results can no longer be saved somehow...

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#1213]
Everything was fine but suddenly no test result can't be saved...
![image](https://user-images.githubusercontent.com/17170199/114174743-625a1f80-997c-11eb-90b5-d86fb1a3db4c.png)

**Comment by pingshunhuangalex** [comment]
Seems to be fixed

**Comment by Miodec** [comment]
That was a short downtime to fix an issue with a cloud function
