### ISSUE TITLE
Clicking 'all filters' doesnt select all tags

### ISSUE THREAD

**Issue by bsamseth** [Miodec/monkeytype#1222]
**Did you make sure to clear cache before opening an issue?**
Yes, it even persists across browsers and/or devices.

**Describe the bug**
The account page shows the wrong info from the graph and down. That is, the following is correct:

![image](https://user-images.githubusercontent.com/8997458/114260234-e5f32b00-99d3-11eb-9f18-fae14c2b8bbd.png)

But scrolling down, both the graph and the stats summary only show data from some initial period from when I made the account:

![image](https://user-images.githubusercontent.com/8997458/114260335-7467ac80-99d4-11eb-95d4-69d62665547d.png)
![image](https://user-images.githubusercontent.com/8997458/114260277-1c30aa80-99d4-11eb-9f19-09ff2a1c8ded.png)

Notice for instance the total time spent typing is about half in the last screenshot compared to the top. 

I remember seeing later test results in the graph previously, using version 1.7.6. So this started somewhere between then and now (I know that probably helps minimally, given the large number of changes made since then).

**Did it happen in incognito mode?**
Same exact behavior regardless.

**To Reproduce**
1. I log in to my account
2. Go to the account page

**Desktop**
 - OS: [e.g. iOS] Ubuntu 20
 - Browser: Chrome, Firefox

**Smartphone:**
 - Device: iPhone
 - Browser: chrome, safari

**Comment by pingshunhuangalex** [comment]
May I ask what theme is this? Thanks

**Comment by Miodec** [comment]
Go into advanced filters, make sure everything is selected and check then

**Comment by karlshea** [comment]
I'm seeing the same issue. When I go to advanced, only "no tag" is selected. Clicking "all" directly under the "filters" heading does not select them. For me, manually selecting the tags does then show everything, but I can't speak for @bsamseth.

**Comment by bsamseth** [comment]
@Miodec @karlshea I can also confirm that it had to do with tags. Only the "no tags" option was selected, and selecting the remaining tags shows everything again. Thanks for the help!

I'd still argue that this is a bug, albeit only a UI one. From the screenshot above it says "all" next to the tag filter display

![image](https://user-images.githubusercontent.com/8997458/114349891-c2adb480-9b68-11eb-9b09-0c2a718f9c83.png)
 
I saw this displayed and naturally assumed that every tag would be shown. Do you agree, @Miodec ?

**Comment by bsamseth** [comment]
I also noticed that it resets back to the same view (only tests with no tags) when I get back after a while/hard refresh the page (ctrl+shift+r), making it all the more annoying having to set it back every time. I really believe the default filter settings should be no filter, as the UI seems to indicate already.

**Comment by Miodec** [comment]
Should be good now. Fixed in 99ecbe27cc62b31c9aa7b192386827c30ea95f28
