### ISSUE TITLE
Key map configuration does not show in settings

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1233]
**Describe the bug**
Keybind tips are not showing even though they are enabled in the settings. 

**To Reproduce**
1. Go to [https://monkeytype.com/settings](https://monkeytype.com/settings)
2. Click on the `hide elements` settings group button
3. Look for `keymap`

**Expected behavior**
Setting for key map would be there.  

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [chrome]
 - Version [89.0.4389.116 (Official Build) (64-bit)]

**Additional context**
After using the funbox `simon says` and settings the funbox value to `none`, key map show on the bottom of the screen.

**Comment by UnrealApex** [comment]
Are the key map and  key tip feature the same thing?

**Comment by CrumblyLiquid** [comment]
> 
> 
> Are the key map and key tip feature the same thing because I do not see any option for keymap in the settings page, only through command line?

Afaik keymap is the keyboard on screen and key tips are: "tab - restart test" and "esc - command line" that show up under the test when you're not typing

**Comment by CrumblyLiquid** [comment]
I checked for bot Firefox (87.0) and Chrome (89.0.4389.114) and it works as expected for both (they show up when they should and are hidden when they should)

**Comment by Miodec** [comment]
Its working for me correctly as well. @UnrealApex make sure you didn't mistake keymap and keytips.

**Comment by UnrealApex** [comment]
I realized my mistake, thank you @CrumblyLiquid and @Miodec .
There is no option to modify the keymap options in the settings page; the only way to do so is through the command line through the `Change keymap mode...` option.

**Comment by UnrealApex** [comment]
Never mind, found it in settings, apologies on my part for not digging in deeper into the problem.
