### ISSUE TITLE
funbox settings does not hold after completing a test

### ISSUE THREAD

**Issue by xPrzybyLx** [Miodec/monkeytype#1250]
**Did you make sure to clear cache before opening an issue?**
Yes, many times I have cleared the cache. It does not fix the issue.

**Describe the bug**
I am using funbox=ascii to learn typing various symbols. The funbox resets to "normal" English after each test. I have to restart the test for funbox=ascii to be reapplied. Also it looks like the funbox is not being counted properly in the chart/statistics (looks like it's being counted as "normal" english or engligh 1k or 10k etc...

**Did it happen in incognito mode?**
It also happens in incognito mode.

**To Reproduce**
1. Select funbox: ascii
2. Select English (standard or 1k or 10k)
3. Do one test, after it is completed You won't see ascii characters anymore, You have to restart the test for ascii symbols to be reapplied
4. See video

**Expected behavior**
I should see ascii symbols for each consecutive test.

**Screenshots**
[Image of the issue](https://imgur.com/QHcPoDA)

Video: https://youtu.be/BavDuUj-p-Q

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 + i3
 - Vivaldi 3.7.2218.52 (Stable channel) (64-bit)

**Smartphone (please complete the following information):**
- Not used

**Additional context**
- No additional info

**Comment by Miodec** [comment]
@Saint-dev would you mind taking a look at this? Looks like your recent PR might have caused this.

**Comment by Saint-dev** [comment]
Should be fixed with above PR. test-logic was calling funbox.active instead of the saved funbox
