### ISSUE TITLE
add carrot and banana to pace caret options

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1269]

**Comment by TheeKevin** [comment]
I guess this does the raise the question of whether or not you'll keep the carrot/banana as an easter egg.

If you do then I think it'll be really fun to add other easter eggs after multiplyer (trroibe). Like you could click a secret spot in the settings and it'd change the theme into the april fools theme (you could recycle it in that way) or something else. 

But if you don't keep it as an easter egg it'll still be a little fun to use.

**Comment by Miodec** [comment]
Added

**Comment by TheeKevin** [comment]
Wait what exactly did you add?

**Comment by Miodec** [comment]
Added them as hidden command line options 4a70f7e476bdba6fbd8625258c52626d61cf43f7

**Comment by TheeKevin** [comment]
ah makes sense 

I misinterpreted the question which is why I asked another question that didn't really make sense
