### ISSUE TITLE
Stuck with carrot caret

### ISSUE THREAD

**Issue by SongWithoutWords** [Miodec/monkeytype#1270]
**Describe the bug**
When I access the site I have the carrot caret. After signing out I still have it. If I sign out and then clear my browsing data/cache the issues goes away, but returns the moment I sign in again.

**Did it happen in incognito mode?**
The issue is similar in incognito mode. In incognito mode, if I access the site my cursor is normal, but I get the carrot caret again if I sign in.

**To Reproduce**
I don't think I can provide straightforward repro steps that aren't attached to a specific, bugged out account.

**Expected behavior**
Normal caret.

**Screenshots**
![image](https://user-images.githubusercontent.com/10523838/115138556-ce263300-9fe1-11eb-856c-f2cbfcceac0f.png)

**Desktop (please complete the following information):**
 - OS: Linux (Kubuntu 20.04) and Windows 10
 - Browser Chrome (89.0.4389.128), and Chromium (recent)

**Comment by TheeKevin** [comment]
Well have you tried switching it manually? If you've gotten as far as carrot then you should just be able to change it through the command line. Also, I'm pretty sure that's intentional because this is the same case with every caret (so that people don't have to constantly change their caret back).

**Comment by Miodec** [comment]
Just go into settings / command line and change the caret style to line

**Comment by SongWithoutWords** [comment]
I think you guys might want to change the way you override user settings for holiday themes in that case (maybe do it as a temporary override for the duration of the holiday), as persistently changing a user setting for a one-off event and not showing or indicating in the settings UI that you've changed it is counter-intuitive.

If you guys enabled it persistently for all user accounts and were relying on people to manually restore their own settings, I wonder how many accounts still have it on.

**Comment by Miodec** [comment]
Yes, I agree. It's a fuck up on my part and something I've totally overlooked. We still get questions on Discord on how to disable the carrot.

**Comment by SongWithoutWords** [comment]
Ah, shoot, well maybe some affected users will find this post and resolution via Google. Thanks for your help guys, great site and project, really helped me learn colemak :)
