### ISSUE TITLE
After login : home screen does not show up

### ISSUE THREAD

**Issue by 4shutosh** [Miodec/monkeytype#1288]
**Describe the bug**

After successful login using email and password, we should end up on the typing screen (i.e the home page) and the fields (email and password should be cleared), none of those happen. Though the user theme is fetched and updated.

**Did it happen in incognito mode?**
Yes, I checked on both incognito and normal tab as well

**To Reproduce**
1. Go to login
2. Enter the email and password fields, login
3. See error

**Expected behavior**
we should end up on the typing screen (i.e the home page) and the fields (email and password should be cleared)

**Desktop:** 
 - OS: [Linux] 
 - Browser [Chrome] 
 - Version [90.0.4430.72] 

**Additional context**

Please correct me I'm wrong.

**Comment by Miodec** [comment]
On login the website should go from login page to account page - is it not doing that?

**Comment by 4shutosh** [comment]
Nope. 
The account theme and the name are visible, but the fields are not cleared and it does not go to the account page as well.

**Comment by Miodec** [comment]
Which browser?

**Comment by 4shutosh** [comment]
Chrome latest stable version.

**Comment by Miodec** [comment]
So i tested on Chrome, both mac and windows - for me the website goes to the account page. I tried throttling the connection speed with the inspector tools but it still eventually makes it to the account page. Could you try again and leave it for a bit?

**Comment by 4shutosh** [comment]
Sure, Mine still exists tho, will update the status after few days.

**Comment by Miodec** [comment]
Well, i didn't mean waiting days, i mean waiting like a minute after logging in. Maybe it still is downloading the user data and that's why it doesn't move onto the account page?

**Comment by 4shutosh** [comment]
Please Take a look at this, I don't think this is an internet issue.



https://user-images.githubusercontent.com/53831987/115966181-28774480-a54a-11eb-8907-755858ec6c43.mp4

![image](https://user-images.githubusercontent.com/53831987/115966212-3d53d800-a54a-11eb-9e11-923389754585.png)

**Comment by Miodec** [comment]
I see, i'll keep looking then

**Comment by Miodec** [comment]
What happens when you enter `window.location.pathname` into the browser console?

**Comment by 4shutosh** [comment]
it says /login
![image](https://user-images.githubusercontent.com/53831987/115966481-5f018f00-a54b-11eb-9cee-33e173d3caf7.png)

**Comment by Miodec** [comment]
What about `$(".pageLogin").hasClass("active")` while on the login page, just before hitting sign in

**Comment by 4shutosh** [comment]
true

**Comment by Miodec** [comment]
Right, so I'm assuming the page transition is initiated, but something is broken inside of it.

**Comment by Miodec** [comment]
Alright, I've deployed some dirty console logs to try and find out what happens. After you clear cache, you should see console logs about the page transition. Try to login and screenshot the logs.

**Comment by 4shutosh** [comment]
![image](https://user-images.githubusercontent.com/53831987/115967033-f7990e80-a54d-11eb-8abe-e06ba686dd22.png)

**Comment by Miodec** [comment]
And this is after clicking sign in?

**Comment by 4shutosh** [comment]
yes

**Comment by Miodec** [comment]
Honestly, im lost at this point.

**Comment by Miodec** [comment]
Should be fixed now. Clear cache and let me know

**Comment by 4shutosh** [comment]
Fixed :tada:
Thank you very much.

**Comment by 4shutosh** [comment]
May I know what was going wrong?

**Comment by Miodec** [comment]
If the locally stored config was different compared to the one stored in the database, it would apply the config and restart the test. Test restarting locks page changing for a second to avoid issues. Thats why the page was not changing - because the database config was being applied
