### ISSUE TITLE
Privacy Policy not updated after merged pull request

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1295]
**Describe the bug**

**To Reproduce**

1. Click link to Privacy Policy 
2. See error

**Expected behavior**

Privacy Policy would have updated after latest merge that updated it.

**Desktop:** 
 - OS: [Chrome OS] 
 - Browser [Chrome] 
 - Version [89.0.4389.130 ]

**Comment by Miodec** [comment]
Not pushed yet.

**Comment by UnrealApex** [comment]
I forgot that new content is added in versions. Thanks for the reminder!
