### ISSUE TITLE
Keys that insert two characters with one press do not work [Arabic]

### ISSUE THREAD

**Issue by PAHXO** [Miodec/monkeytype#1297]
Keys that insert two characters at the same time do not work

In Arabic, there are certain keys that do so.

**To Reproduce**

1. Go to Add Arabic layout
2. Try to press any of those keys
![1000px-KB_Arabic svg 2](https://user-images.githubusercontent.com/9639436/115968602-573ced00-a541-11eb-8d2a-7b152b4282c5.png)

**Expected behavior**
Those characters to be typed

**Current behavior**
Input being ignored

**Desktop:** 
 - OS: Windows 10
 - Browser  Chrome
 - Version 90.0.4430.85

**Comment by Miodec** [comment]
The inupt rewrite is live now on the main site. Give it a quick test and let me know.
