### ISSUE TITLE
Funbox (plus one) not working after failing a test (master difficulty)

### ISSUE THREAD

**Issue by rvjanapin** [Miodec/monkeytype#1309]
**Describe the bug**

* Plus one mode in funbox not working after a failed test. It shows all the words as normal. 
* It gets fixed after I restart the test once more

**Did it happen in incognito mode?**
* Also happens in incognito

**To Reproduce**

1. Use master difficulty
2. Go to either words or time mode
3. Enable funbox plus one
4. Fail the test by missing a keystroke
5. Click on next test
6. See error

**Expected behavior**

* Expected to maintain plus one behavior
**Screenshots**
![image](https://user-images.githubusercontent.com/80207044/116216481-41b30780-a77b-11eb-832f-03464c595498.png)

**Desktop:** 

- OS: [Windows 10]
- Browser: [Edge] 
- Version [90.0.818.46]

**Comment by Saint-dev** [comment]
Should be fixed with above PR
