### ISSUE TITLE
It would really be cool to have a button similar to punctuation for specials.

### ISSUE THREAD

**Issue by richtera** [Miodec/monkeytype#1313]
It would be really nice to have the ability to practice special characters similar to upper case and punctionation. Things like `@#$%^&*(){}[]|\` and so on. It might be a fringe case for many people, but for any developers it's definitely very useful.

**Comment by Miodec** [comment]
Try ascii or specials funboxes

**Comment by richtera** [comment]
Sounds interesting.. What are "Try ascii or specials funboxes"? ok searching....
