### ISSUE TITLE
Auto repeat edge case breaks account statistics

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1316]
**Describe the bug**
When using auto repeat in zen mode for a period of time, the website freezes, after a reload account statistics are wrong.

**To Reproduce**

1. Start a `zen mode` test
2. Hold the `a` key on auto repeat(make sure the repeat rate is set to the max) for 60 or more seconds
3.  Reload or close tab and reopen it
4. Check account statistics and see if they are altered in any way
**Expected behavior**
Account statistics would not change

**Desktop:** 

- OS: [Chrome OS] 
- Browser [chrome] 
- Version [90.0.4430.86]

**Comment by UnrealApex** [comment]
After using auto repeat on zen mode, the account page does not load. After a few reloads, the page loads but the statistics are off.

**Comment by UnrealApex** [comment]
I will send a video to document.

**Comment by Miodec** [comment]
Check console for errors

**Comment by UnrealApex** [comment]
> I couldn't reproduce the issue but I limited zen mode to 30 characters per word.

@Miodec I would suggest changing the character per word limit to 50 characters because there are words that are over 30 characters,.
fun fact: the words longest word is pneumonoultramicroscopicsilicovolcanoconiosis, go google it to so for yourself :)

**Comment by UnrealApex** [comment]
I didn't see any errors in the console.
