### ISSUE TITLE
Monkeytype lags heavily during ad transitions

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1337]
When ads are enabled to `sellout` and ads transition, there is a notifiable lag spike as the advertisements transition.

**Comment by Miodec** [comment]
Doesn’t happen for me - probably depends on your pc?

**Comment by UnrealApex** [comment]
That would be true. I'm currently using a very low power chromebook because I can't access [my dev machine](https://www.amazon.com/MSI-GE66-Raider-10UH-210-i7-10870H/dp/B08R9GGMBS/ref=sr_1_3?dchild=1&keywords=msi+ge66+raider&qid=1620001443&sr=8-3) all the time so I use my chromebook for most of my development. For lower power computers(chromebooks, raspberry pis, etc... just loading youtube videos is a challenge.
