### ISSUE TITLE
Remove tooltip on personal best icon

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1362]
**Describe the bug**

When hovering over the personal best icon achieved when a personal best is reached, there is a tooltip with no data in it.

**To Reproduce**

1. Start a `time 30 english` test and get a new personal best
2. Hover over the personal best icon above the wpm

**Expected behavior**

There would be no tooltip if user hovered over the personal best icon or there would be some text in the tooltip
**Screenshots**

![Monkeytype](https://user-images.githubusercontent.com/79121360/117220010-41d68700-adbb-11eb-8cc6-9f68995eb1e4.gif)

**Desktop:** 

- OS: [Chrome OS] 
- Browser [Chrome] 
- Version [90.0.4430.86 ]

**Comment by dustinsbustin** [comment]
Was unable to reproduce.

**Video evidence**
https://dustin.gg/s5zgX2.mp4

Windows 10 Pro (Build 19041.928)
Chrome: 90.0.4430.93 (Official Build) (64-bit)

**Comment by UnrealApex** [comment]
Must be an error on my end.

**Comment by UnrealApex** [comment]
@dustinsbustin 
Another option you can use besides uploading videos to your website would be attaching a video file to your comment. See [File attachments on issues and pull requests](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) for more clarification.

**Comment by dustinsbustin** [comment]
Yeah I know but I prefer doing it the way I had done it, unless it is a requirement.
