### ISSUE TITLE
Repeat test should enable pace caret with the wpm of the previous test.

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#1369]
It should also remember the previous state of the pace caret settings so it can revert back.

**Comment by ivan-pop** [comment]
Can you add option in settings to disable this feature?
I usually play with master difficulty or accuracy limit and pace caret is annoying when i just want to improve accuracy and dont care about wpm.

**Comment by Miodec** [comment]
Added `repeated pace` setting. Will be live soon.
