### ISSUE TITLE
Overlapping settings text after closing menu

### ISSUE THREAD

**Issue by rustom** [Miodec/monkeytype#1375]
**Describe the bug** 
When the timer/progress style is changed to text and the escape menu is open and then closed, the word count text overlaps with the other setting buttons directly above the typing text. 

This occurs both on my account and in incognito mode.

**To Reproduce** 

1. Change timer/progress style from "mini" to "text"
2. Change word corpus from default to a certain number of words and/or enable pacing caret
3. Press "Esc" twice (to open and close the menu)

**Expected behavior** 
The text word counter should maybe be shifted up a line so that it does not overlap with the word corpus/average pace setting. This is just a small UI fix. 

**Screenshots** 
![image](https://user-images.githubusercontent.com/45826892/117505036-05389600-af49-11eb-80d0-fff0e48ab9c0.png)

**Desktop:** 

- OS: MacOS Big Sur
- Browser: Chrome
- Version: 1.8.5

**Additional context** 
I have freedom mode is enabled, but I believe this issue exists when it is disabled as well.

**Comment by Miodec** [comment]
Its not really an issue because those two elements 99% of the time are not visible both at once. Plus, if I move the progress up, once the mode notice disappears it will be too high.
