### ISSUE TITLE
Adding java quotes [low priority] [good first issue]

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1378]
It would be nice if there were Java quotes on Monkeytype.

**Comment by mtthwn** [comment]
I'd like to give this one a shot! How many quotes/what level of difficulty were you looking to add?

**Comment by Miodec** [comment]
Anything really, varying length and difficulty - all up to you

**Comment by UnrealApex** [comment]
@mtthwn 
I've already created a PR with one quote.

**Comment by mtthwn** [comment]
@UnrealApex Would you like me to append to that list after that PR's been merged? Sorry I didn't see it in the open PR's

**Comment by UnrealApex** [comment]
Sure, no problem.
