### ISSUE TITLE
Incorrect firebase auth domain with Google sign in

### ISSUE THREAD

**Issue by raymon-zhang** [Miodec/monkeytype#1379]
**Describe the bug** 
After clicking Google sign in button, the resulting dialog displays "monkey-type.firebaseapp.com" instead of "monkeytype.com". 

**To Reproduce** 

1. Go to [https://monkeytype.com/login](url)
2. Click on "Google Sign In"
3. See error

**Expected behavior** 
Expected the Google sign in dialog to say "monkeytype.com" instead of "monkey-type.firebaseapp.com"

**Screenshots** 
![image](https://user-images.githubusercontent.com/65573069/117515315-c4da1780-af4a-11eb-8542-f789bfadb5df.png)

**Desktop:** 

- OS: Windows 10 
- Browser Chrome 
- Version 1.8.5 

**Additional context** 
I believe this can be solved by:
1. Changing the "authDomain" property on the Firebase configuration to "monkeytype.com"
2. Whitelisting "https://monkeytype.com/__/auth/handler" in the Google developer console OAuth Client IDs under Authorized redirect URIs

**Comment by Miodec** [comment]
After contacting Firebase support i found out there is no way of changing that url. I've tested Google sign in and it works correctly, so I'll just have to leave it.

Full answer by DIGI on the Firebase Discord:
> you can't - Firebase auth manages the domain and the auth sign in. you would have to implement custom auth with your own server and redirects
