### ISSUE TITLE
Refactor all the ui elements to use American spelling

### ISSUE THREAD

**Issue by omackenzie** [Miodec/monkeytype#1384]
Some words are spelt in a preferred American English style (e.g. color), while others are a British spelling (e.g. randomise). In some cases, both different spellings are used, such as in this screenshot with "behavior" and "behaviour".
![behaviorvsbehaviour](https://user-images.githubusercontent.com/30273552/117529961-0b4c7680-b01e-11eb-95e1-e1b16984b654.PNG)
One standard should be chosen and stuck with.

**Comment by rustom** [comment]
Should this be changed directly in `index.html` or is there anywhere else where these spellings should be edited?

**Comment by Miodec** [comment]
All the files need to be checked pretty much because some popups / notifications are defined in javascript.
