### ISSUE TITLE
Can you add a mode for commonly misspelled words

### ISSUE THREAD

**Issue by one-loop** [Miodec/monkeytype#1385]
When I am typing, I often make the same mistakes on certain words (e.g. acquire, acknowledge, referred, relevant successful) beginning, so I was wondering if you can add a typing mode which contains commonly misspelled words. This means you can practice your typing as well as improve your spelling and make sure you don't make any embarrassing spelling mistakes in email in the future

**Comment by Miodec** [comment]
There is a button on the result page `repeat missed words`
