### ISSUE TITLE
Add a 'light' and 'dark' option to randomise themes. 

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#1386]
This will require all themes to be categorized as light or dark inside the themes 'list' file.

**Comment by rustom** [comment]
Another alternative might be using [TinyColor](https://github.com/bgrins/TinyColor#isdark) to automate the detection of light and dark themes based on the background color (the color of text itself typically doesn't matter). This would be a lightweight addition, but would you prefer it done in vanilla JS or using the library?

**Comment by Miodec** [comment]
Why not just go through the list of themes manually. We only have to do it once and then the website just needs to read the value. Not sure if a library is necessary just for this one tiny task.

**Comment by Miodec** [comment]
Actually why not, just use the library.
