### ISSUE TITLE
Custom layoutfluid doesn't work with layout names containing uppercase letters

### ISSUE THREAD

**Issue by tmwitczak** [Miodec/monkeytype#1395]
**Describe the bug** 

The custom _layoutfluid_ input prompt accepts layout names originally containing at least one uppercase letter, like `colemaQ` or `ISRT`, when written fully in lowercase, i.e. `colemaq`, `isrt`. In that case, though, the displayed keymap falls back to `qwerty` with no actual layout override during typing. Moreover, when the layout name is typed in the prompt correctly regarding the case, it's being discarded and the custom option is set to the default value `qwerty dvorak colemak`.

**To Reproduce** 

1. Go to [monkeytype](https://monkeytype.com)
2. Turn on the _layoutfluid_ funbox mode
3. In the dropdown menu choose `Change custom layoutfluid...` and type in a layout name containing uppercase letters, e.g. `ISRT` or `colemaQ`
4. See the notification `One of the layouts were not found. Reverting to default`
5. Repeat 3. but type in the name in all lowercase, i.e. `isrt` or `colemaq`
6. See the `qwerty` keymap being displayed with no actual layout override

**Expected behavior** 

Proper layouts are selected.

**Desktop:** 

- OS: Windows 10 
- Browser: Chrome 
- Version: 90.0.4430.93

**Comment by Miodec** [comment]
Fixed in 086b2d20a581c6944afbc3ce0138f0510d06d1bd. Will be live soon.
