### ISSUE TITLE
Clicking On settings#option should expand the option

### ISSUE THREAD

**Issue by antorkhan** [Miodec/monkeytype#1397]
**Describe the bug** 
In settings after collapsing all the options, if user clicks on specific settings (ex: behavior) , that particular option should expand.

**To Reproduce** 

1. Go to 'https://monkeytype.com/'
2. Click on 'settings'
3. Collapse all options.
4. Click on any specific setting like behavior or input.

**Expected behavior** 
Even if that field is collapsed, upon clicking on the header that particular option should expand.
**Screenshots** 
![image](https://user-images.githubusercontent.com/25868650/117708517-b82b1d00-b1f1-11eb-9dc8-2f256290d28f.png)

**Desktop:** 

- OS: [] Windows 10
- Browser []  Chrome
- Version [] 90

**Smartphone:** 

- Device: [] 
- OS: [] 
- Browser [] 
- Version [] 

**Additional context**

**Comment by rustom** [comment]
I wasn't able to replicate this behavior on Chrome. Do you encounter this issue across browsers and/or when you're not logged in?

**Comment by Miodec** [comment]
This is not really a bug, more of a quality of life change.

**Comment by mtthwn** [comment]
Should clicking on the option in the header close any other sections that are already collapsed? Or is it enough to just open the one that the user selects if it hasn't been opened already

**Comment by Miodec** [comment]
IMO only expand that section if its closed, and don't change any other sections.
