### ISSUE TITLE
Characters how need a SHIFT " to make ö, ü or ä suddenly not working anymore. [GERMAN]

### ISSUE THREAD

**Issue by thorstenSchmitz** [Miodec/monkeytype#1403]
1. 'I work on an english Keyboard. I have to press " + a to make the character ä ( or ü ö) '
2. As soon as I press " it shows up as an Typo, but normally it waits for the second key

After Log out and Login again, it works. But I have to restart allways.

Thanks

**Comment by Miodec** [comment]
An input rewrite should be merged in soon which should fix this so i will come back to this issue after that.

**Comment by Miodec** [comment]
Does it work here? https://seerlite.github.io/monkeytype/issue/531-input-rewrite/

**Comment by chinese-soup** [comment]
Hello. I am testing the same thing with Czech accents (Shift+ˇ and then a letter) and it works on that rewrite link you've posted.

**Comment by victorbnl** [comment]
There is the same problem with the circumflex accents on the french keyboard, which is an issue for the french ê or the Esperanto ĉ ĝ ĥ ĵ ŝ

It works on the seerlite.github.io link you sent

**Comment by socau** [comment]
Working on Spanish accents as well

**Comment by Mxrcon** [comment]
I'm having the same issues for Portuguese, special characters that need shift are identified as error no matter of how you type them.

**Comment by NorbertRop** [comment]
Have the same problem with polish characters "ąęć" on main website, on https://seerlite.github.io/monkeytype/issue/531-input-rewrite/ its working. Settings reset doesn't help

**Comment by DrGGCoolman** [comment]
@thorstenSchmitz deadkeys are an OS feature, and behave quite differently on Mac OS/ Windows. It might be usefull to know which OS you are using. I'm not having any issues with the US-International layout on windows ( I also type german with an english keyboard)

**Comment by lucas-lxx** [comment]
I had the same problem with â, ã, é, ê..., using portuguese, but it works with https://seerlite.github.io/monkeytype/issue/531-input-rewrite/ as far as I've tested

**Comment by Hello-Helo** [comment]
Same problem as Lucas-lxx, same language and OS

**Comment by Miodec** [comment]
Related to #531, will be fixed by #1325
