### ISSUE TITLE
Monkey type goes to custom typing test while taking practice missed words 

### ISSUE THREAD

**Issue by anoop1005** [Miodec/monkeytype#1431]
**Describe the bug** 

**To Reproduce** 

1. Take a typing test of 50 words 
2. After the test complete take the test of practice missed words 
3. The settings automatically goes to a custom test of lesser words instead of 50 words 

**Expected behavior** 

- OS: [] 
- Version []

**Comment by Miodec** [comment]
That's the intended functionality. Practise missed words starts a custom test with only the words you mistyped. The amount of words is based on the number of words you missed and how often you missed them, meaning your weaker words will appear more often in the practise mode.
