### ISSUE TITLE
Letters not highlighted at beginning when using simon says funbox. 

### ISSUE THREAD

**Issue by Banzobotic** [Miodec/monkeytype#1435]
**Describe the bug** 

When using the simon says funbox in tribes no letter is highlighted on the keyboard. It will show up once a random letter is typed. 

**To Reproduce** 

1. Go to tribes on the monkeytype dev website
2. Go into a private room and select the simon says funbox
3. Add someone else to the room
4. Start and see that no letter is highlighted on the on screen keyboard

**Expected behavior**

A letter should be highlighted from the beginning. 

**Desktop:** 

- OS: [Windows 10]
- Browser [Chrome]
- Version [Dev] - Is this monkeytype version?

**Comment by UnrealApex** [comment]
@Banzobotic to clarify, the version is the version of your browser.

**Comment by UnrealApex** [comment]
@Miodec is the dev version the `tribe` branch?

**Comment by Miodec** [comment]
Yes but the tribe branch on `origin` is out of date. Plus to work on tribe you would need the server code which is not available.

**Comment by Saint-dev** [comment]
This is happening while not on tribe too.

For some reason `$(".active-key").removeClass("active-key");`  in config.js is being called after active key is set in keymap.js so when the test starts there is no key highlighted. 

![image](https://user-images.githubusercontent.com/25359372/118708272-84e81f80-b7e9-11eb-8a94-13ffedc4a9d5.png)

Also if you start a "simon says" test and then change back to funbox "none" the keymap still persists. Separate bug but I can look into all of this when I have time

**Comment by Miodec** [comment]
I just tried it and im not experiencing the keymap key not being highlighted. What are the exact steps?

**Comment by Miodec** [comment]
Nevermind, i just got it
