### ISSUE TITLE
Insertion point can't keep up with the speed when typing 200+ wpm

### ISSUE THREAD

**Issue by ZealShadow** [Miodec/monkeytype#1443]
When you type over 200+ wpm the insertion point can't keep up with speed, here's a screen shot
Device: Laptop
OS: Windows 10
Browser: Google Chrome
Browser Version: Chrome Version 90
![image](https://user-images.githubusercontent.com/74703939/118700299-5d805b00-b7c7-11eb-8a74-b7deacc79d2e.png)

**Comment by ZealShadow** [comment]
Another screenshot 
![image](https://user-images.githubusercontent.com/74703939/118700457-8bfe3600-b7c7-11eb-9d10-7d48baebdee4.png)

**Comment by ZealShadow** [comment]
![image](https://user-images.githubusercontent.com/74703939/118700559-a9cb9b00-b7c7-11eb-80b5-5f6311ed0879.png)

**Comment by Miodec** [comment]
Disable smooth caret

**Comment by ZealShadow** [comment]
Smooth caret has already been disabled.

**Comment by Miodec** [comment]
Try changing to a different theme? Rgb might be causing lag?

**Comment by ZealShadow** [comment]
Tried that too didn't work.

**Comment by Miodec** [comment]
Can you record it?

**Comment by ZealShadow** [comment]
The recording is ending up corrupted, I don't know why tried it many times

**Comment by ZealShadow** [comment]
I have also checked my Wi-Fi, It is fast

**Comment by ZealShadow** [comment]
![image](https://user-images.githubusercontent.com/74703939/118717538-0c7a6200-b7db-11eb-912e-db5a686f204e.png)

**Comment by ZealShadow** [comment]
![image](https://user-images.githubusercontent.com/74703939/118717709-3d5a9700-b7db-11eb-996e-5c19a59a84c5.png)

**Comment by ZealShadow** [comment]
asdfghj

**Comment by Miodec** [comment]
I can't really help if you can't get this on video, because so far only you're having issues like that

**Comment by ZealShadow** [comment]
Alright. Should I close this?

**Comment by Miodec** [comment]
Try and get it recorded if not I can't really do much

**Comment by ZealShadow** [comment]
Alright.

**Comment by Miodec** [comment]
Closing for now. If you manage to get it on video comment on the issue again.
