### ISSUE TITLE
Stop on word causes replay bug

### ISSUE THREAD

**Issue by lukew3** [Miodec/monkeytype#1445]
Enabling stop on word causes replay to perform strangely.
![Prob_Replay_bug](https://user-images.githubusercontent.com/47042841/118733676-b7eedb00-b80a-11eb-87b9-ba235c6ed7e8.png)
I think that something throws off the replay render method when backspace occurs.

**Comment by lukew3** [comment]
I can probably fix it myself, I just can't right now and don't want to forget about it.

**Comment by Miodec** [comment]
Already fixed
