### ISSUE TITLE
Timer contrast too low on Arch theme

### ISSUE THREAD

**Issue by cyqsimon** [Miodec/monkeytype#1446]
![Screencap_001_2021-05-19_08-08-13](https://user-images.githubusercontent.com/28627918/118738508-d5a75900-b879-11eb-9c5a-ae5d8a51cd8d.png)

P.s. There is, in fact, a timer above the words... You just have to turn up the screen brightness and squint really hard.

I hope you can see that the timer's contrast is wayyy too low. It is barely visible in low-light conditions, and in daytime it's just not visible at all.

A colour such as `#2c2f39` would be much better:

![2c2f39](https://user-images.githubusercontent.com/28627918/118739314-c0cbc500-b87b-11eb-952a-c99e2888eeb5.png)

**To Reproduce**

1. Switch to "Arch" theme
2. Toggle timer display to enable the centered large timer
2. Start a timed typing test

**Other sections omitted due to being unnecessary**

- OS: Windows 10 20H2
- Browser Chrome Dev 92

**Comment by Miodec** [comment]
You can change the timer color in the settings
