### ISSUE TITLE
Show all lines not working

### ISSUE THREAD

**Issue by connerf** [Miodec/monkeytype#1451]
Show all lines not working. I can only see three lines. Incognito does not work

This issue is recent.

- OS: - Windows
- Browser - Chrome
- Browser Version - Version 90.0.4430.212 (Official Build) (64-bit)

<img width="1114" alt="result" src="https://user-images.githubusercontent.com/57424246/119035461-73775280-b964-11eb-9f4a-357c4fdc3f89.png">

<img width="980" alt="settings" src="https://user-images.githubusercontent.com/57424246/119035594-94d83e80-b964-11eb-9d9a-a79a5481d265.png">

**Comment by Miodec** [comment]
It will not work in time mode. Are you using time mode?

**Comment by connerf** [comment]
I am/was. 

Perhaps the default settings changed recently and now the functionality is different. I'm getting all the lines to show when "words" are selected.

Is this feature new?

**Comment by Miodec** [comment]
Show all lines never worked for time mode. Nothing was changed about it for months.
