### ISSUE TITLE
Fuzzy select does not narrow down the result

### ISSUE THREAD

**Issue by Ultrahalf** [Miodec/monkeytype#1453]
->Fuzzy select does not narrow down narrow down the selection when typed

![image](https://user-images.githubusercontent.com/41832211/119169257-6b600580-ba7f-11eb-9923-803bc1df6f8a.png)

**Did it happen in incognito mode?**

Sometimes things work in incognito mode, which allows me to further track down the issue.

->Same result in incognito mode

**To Reproduce** 

1. Press esc
2. search 'change layout'-> then search 'colemak dh matrix'
3. we still get 4 result.

**Expected behavior** 
fuzzy select should narrow down the result as we type.

**Desktop:** 

- OS: []  Linux
- Browser []  Firefox and brave
- Browser Version []  Firefox: 88.0.1 (64-bit) and Brave: Version 1.24.85 Chromium: 90.0.4430.212

**Comment by Miodec** [comment]
Merged a pr with a fix
