### ISSUE TITLE
Searching a user accounts name in DuckDuckGO seems to show the website.

### ISSUE THREAD

**Issue by MysteriousLog6** [Miodec/monkeytype#1458]
Happens on every device , doesnt seem to happen in google but does on duckduckgo.

Typing my user name will also show the monkeytype.com website.

It doesn't seem to leak any data , but this behavior is unusual.

**Comment by Miodec** [comment]
Maybe duckduck finds monkeytype because the text of your username is in the website? Maybe it does some local text checking. Whats your username ill try to reproduce it.

**Comment by MysteriousLog6** [comment]
> Maybe duckduck finds monkeytype because the text of your username is in the website? Maybe it does some local text checking. Whats your username ill try to reproduce it.

Username: Mysteriouslog6

**Comment by Miodec** [comment]
Yeah, when i look for your name it only finds your stackoverflow, reddit, github and so on. I think duckduck might be checking local cache/website data to augment ita search results.

**Comment by MysteriousLog6** [comment]
> Yeah, when i look for your name it only finds your stackoverflow, reddit, github and so on. I think duckduck might be checking local cache/website data to augment ita search results.

Thanks for clarifying!
