### ISSUE TITLE
Hitting space after a mistake or first letter causes caret to move to next line

### ISSUE THREAD

**Issue by 735l4** [Miodec/monkeytype#1473]
Hitting space after a mistake is causeing caret to move to next line without completing.

<!--

**Did it happen in incognito mode?**

Sometimes things work in incognito mode, which allows me to further track down the issue.

**To Reproduce** 

1. Go to monkeytype
2. type incorrect letter at the beginning 
3. Hit space

**Expected behavior**
Mark mistake and not jump to another word staight

**Screenshots** 
![image](https://user-images.githubusercontent.com/42088682/119754016-7ff92f00-bebf-11eb-8286-4bd01c655152.png)

**Comment by Miodec** [comment]
By design. If you don't want it to move forward use `stop on error: word` mode
