### ISSUE TITLE
Presets don't save funbox settings

### ISSUE THREAD

**Issue by Munzu** [Miodec/monkeytype#1479]
**Describe the bug** 

My presets don't save funbox settings. I'd like to make a preset with the read-ahead setting for practice. When I save and apply the preset, the funbox setting is still on default instead of read-ahead.

I tried clearing my Firefox cache and I wanted to try it in incognito mode too but for some reason I can't sign in in incognito mode.

**To Reproduce** 

1. Go to settings
2. Select a language, in my case German
3. Select funbox setting "read ahead easy"
4. Scroll back up to "presets"
5. Create a preset and name it
6. Refresh the site. This will reset preset settings as expected 
7. Go to settings
8. Select English
9. Select the preset 
10. Go back to typing screen

The words will be German so that tells me the preset successfully saved and applied German as the language, however, funbox will still be "none."

**Expected behavior** 

I expect the preset to also save the funbox setting so that I just have to apply the preset and I'll have "read ahead easy" applied as well.

**Screenshots** 

If there's a screenshot that you need, please let me know.

**Desktop:** 

- OS: [Windows 10] 
- Browser [Firefox] 
- Browser Version [88.0.1 (latest as of writing this issue)] 

**Additional context**

**Comment by Eloren1** [comment]
Presets are broken, I can't apply them
