### ISSUE TITLE
Always the same text when logged in

### ISSUE THREAD

**Issue by Takeo12** [Miodec/monkeytype#1488]
**Describe the bug** 

If you log in and start a test, always the same text "The quick brown fox jumps over the lazy dog" appears. 

**To Reproduce** 

1. Login
2. Click on the monkeytype link
3. complete test

**Expected behavior** 

If you are not logged in, the website works normal. The tests are long and change every time you select a new one. 

**Screenshots** 

![Screenshot 2021-05-30 212249](https://user-images.githubusercontent.com/46075858/120117393-40676700-c18d-11eb-8764-91e71f8e448c.png)

**Desktop:** 

- OS: Windows 
- Browser Chrome 
- Browser Version  90.0.4430.212

**Comment by Miodec** [comment]
Top right, change mode to time or words. Custom mode will always have the same text
