### ISSUE TITLE
Account data not displayed on account page

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1499]
**Describe the bug** 
No account data is shown on the account page with the exception of the pbs(personal bests), tests started and completed, and time typing

**To Reproduce** 

I don't think this is reproducible.

**Expected behavior** 
When account page loaded, statistics would show.

**Screenshots** 
![Screenshot 2021-06-01 9 06 23 AM](https://user-images.githubusercontent.com/79121360/120356222-eebbfb00-c2b8-11eb-853b-97eac2c1ecea.png)
![Screenshot 2021-06-01 9 02 29 AM](https://user-images.githubusercontent.com/79121360/120356224-ef549180-c2b8-11eb-82f1-5a25c8c7e8fc.png)

**Desktop:** 

- OS: [Chrome OS] 
- Browser [Chrome] 
- Browser Version [90.0.4430.86 (Official Build) (64-bit)] 

**Additional context** 
I believe the cause of this bug was edge case testing I did last month. I tested to see if holding down a key with auto repeat on in zen mode would break anything. I held down a key until Monkeytype crashed. After a few days, I noticed the statistics weren't updating after doing tests. Occasionally the statistics would load, but now they do not.

**Comment by Miodec** [comment]
Click `all` filters.

**Comment by UnrealApex** [comment]
When clicking the `all` filters button, nothing happens.

**Comment by UnrealApex** [comment]
It does appear that something tries to load.

**Comment by Miodec** [comment]
Open the advanced filters and make sure everything is selected?

**Comment by Miodec** [comment]
Just pushed an update that should avoid this issue happening in the future.

**Comment by Miodec** [comment]
Ill close the issue, reopen if the filters break again.

**Comment by UnrealApex** [comment]
I'll be on the lookout.
