### ISSUE TITLE
Signed out, can't log back in.

### ISSUE THREAD

**Issue by zenVentzi** [Miodec/monkeytype#1513]
My password manager has saved my user name and password but not email. I've got two emails. None of them seems to be in use. At least that's what it says. The password is 100% the one from the password manager. Also the username. I'd really appreciate if I can log back in with my username or anyway

EDIT: there seems to be a change where now you have to log in with your email whereas previously it's been with username

EDIT2: The email that I got an alert saying "not found in records"(not these exact words) was actually there. I clicked on forgot password, entered that exact email, and recovered my account.

**Comment by Miodec** [comment]
> EDIT: there seems to be a change where now you have to log in with your email whereas previously it's been with username

You always had to use the email address to log in.

> I clicked on forgot password, entered that exact email, and recovered my account.

Nice. Closing.
