### ISSUE TITLE
I cant type ê and î in french because the accents dont seem to work

### ISSUE THREAD

**Issue by petertwishart** [Miodec/monkeytype#1525]
Hi 

I love this project  !

i have a problem when i try to type ê and î in french. The accents dont seem to work, so it counts as a mistake / error.

i am on chrome, windows 10, azerty keyboard

hope you can help

**Comment by Miodec** [comment]
Make sure your layout override in the settings is set to default.

If that doesnt work then you might have to wait for the input rewrite to be completed, as this has been an issue for quite some time and there are many issues open about this already
