### ISSUE TITLE
Different values for "time typing" statistic

### ISSUE THREAD

**Issue by kiriDevs** [Miodec/monkeytype#1527]
**Describe the bug** 
When opening my profile statistics page, there are two "counters" for the time I spent typing: One at the top-right of the page, one is at the bottom-left of the page.

**Did it happen in incognito mode?**
Yes.

**To Reproduce** 
1. Go to your profile page
2. Read the counter on the top-right of the page
3. Read the counter on the bottom-left of the page
4. Compare the values

**Expected behavior** 
Both counters display the same time I spent typing on the site while logged in with my account.

**Screenshots** 
*Will upload them ASAP, just have to figure out why it doesn't work right now*

**Additional context** 
- It seems like the upper-right has almost exactly 2min 30sec more time on it, but that might just be a coincidence with my specific values and account.
- I thought it might have something to do with me doing tests right before so I also waited a few minutes before checking again, just to still see different values.

**Comment by Miodec** [comment]
How many tests have you completed? The bottom value is limited by the 1000 results limit.

**Comment by kiriDevs** [comment]
Definitely not 1000 - let me check... 372 completed, 395 started.

**Comment by Miodec** [comment]
What are the exact values?

**Comment by kiriDevs** [comment]
Top-right: 02:33:25
Bottom-left: 02:30:59

**Comment by Miodec** [comment]
Im assuming this is still a problem after refreshing

**Comment by kiriDevs** [comment]
Yes, it is. Also on different devices and after clearing caches.
Also I believe I didn't start any tests for the last 24 hours.

**Comment by Miodec** [comment]
Do the 'tests completed' numbers match aswell? The one above and below the graph. Could be that you are filtering out some tests and that's why the times don't match.

**Comment by kiriDevs** [comment]
Above the graph:
- Tests Started: 407
- Tests Tompleted: 383
- Time Typing: 02:33:25

Below the graph:
- Tests Started: 395
- Tests Completed: 372
- Time Typing: 02:30:59

The filters all say 'all' though, and nothing changed after I clicked the 'all' button for the filters. For the time span 'all time' is selected.

**Comment by Miodec** [comment]
Open the advanced filters and make sure everything is selected. If it is, that means there is an issue with filtering.

**Comment by kiriDevs** [comment]
Yes, everything is selected under the advanced settings.

**Comment by Miodec** [comment]
So it must be the filtering thats broken. When you login and go to the account page, open the browser console and type in `snapshot().results.length`. What number do you get?

**Comment by kiriDevs** [comment]
\> snapshot().results.length
< 480

**Comment by Miodec** [comment]
And whats your current 'tests completed' statistic? Both at the top of the account page and when all filters are active?

**Comment by kiriDevs** [comment]
At the top: 491
At the bottom: 480

**Comment by Miodec** [comment]
Had another look into the filters - looks like it was including afk time in the time. Please test again. If your results are < 1000, when pressing the 'all' filter make sure the test completed and time typing match above and below the graph.

**Comment by kiriDevs** [comment]
That didn't really seem to change a lot for me, the two are still different. As we had established earlier, the numbers for "tests completed" are different as well, even if "all" is selected, so it probably filters some test out that it shouldn't filter out.

But I can confirm now that right now, both counters do not include AFK time.

I also had the idea that one maybe included time spent in cancelled tests, but apparently neither do that aswell.

**Comment by Miodec** [comment]
Okay, this is the only way that I can come up with to debug this. Ive pushed an update that allows you to enable a filter debug from the console. Quick screenshot of how it works:

![image](https://user-images.githubusercontent.com/13181393/126019990-3de66307-330d-41f2-84d6-dcb6a496857e.png)

Let me know what pops up.

**Comment by kiriDevs** [comment]
It does not seem to skip any results, *but* after waiting for a few seconds after clicking, I get an error:
![image](https://user-images.githubusercontent.com/56218513/126021039-e5363555-bb02-4dd0-8901-6b0284bc4af4.png)

**Comment by Miodec** [comment]
Right, I'm not sure then.

Whats the difference again between `snapshot().results.length` and complete tests at the top of the account page?

**Comment by kiriDevs** [comment]
Currently, it is 11.
`snapshot().results` has a length of 488, the top of the page displays 499.

**Comment by Miodec** [comment]
I don't know how the numbers got out of sync then...

**Comment by Miodec** [comment]
The only explanation i have is that 11 of your tests failed to save midway through. Send me your account name ill resynchronize the numbers.

**Comment by kiriDevs** [comment]
Sure, it's `kiriTypes` (very creative, I know).

Are these two numbers actually two numbers in the database? If so, what is the reason for that?

**Comment by Miodec** [comment]
Okay, ive reduced the stats by 11 so hopefully it should be synced.

Only the top numbers are stored. The bottom one is calculated based on the number of results found on your account. It could be that the code failed somewhere in between adding the result and incrementing the data, making it out of sync. Or there is a bug somewhere.

**Comment by kiriDevs** [comment]
Sorry for not replying sooner, but the numbers are indeed synced for me now.
