### ISSUE TITLE
word change

### ISSUE THREAD

**Issue by justklauz** [Miodec/monkeytype#1537]
**Describe the bug** 

**To Reproduce** 

**Expected behavior** 

**Screenshots** 

**Desktop:** 

- OS: [] 
- Browser [] 
- Browser Version [] 

**Additional context**

**Comment by justklauz** [comment]
Words change every 1 second when you begin typing and it won't let you type the word completely

**Comment by Miodec** [comment]
Please send a screenshot of the browser console when this happens

**Comment by justklauz** [comment]
> Please send a screenshot of the browser console when this happens

can't seem to happen right now
