### ISSUE TITLE
"repeat quotes" option should be added for other modes as well

### ISSUE THREAD

**Issue by Kelvets** [Miodec/monkeytype#1541]
If I screw up badly during the regular default random words test, I might want to repeat the exact sequence of words I just got; or might just keep repeating the same exact sequence to see how much my WPM improves over time as I learn the sequence of words by heart. However, clicking Repeat Test during typing will change the sequence of words provided. In the options menu, there is only the "repeat quotes" option, which only works for "quote" mode, not for the "words" mode, which I don't understand the reason for. This option should be universal.

![Screenshot_13](https://user-images.githubusercontent.com/3800465/121818835-0f446780-cc60-11eb-8412-6bf5bb0318d6.jpg)

**Comment by Miodec** [comment]
This wouldn't make much sense for words and time because repeated tests in those modes don't save.

**Comment by CapularisPerpetua** [comment]
Presumably the seed information for generating the test is easily retrievable? And you could merely regenerate the same values?
