### ISSUE TITLE
Error when changing languages after re-typing quotes.

### ISSUE THREAD

**Issue by kiriDevs** [Miodec/monkeytype#1542]
**Describe the bug**
When changing the language after repeating a quote, the site tries to repeat that quote in the new language, therefore only gives the same quote over and over again (since it is still in "repeat-a-quote-mode")

**Did it happen in incognito mode?**
Yes.

**To Reproduce** 
1. Change the mode to quote
2. Type the quote
3. Use the "repeat" function to type the quote again
4. On the completion screen of the repeat, change the language
5. See the error at the top-right corner: "Quote ID not found" and a specific quote in the new language.
If you type the new quote and want to go to the next, it will repeat that one quote in the new language and show the error again.

**Expected behavior**
I go into the normal quote mode and get the usual, random quotes.

And no error message, obviously.

**Comment by Miodec** [comment]
Can't reproduce this issue, did you include all the steps necessary?

**Comment by kiriDevs** [comment]
I can't seem to get it again as well now.

Maybe it was a weird interaction between multiple of my settings or maybe the WiFi connection gave up and the quotes of the new language didn't load properly or something.

I might try again later today and see if it happens again (and make sure to record everything), but for now I'll close the issue.
