### ISSUE TITLE
Favorites theme notice.

### ISSUE THREAD

**Issue by ZealShadow** [Miodec/monkeytype#1543]
I would like to know if you could remove the notice board when the colors change, I think it's a little bit annoying to find the notice change after every test.
Can you add a setting to not display this notice, thanks.
![image](https://user-images.githubusercontent.com/74703939/121974835-1ee1b000-cd35-11eb-8b2c-2d88aa5e435b.png)

**Comment by ZealShadow** [comment]
This is not an issue. Like an update sort-of thing 
Thanks

**Comment by Miodec** [comment]
Since current theme shows up in the bottom right - sure.
