### ISSUE TITLE
Add English 200

### ISSUE THREAD

**Issue by bl0bcode** [Miodec/monkeytype#1550]
I think it would be cool if there was an English 200 option instead of only having 1k, 10k, 25k, and 450k. I know there is also just the default "english" option as well, but I'm pretty sure that that isn't 200 different words. Thanks! 

- bl0bcode

(please correct me if there is a way to get english 200 or something like that lol)

**Comment by Miodec** [comment]
> but I'm pretty sure that that isn't 200 different words

It is 😂
