### ISSUE TITLE
Caret offset during typing

### ISSUE THREAD

**Issue by TheBB** [Miodec/monkeytype#1560]
**Describe the bug**

The caret is offset by one character. Before typing a word, the caret is one position to the right of where it should be, while during typing it is one position to the left. See below for video.

It happens in incognito mode.

**To Reproduce** 

1. Just play any typing game.

**Expected behavior**

That the caret is in the correct location.

**Screenshots**

https://streamable.com/7g4s7a

**Desktop:**

- OS: Ubuntu 20.04 
- Browser: Firefox 89.0.1 and Chrome 89.0.4389.114 both reproduce the error

**Comment by Miodec** [comment]
Fixed already
