### ISSUE TITLE
stats say afk while not being afk

### ISSUE THREAD

**Issue by iamlambda** [Miodec/monkeytype#1567]
Hey, Iooks like the code to verify if someone is AFK is broken, I have a pretty high consistency in both shots so it shouldn't say I've been AFK at all. Here are 2 screenshots:
![2021-06-22-191242_1127x421_scrot](https://user-images.githubusercontent.com/77165319/122970197-e32a9400-d38d-11eb-91de-2511a89e3680.png)
![2021-06-22-191646_1135x351_scrot](https://user-images.githubusercontent.com/77165319/122970614-6f3cbb80-d38e-11eb-80c3-b53369756671.png)
I do get that AFK thing on every test.
### Deskop:
- OS : Arch linux
- Browser : Firefox 89.0.1

**Comment by Miodec** [comment]
Can you verify that this only happens for `failed` tests?

**Comment by iamlambda** [comment]
After several tries, I only get that bug when I fail a test (not on every failed test). I can't get that bug while getting the test right.

**Comment by Miodec** [comment]
Should be fixed now.
