### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by karstenhunstad** [Miodec/monkeytype#1573]
I Would like an option to automatically start the "Practice Missed Words" immediately after finishing/failing the typing test

**Comment by Miodec** [comment]
Next time use Discussions as it was mentioned while creating this issue.

To answer the actual suggestion - I don't think its a good idea to start a test automatically. When you type fast you might not notice that you failed, and you will start typing in the new test without even realising. I think it's best to keep it manual.
