### ISSUE TITLE
Purging offensive words/words not appropriate for a workplace(NSFW) in language files from Monkeytype

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1582]
The language files contain offensive and or NSFW words. While I'm glad you took [my suggestion](https://github.com/Miodec/monkeytype/pull/1360#issuecomment-833065783) of only allowing pull requests to be merged  if they have been reviewed by a user who has given a review and approved the PR, but the damage has already been done. The language files especially the 1, 10, 25, and 450k.jsons are massive in size making them tedious to review to their fullest extent.  The contributions were probably of good faith, but the contributors failed to check the content of which they retrieved(or typed the words with malicious intent in mind). It's hard to detect subtle words such in large files leaving a margin for error. 

### The Solution/Effect

First of all, I just want to say that I don't want to put any stress on you. The solution to this problem is providing each language file a full read-through and remove any offensive words found in each one if any. Or having a workplace safe mode that omits any profane words in quotes and words lists. Doing this for quotes is up to you. Like I stated previously on reviewing language files, this will be time consuming, but should be of high priority.

### Discussed in https://github.com/Miodec/monkeytype/discussions/1581
<div type='discussions-op-text'>

<sup>Originally posted by **okpreetam** June 29, 2021</sup>
Recently I'm doing monkeytype and tackle the word "**UPSKIRT**". As English is my second language I know that this word is not appropriate for this platform, or maybe I do not know the correct meaning of this word so I googled it and got some awkward results 😂. This is the first time I face such a word in my 28 hours of typing time.

**So It is good to blacklist some NSFW words, at least for people below 18.**

> It would be good if we comment down such words. so it easy for monkey type to rectify them.</div>

 Thank you.

**Comment by Miodec** [comment]
Removing bad words from lists is a good idea. However, quotes I think are a bit different. Occasional 'fuck' here and there is fine I think.

What do you propose to further purge the lists?

**Comment by UnrealApex** [comment]
For quotes I agree. Nothing fancy for purging the lists, just skimming through the files. For future PRs for languages maybe have two people review them? Even with 200+ contributors, I feel that most people won't take the time to this but I could give it a go.

**Comment by Miodec** [comment]
Alright, i went through the project and removed bad words.
