### ISSUE TITLE
Crown tooltip is always empty

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#1583]
**Describe the bug** 
The tooltip is always empty upon hovering over the crown icon when you reach your new PB

**To Reproduce** 
I've seen it at least a handful of times across several versions. Unfortunately, I don't have a large enough sample size as it's not that easy for me to reach new PB frequently and I always stick to one mode.

**Expected behavior** 
It should display the diff between the old and the new PB

**Screenshots** 
![image](https://user-images.githubusercontent.com/17170199/123959045-148c0b00-d9f1-11eb-881e-60f1c866eb85.png)

**Desktop:** 

- OS: [Windows 10] 
- Browser [Chrome] 
- Browser Version [91.0.4472.124] 

**Additional context** 
![image](https://user-images.githubusercontent.com/17170199/123959547-a8f66d80-d9f1-11eb-8dd0-e5ee698bd77c.png)

**Comment by arybi** [comment]
What mode were you playing in when you encountered the bug?

**Comment by Miodec** [comment]
Yeah i also can't reproduce it.

**Comment by pingshunhuangalex** [comment]
60s time mode, default English, nothing fancy

**Comment by Miodec** [comment]
No tags, nothing?

**Comment by pingshunhuangalex** [comment]
No tags no, but using custom theme if that matters

**Comment by Miodec** [comment]
Ive added `crownTest()`. Run that from the console and let me know the result. Make sure to first open the account page.

**Comment by pingshunhuangalex** [comment]
Is it already added? It said `crownTest` not defined when I invoke it in console...

**Comment by Miodec** [comment]
Yes, clear cache if its undefined.

**Comment by Miodec** [comment]
What is your account name? Gotta check where that 88.99 is coming from

**Comment by pingshunhuangalex** [comment]
`pingshunhuang`. `88.99` was from one of my previous tests, and then I reset my pb one day and only reached `86.8` as pb so far

**Comment by Miodec** [comment]
That makes sense now. You resetting your pb caused the empty popup.

**Comment by pingshunhuangalex** [comment]
Mmm, shouldn't the tooltip get rebased to local pbs after a reset? I mean either not show the crown if highest wpm is always used or show the crown and calculate the pb progress using local pbs

**Comment by Miodec** [comment]
Yeah there is a check leftover when I was adding the whole pb system where if your result data was higher than your pb data it wouldn't be a pb. But then the server doesn't make that check (not anymore) so it still brings back the crown. The popup data is missing because it was only set based on the local pb.


Anyway i have added the code that edits the popup data to the code that receives the server response, so this shouldn't happen anymore. If it does please reopen the issue.
