### ISSUE TITLE
Click table headers to sort acount results

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#1602]
### Discussed in https://github.com/Miodec/monkeytype/discussions/1591

<div type='discussions-op-text'>

<sup>Originally posted by **BuddyBob** July  3, 2021</sup>
When you click your account and scroll all the way down it shows you all of your entries. 
<img width="1140" alt="Screen Shot 2021-07-03 at 9 08 11 AM" src="https://user-images.githubusercontent.com/66140321/124360465-d7856b80-dbde-11eb-8e14-6affcf076b88.png">
**| wpm | raw | accuracy | etc.**
I suggest a couple of buttons to sort this data. 

<li> by time
<li> by accuracy
<li> by wpm
<li> by consistency

</div>

**Comment by Geekz45679** [comment]
You should also be able to sort the table data by date. That would be pretty neat.

**Comment by tricarbonate** [comment]
I've managed to get the sorting by wpm work. I think I have a pretty good idea of how to sort by time, acc, consistency etc... Can I be assigned this issue?
