### ISSUE TITLE
Unable to disable key tips in command line

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1609]
**Describe the bug** 
When trying to disable key tips from the command line, I am unable to.

**To Reproduce** 

1. Open the command line `esc`
1. Search for `Key tips...`
1. Press `enter` or click on the result
1. Click `off` or search for `off` or press `enter`

**Expected behavior** 
Upon clicking or pressing enter, key tips would appear to be disabled. 

**Desktop:** 

- OS: [ChromeOS] 
- Browser [Chrome] 
- Browser Version [91.0.4472.147 (Official Build) (64-bit)] 

**Additional context** 
Note keytips are still actually enabled even when trying to disable from the command line and it's still possible to disable key tips from the settings page.

**Comment by Miodec** [comment]
Fixed in 98f7148ccb9d5e765eefeb5601ff11bde925e9cf

**Comment by UnrealApex** [comment]
Wow that was quick!
