### ISSUE TITLE
Export settings as JSON file

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1617]
### Proposed in https://github.com/Miodec/monkeytype/discussions/1610

<div type='discussions-op-text'>

<sup>Originally posted by **UnrealApex** July  9, 2021</sup>
It would be nice to be able to export your settings as a JSON file instead of a long JSON string. For example, once you attempt to export the settings, Monkeytype will ask you where to save the JSON file.
![Screenshot 2021-07-09 5 17 31 PM](https://user-images.githubusercontent.com/79121360/125146250-bab6cf80-e0d9-11eb-9918-d18d8b3ebcbe.png)
</div>

**Comment by Miodec** [comment]
Not really discussed. Not sure whats the advantage of having a file?

**Comment by UnrealApex** [comment]
Technically true, also yeah, should have actually discussed first. Thanks for the tip! 👍

**Comment by UnrealApex** [comment]
Actually, I thought of a use case, but it would require another feature. Being able to import the settings from JSON file would pair with this feature.

**Comment by Miodec** [comment]
I want to avoid file uploading as much as possible because I'm kinda afraid of people uploading malicious files.

**Comment by UnrealApex** [comment]
I do see the risks, but there should be easy ways to validate them.
