### ISSUE TITLE
ctrl+delete doesn't delete whole world

### ISSUE THREAD

**Issue by iamlambda** [Miodec/monkeytype#1624]
So I've been having this issue for months now, but I finally recorded it. I have no clue how to reproduce it since sometimes I get it, and sometimes I don't, but I'm pretty sure it only happens when I type the first letter wrong. Here's a video that shows the bug: [here](https://0x0.st/-Otk.mkv)
OS : arch linux
browser : firefox

**Comment by Miodec** [comment]
Do you mind uploading it here directly or to a video sharing site

**Comment by iamlambda** [comment]
i'm not gonna hack you Mio, I promise <3 (what a shame, github doesn't support mkv files)

https://user-images.githubusercontent.com/77165319/125457593-487d971d-8a85-46c8-b5e4-f7cc9193a160.mp4

**Comment by Miodec** [comment]
Hard to tell whats going on because of the theme. You also said that its not consistent? Did you test it on another OS or in another browser?

**Comment by iamlambda** [comment]
right, since I don't have the caret thing, it ain't very easy to tell. I'm pretty sure I got the same bug on qutebrowser (still on arch), I'll try to record with the caret next time I get the bug

**Comment by SaltatorMortis** [comment]
the vid looks like the word started with an SPACE and this will never get deleted with ctrl + backspace
maybe check if strict space is enabled

but while testing i found that underscore does not get deleted as it should as part of the word
and on a completed wort ctrl + backspace always deletes the whole word to the next space

**Comment by iamlambda** [comment]
damn, you may be totally right
