### ISSUE TITLE
pressing esc while website is loading breaks the command line

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1625]

**Comment by iamlambda** [comment]
pressing esc while a website is loading disable javascript, it's no bug ^^

**Comment by Miodec** [comment]
No no, its still broken after the website is loaded

**Comment by Estebene** [comment]
This is quite a weird bug (possibly haunted), I was trying to fix it, adding console logs, to see where it stopped working, then the command line started showing up while the website data was still loading. So I removed the console.log changes but this new state persists. I have to idea what I did. This change is also replicable across browsers as I tested on firefox and chrome. I don't know if this is the intended behavior and I don't know what I did.

**Comment by Miodec** [comment]
Nah, it was just an issue with the account related commands not loading in.
