### ISSUE TITLE
autoswitch between light and dark theme

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1629]

**Comment by Miodec** [comment]
User would need to specify one light and one dark theme. Then auto switch based on system setting.

**Comment by redarguireda** [comment]
I can work on this if you want, but I have a question: right now if I select a theme, and then chose light or dark, what's the difference? Like it doesn't seems to change anything

**Comment by redarguireda** [comment]
Btw I think that the user can choose a light theme, and then a dark theme, and based off what he/she chose the website set the theme. And in addition to that, a little switch on the top right/left whatever that lets the user to quickly switch between the two themes that he previously chose.

**Comment by Miodec** [comment]
Right now the website does not react at all to the system theme.

**Comment by sealvessel** [comment]
Could you also make this work for MacOS and Linux?

**Comment by JamesNarayanan** [comment]
In my personal projects, I use the following:
`window.matchMedia("(prefers-color-scheme: dark)").addListener(event => {
    setDarkMode(event.matches);
});`
Where setDarkMode is a redux action in react.
It works for mac, but I have not been able to test it for windows.
To manage theme state, I store a userTheme in localstorage. The user can change the userTheme manually using a toggle switch. If they change the device theme, it will update the userTheme to match. You can see a demo [here](https://roboguide.tk/). I apologize for the flash when loading the page, that occurs since I am using a useEffect() instead of a useLayoutEffect() in react ... just never got around to fixing it.
Hope this helps.

**Comment by redarguireda** [comment]
> Could you also make this work for MacOS and Linux? I think MacOS has a web identifier for system themes. Not sure for Linux though. This works on websites such as Youtube.

For now I'm checking for linux based systems, even doe i'm using the official api, we'll see, it should work for every system

**Comment by redarguireda** [comment]
> In my personal projects, I use the following:
> `window.matchMedia("(prefers-color-scheme: dark)").addListener(event => { setDarkMode(event.matches); });`
> Where setDarkMode is a redux action in react.
> It works for mac, but I have not been able to test it for windows.
> To manage theme state, I store a userTheme in localstorage. The user can change the userTheme manually using a toggle switch. If they change the device theme, it will update the userTheme to match. You can see a demo [here](https://roboguide.tk/). I apologize for the flash when loading the page, that occurs since I am using a useEffect() instead of a useLayoutEffect() in react ... just never got around to fixing it.
> Hope this helps.

oh yeah the classic one with a react state, used something similar for a old website that I made, thanks for the input!

**Comment by teddinotteddy** [comment]
> > In my personal projects, I use the following:
> > `window.matchMedia("(prefers-color-scheme: dark)").addListener(event => { setDarkMode(event.matches); });`
> > Where setDarkMode is a redux action in react.
> > It works for mac, but I have not been able to test it for windows.
> > To manage theme state, I store a userTheme in localstorage. The user can change the userTheme manually using a toggle switch. If they change the device theme, it will update the userTheme to match. You can see a demo [here](https://roboguide.tk/). I apologize for the flash when loading the page, that occurs since I am using a useEffect() instead of a useLayoutEffect() in react ... just never got around to fixing it.
> > Hope this helps.
> 
> oh yeah the classic one with a react state, used something similar for a old website that I made, thanks for the input!

I guess you would create a style and then that style would react to the system theme.

```
@media (prefers-color-scheme: dark) {
    html {
       color: white;
       background: linear-gradient(to right top,#480080, #AC32D9);
     }
  }
``` This is some code I used for an app that reacts to the theme color with pure css.

**Comment by sealvessel** [comment]
Any progress?

**Comment by teddinotteddy** [comment]
> Any progress?

#2088
