### ISSUE TITLE
Custom blurred background image has white edges

### ISSUE THREAD

**Issue by carceri** [Miodec/monkeytype#1630]
I think, it would be noice to add `transform: scale(1.1)` to custom blurred background image to get rid of white edges. 
  Without `transform: scale(1.1)`:
<img width="2160" alt="image" src="https://user-images.githubusercontent.com/40774542/125802077-382b10ff-a9c5-4a63-a741-c1815ebbb937.png">
With `transform: scale(1.1)`:
<img width="2160" alt="image" src="https://user-images.githubusercontent.com/40774542/125802177-d822caec-03ef-49e1-a44f-1cf725f9080c.png">

**Comment by Miodec** [comment]
Hm, i swear when we were implementing this the scale didn't get rid of the border - ill check again.

**Comment by Miodec** [comment]
![Uploading Screenshot 2021-07-15 at 15.31.05.png…]()


Yeah, doesnt work for me

**Comment by Miodec** [comment]
<img width="1670" alt="Screenshot 2021-07-15 at 15 31 05" src="https://user-images.githubusercontent.com/13181393/125805915-f5b61b4a-1693-49ad-b89b-5fca423646eb.png">

**Comment by carceri** [comment]
I see, must be not working in chrome, but I'm sure there should be a way to fix. I can play with it and let you know if I find something. If not, I will just close this issue.

**Comment by carceri** [comment]
This solution seems working. But it requires `img` html tag.
<img width="2160" alt="image" src="https://user-images.githubusercontent.com/40774542/125808353-5b46728a-598e-4a52-8ab3-46dc36de8698.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/40774542/125808867-60db0d4b-dacb-4b1c-b842-167baeafeb49.png">
Make a wrapper for image that will center image and put image inside and make it size as `calc(100% + blur saturation multiplied by twice)`. This will make white borders outside of view.

Hmm, this looks more difficult than just adding a transform scale to the style. And I'm afraid no one will make such a massive change because of this white border.
