### ISSUE TITLE
Weird box on the top left of the screen

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1633]
**Describe the bug** 
When using Monkeytype today, I noticed there was this small box at the top left of the screen. The margins also didn't appear normal

**Expected behavior** 
Margins would be 0 and box wouldn't be there.

**Screenshots** 
![Screenshot 2021-07-16 10 04 21 AM](https://user-images.githubusercontent.com/79121360/125984170-b903ed6e-7b4a-4aff-a636-da52fc869993.png)
![Screenshot 2021-07-16 10 08 44 AM](https://user-images.githubusercontent.com/79121360/125984202-8e1ef22a-d07c-4b88-9a34-6c8946f02345.png)

**Desktop:** 

- OS: [ChromeOS] 
- Browser [Chrome] 
- Browser Version [91.0.4472.147 (Official Build) (64-bit)] 

**Additional context** 
Box might be a checkbox, but upon clicking, no output. In the second screenshot, the wonky margins aren't visible with GitHub light mode on because they are white(use Default dark, Dark dimmed, or
Dark high contrast).

**Comment by Miodec** [comment]
Probably the custom background img

**Comment by UnrealApex** [comment]
I have no background image.
