### ISSUE TITLE
Grammar update

### ISSUE THREAD

**Issue by NexInfinite** [Miodec/monkeytype#1649]
I don't know about other languages but when typing the word `a` a word like `again` can come up. It'd be nice if there was a check for a word beginning with a vowel after a letter like `a`. You could either change `a` to `an` or just skip that word and pick a new random one (I haven't looked into how you generate words but I'm assuming its all rng).

**Comment by Miodec** [comment]
Please keep issues to bug reports only. For feature requests use discussions. 

As for proper grammar, you could use quote mode to type realistic text.
