### ISSUE TITLE
Changing the font family to Helvetica actually changes to Comic sans.

### ISSUE THREAD

**Issue by isaaceliapeFusioneer** [Miodec/monkeytype#1651]
**Describe the bug** 
When selecting the Helvetica font family the application is setting the font family to be Comic sans instead.

1. Go to 'Settings
2. Scroll down to the Font family section
4. Click on Helvetica
4. Check the font applied 

**Expected behaviour** 
The Font Family to be set as Helvetica.

**Screenshots**
<img width="1590" alt="screenshot" src="https://user-images.githubusercontent.com/42380784/126632567-8f505dae-98bf-4f85-9e8f-4f9641069e4c.png">

**Desktop:** 
- OS: MacOS Catalina 10.15.7
- Browser: Chrone
- Browser Version: 91.0.4472.114 (Official Build) (x86_64)

**Comment by Miodec** [comment]
Its a joke, not a bug.

**Comment by isaaceliapeFusioneer** [comment]
I thought might be that but I needed to check =]
