### ISSUE TITLE
Inaccurate burst for the last unfinished word

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#1660]
**Describe the bug** 
I love the burst heatmap, but I noticed the last unfinished work will always have a crazy high burst which affect the burst heatmap a lot as all other color are shifted due to this crazy high final burst.

Any chance we can fix that so the heatmap can be more accurate? Thanks.

**To Reproduce** 

1. Finish a test
2. Toggle burst heatmap
3. Check the last unfinished word
4. You'll see a crazy high burst that drag the entire heatmap with it

**Expected behavior** 
The burst for the last unfinished work should be tweaked to avoid making it an outlier.

**Screenshots** 
![Screen Shot 2021-07-23 at 12 26 34 pm](https://user-images.githubusercontent.com/17170199/126731126-c8714607-3537-47f5-96a7-cf660ed6b78c.png)

**Desktop:** 

- OS: [MacOS] 
- Browser [Chrome] 
- Browser Version [91.0.4472.164] 

**Additional context**

**Comment by Miodec** [comment]
This was just addressed in #1655. Last word will be colored, but does not affect the rest.
