### ISSUE TITLE
Right-shift keys don’t work in opposite Shift mode

### ISSUE THREAD

**Issue by vintagentleman** [Miodec/monkeytype#1676]
**Describe the bug**

Keys that require using the right Shift key for switching to uppercase have stopped working in opposite Shift mode.

**Did it happen in incognito mode?**

Both in incognito mode and when logged in.

**To Reproduce**

1. Go to _Settings_ → _Input_.
2. Enable opposite Shift mode.
3. Set up a quote typing test.
4. Try to press a key like A, C, or T.
5. Nothing happens.

**Expected behavior** The key gets typed in as usual.

**Screenshots**

![Peek 2021-07-25 11-54](https://user-images.githubusercontent.com/26284913/126893731-26a54d65-4f7a-4fff-ab74-855d19303039.gif)

**Desktop**

- OS: Ubuntu 20.04.2 LTS
- Browser: Google Chrome
- Browser Version: 92.0.4515.107

**Comment by Miodec** [comment]
Check that layout override is set to default in the settings. If doesn't fix it then I will assume its a Linux problem, which should be fixed in upcoming input rewrite.

**Comment by vintagentleman** [comment]
> Check that layout override is set to default in the settings.

Yes, it is set to default.

> If doesn't fix it then I will assume its a Linux problem, which should be fixed in upcoming input rewrite.

I’ll be waiting then, thanks!

**Comment by Miodec** [comment]
What `event.code` do you get here https://keycode.info/ when pressing left and right shifts?

**Comment by vintagentleman** [comment]
Hmm, I get `ShiftLeft` either way...

**Comment by Miodec** [comment]
Try Firefox?

**Comment by vintagentleman** [comment]
Yeah, it’s all fine in Firefox. Seems to the a Chrome issue then.

Thanks for the help!
