### ISSUE TITLE
Double input on Linux

### ISSUE THREAD

**Issue by Vrishabhsk** [Miodec/monkeytype#1679]
Whenever i start typing, after typing a few words, a few letters get re-typed without even pressing the key which did not happen in the first time i used monkeytype. So it affects the typing speed as well. Please fix this.

- OS: [Linux] 
- Browser [Brave] 
- Browser Version [1.27.108]

**Comment by Miodec** [comment]
Im pretty sure this is a Linux only issue because someone else on Linux is experiencing this.

**Comment by Miodec** [comment]
Could you test if it works here? 
https://seerlite.github.io/monkeytype/issue/531-input-rewrite/

**Comment by Vrishabhsk** [comment]
Yep it works now thanks a lot

**Comment by Miodec** [comment]
Closely related to #531 - closing this one. Will be fixed by #1325

**Comment by Miodec** [comment]
This is also a bug introduced by Chrome, there is a Chrome Bug open on this issue already.

**Comment by Vrishabhsk** [comment]
> This is also a bug introduced by Chrome, there is a Chrome Bug open on this issue already.

Yeah i noticed this happening on 10fastestfingers as well

**Comment by uqs** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1232428

Are you on Chrome 92 by any chance? Does it repro on Firefox?

**Comment by Vrishabhsk** [comment]
> https://bugs.chromium.org/p/chromium/issues/detail?id=1232428
> 
> Are you on Chrome 92 by any chance? Does it repro on Firefox?

Let me have a look

**Comment by Vrishabhsk** [comment]
> > https://bugs.chromium.org/p/chromium/issues/detail?id=1232428
> > 
> > Are you on Chrome 92 by any chance? Does it repro on Firefox?
> 
> Let me have a look

I used brave as of now

**Comment by Vrishabhsk** [comment]
@uqs works fine on firefox only brave and chrome have this problem

**Comment by Tutorgaming** [comment]
I'm having the same issue - random doubling input
OS: Ubuntu 18.04 
Browser: Chrome 92.0.4515.107 (Official Build) (64-bit)
