### ISSUE TITLE
low wpm for no reason

### ISSUE THREAD

**Issue by MeirKlemp** [Miodec/monkeytype#1688]
**Describe the bug** 
Sometimes, after a test, the wpm is very low for no reason.<br>
It happened to me twice in 457 tests of 60 seconds, punctuations, and numbers that I took. In both times, the wpm was in the 20s, the raw wpm was near my average at the time, the accuracy was above 85%, but the incorrect characters were above 100.<br>
On the last test it happened, I practiced the wrong words and I saw a lot of words that I have done a typo and fixed appear, a lot. I think it counts all the times I did a typo as a wrong character even though I fixed it.

**To Reproduce** 

1. Set a test of 60 seconds, punctuations, and numbers (probably could happen on other types of test)
2. Play a lot of tests until one test with a low wpm and a high number of incorrect characters appear for no reason.

**Expected behavior** 
More reasonable wpm, and 0 incorrect characters as I usually fix them.

**Screenshots** 
![image](https://user-images.githubusercontent.com/50945641/127381074-1373598f-3154-4973-82ce-b8fca9acd7a7.png)
![image](https://user-images.githubusercontent.com/50945641/127381210-a589018b-dfbe-4de7-9401-bc9044fbd59b.png)
![image](https://user-images.githubusercontent.com/50945641/127381314-1a650bf8-7a6d-4ef5-9f24-35ba571c3a8f.png)

**Desktop:** 

- OS: Windows 10
- Browser: Firefox
- Browser Version: 90

**Comment by Miodec** [comment]
I need someone to record whats going on during the test because I've got no idea whats happening here.

**Comment by Miodec** [comment]
Can you paste in your config JSON? Did you use ctrl+backspace?

**Comment by MeirKlemp** [comment]
I don't use ctrl+backspace.

{"theme":"bento","customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":true,"numbers":true,"words":50,"time":60,"mode":"time","quoteLength":[0],"language":"english","fontSize":15,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"capsLockBackspace":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"showLiveBurst":false}

**Comment by Miodec** [comment]
I found it and fixed it

**Comment by MeirKlemp** [comment]
Hi, I got the bug again.
This time I recorded it:
https://user-images.githubusercontent.com/50945641/128416265-0d982fe7-2fee-47f1-8cd5-1ceff067dd14.mp4

**Comment by Miodec** [comment]
I think i would need a recording of this during typing, not after. Hard to guess whats going on just based on the result. Did you use ctrl+backspace around the `565 a she but` words?

**Comment by MeirKlemp** [comment]
I did use ctrl+backspace around the ```565 a she but``` words.
The bug is rare, so I don't know how I will be able to record it...
Maybe you can add a debug feature that extracts all the information about the run that could help to debug?
