### ISSUE TITLE
On window resize, leaderboard gets wonky (Phone/small tablet)

### ISSUE THREAD

**Issue by BuddyBob** [Miodec/monkeytype#1696]
I came to this website to get some inspiration on a leaderboard (beautiful leaderboard btw) and how your guys formatted it. One thing that was very important to me was how the leaderboard changed when scaled down to a phone or small tablet size. 

Sadly I was disappointed to see that the leaderboard did not scale down properly. The following images should tell the story.
<img width="490" alt="Screen Shot 2021-07-30 at 8 14 38 AM" src="https://user-images.githubusercontent.com/66140321/127675912-d35a4432-9d2f-4901-a9f0-e95bde22cd13.png">
<img width="586" alt="Screen Shot 2021-07-30 at 8 15 20 AM" src="https://user-images.githubusercontent.com/66140321/127675916-70c76741-a7dc-41e6-bc00-1edcc05a3a5b.png">

- OS: [ MacOs ]
- Browser [ Chrome ] 
- Browser Version [ 92.0.4515.107 ]

**Comment by Miodec** [comment]
Fixed by #1698
