### ISSUE TITLE
Position of nav menu should be sticky

### ISSUE THREAD

**Issue by rockingrohit9639** [Miodec/monkeytype#1699]
When we go on a large page where we have to scroll the window the nav menu is scrolled up with it too. And to change the page we need to scroll up. It would be better if the menu is already positioned fixed.

### nav-menu
![image](https://user-images.githubusercontent.com/40729749/127848988-9cc42ec7-57ff-456e-bd86-9bd993b2fabc.png)

**Comment by Miodec** [comment]
For suggestions please use discussions instead of creating an issue.

As for the sticky suggestion, it would require a lot skeleton changes to allow for a sticky nav. I don't think its worth the effort. There is also a scroll to top button available in the bottom right.
