### ISSUE TITLE
Apostrophe recognized as error when using the US international keyboard

### ISSUE THREAD

**Issue by Xiquee** [Miodec/monkeytype#1701]
**Describe the bug** 

When using the US English international keyboard, the Apostrophe ' sign is recognized as an error. 

(The international US keyboard does not input the apostrothe upon typing it, it waits until the next key is pressed. If the next input is space or a key with which no special character is associated, it will input the apostrophe plus the second input. Othewise it inputs the special character. Example: ['] + [Space] produces ['], while ['] + [c] produces [ç], and ['] + [s] produces ['s])

It did not happen in incognito mode.

**To Reproduce**

1. Choose the US international keyboard in Windows
2. Go to a quote that has apostrophes
3. Type the quote using the international US keyboard

**Expected behavior** 

No error expected when the input is correct.

**Screenshots**

[
![monkeytype1](https://user-images.githubusercontent.com/36740696/127912836-d3c1dfd1-bd39-4a67-905b-c9992cb4f9e3.png)
![monkeytype2](https://user-images.githubusercontent.com/36740696/127912856-b767df28-5af5-45d2-b114-8ea9961f5491.png)
](url)

**Desktop:** 

- OS: [Windows 10]
- Browser [Firefox] 
- Browser Version [90.0.2]

**Additional context**

**Comment by Miodec** [comment]
Works for me on a mac. Could be fixed by #1325. Can you check if it works here? https://seerlite.github.io/monkeytype/issue/531-input-rewrite/

**Comment by Xiquee** [comment]
Yes, it works there!
![monkeytype3](https://user-images.githubusercontent.com/36740696/128069376-46c92e23-6492-49a3-81bd-dec956dda108.png)

**Comment by Miodec** [comment]
Related to #531 then. It will be fixed by #1325
