### ISSUE TITLE
Remove words with spaces from the spanish word list

### ISSUE THREAD

**Issue by jamartinezc** [Miodec/monkeytype#1702]
Hi, first of all, thanks for this great learning tool!

I noted that when typing in Spanish there are some words that appear to be "separated" by an empty character, so it is impossible to write them correctly, when looking into the language json file, it seems that some entries have multiple words separated by spaces, my guess is that this is what is causing the problem.

These are the entries:
https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L48

https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L81

https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L85

https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L94

https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L131

https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L141

https://github.com/Miodec/monkeytype/blob/c1d65ba9769e49d19baafedcb9eef2eecaafc67b/static/languages/spanish.json#L142

This is how it looks like (notice that the "word" atravésde should be 3 words "a través de"):
![image](https://user-images.githubusercontent.com/3467593/127947130-ace8acb8-ea0c-4ff0-a07f-c7ff2582de53.png)

thanks

**Comment by Miodec** [comment]
Yeah, words with spaces will not show up correctly - spaces should not be used in the languages lists.
