### ISSUE TITLE
PB line is gone in the result chart

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#1712]
**Describe the bug** 
PB line is gone in the result chart

**To Reproduce** 

1. Finish a test
2. Check the chart in the result screen
3. No dotted PB line in the chart anymore

**Expected behavior** 
PB line is great, please don't remove it.

**Comment by Miodec** [comment]
Screenshot? I didn't touch the pb line

**Comment by pingshunhuangalex** [comment]
In latest Chrome and Win10

![image](https://user-images.githubusercontent.com/17170199/128619544-b757e7e0-2959-4689-9291-b1343ba0cc20.png)

**Comment by Miodec** [comment]
And whats your pb for time 60?

**Comment by pingshunhuangalex** [comment]
`89.59`

**Comment by Miodec** [comment]
Are you signed in? Is the pb line always missing? Did you refresh?

**Comment by pingshunhuangalex** [comment]
yes, yes and yes
