### ISSUE TITLE
Opposite shift mode working inconsistently

### ISSUE THREAD

**Issue by RaniAgus** [Miodec/monkeytype#1717]
I noticed that sometimes I type a capital letter or exclamation mark and the input doesn't reflect in the typing session. I don't have any issue with my keyboard: in normal use, every letter gets caught properly.

I tried disabling caché and didn't work but in incognito mode it did, so I decided to deactivate "opposite shift" mode and now it works as expected (that's why I think the problem might be there). It's a strange issue because after typing the same letter several times (around 15-20 times) it finally gets caught 🤔 

**Desktop:** 

- OS: Linux Mint 20.1 x86_64 
- Browser: Google Chrome 
- Browser Version:  

**Additional context** 

I had enabled punctuation, numbers, words and 50 when the issue appeared (this is the mode I usually use for practice, didn't try any other)

**Comment by RaniAgus** [comment]
More context: I'm using US QWERTY layout

**Comment by Miodec** [comment]
Any chance you could record what is happening?

**Comment by RaniAgus** [comment]
Sure!

https://user-images.githubusercontent.com/39303639/130357166-2cd6a1c6-3aa7-43c5-91f1-86973e345321.mp4

**Comment by Miodec** [comment]
Im assuming that you tried to use the right shift for the a. Is it that the shift 'state' gets frozen? Or is it that you can only shift letters from one side on the keyboard?

**Comment by RaniAgus** [comment]
Nono, it doesn't get frozen, if I unpress right shift and press any lowercase letter it works as usual.

**Comment by sphhax** [comment]
@RaniAgus you are using shifts correctly though right? So if you want to capitalize the A you have to use the right shift, the left shift won't work in opposite shift mode.

I just want to make sure because the behavior you describe sounds like the correct behavior when the wrong shift key is being used.

**Comment by RaniAgus** [comment]
> @RaniAgus you are using shifts correctly though right? So if you want to capitalize the A you have to use the right shift, the left shift won't work in opposite shift mode.

Yes, I'm using shifts correctly and it behaves like I'm always using the wrong shift.

**Comment by sphhax** [comment]
My next thought would be to verify that your shift keys are bound correctly, try a keyboard tester that can distinguish the difference between the left shift and right shift and make sure that is working right.

If so, then that's all I really have in terms of information for this issue as I was unable to reproduce it as well.

**Comment by Miodec** [comment]
Can you check on https://keycode.info/ if you get `ShiftLeft` and `ShiftRight` when you press different shift keys?

**Comment by RaniAgus** [comment]
Sorry! Somehow in my Linux Mint installation both keys are `ShiftLeft`, thank you for your patience!
