### ISSUE TITLE
Ellipsis in quote can not be typed

### ISSUE THREAD

**Issue by Codelefant** [Miodec/monkeytype#1718]
**Describe the bug** 
[Ellipses](https://en.wikipedia.org/wiki/Ellipsis) are part of some medium german quotes, but there is no straight forward way to type them. The complicated way (Alt+0133 on Numpad) is not recognized by monkeytype, but works in the address bar for example. I expected to be able to write three points instead of the special ellipsis symbol, but that didn't work.

**To Reproduce** 

When prompted to write an ellipsis (e.g. in a german medium quote)
1. Try to type "..." (three points)
2. Notice that with the first typed point, the ellipsis is highlighted red.

**Expected behavior** 
I either expected to be able to type three points, which will be combined to the ellipsis (as Microsoft Word does it), or not to encounter this special symbol at all.

**Screenshots** 
![grafik](https://user-images.githubusercontent.com/11066012/128927852-b7145f0b-6369-47d5-a199-74e86ef078a6.png)
![grafik](https://user-images.githubusercontent.com/11066012/128929855-87833ac6-b6f1-4284-a64e-0d50cf3ae043.png)

**Desktop:** 

- OS: Windows 10
- Browser: Firefox
- Browser Version: 90.0.2

**Additional context** 
In a case where the ellipsis is at the end of the quote (first screenshot), it cannot be completed.

**Comment by Miodec** [comment]
Fixed in fd1d5d5ce5b92ebbf626886753e22b61ddbe29ec
