### ISSUE TITLE
Custom mode delimiter switch

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#1728]
Current custom mode breaks up everything on space. This means that if the user wants some words to always appear together ( like, I don't know, "big house" ) the space will make it impossible, and randomise those words separately. 

Adding a switch on the custom text popup, that toggles between a space delimiter and a pipe delimiter would allow users to randomise phrases (for example `big house|test|increase|other`). With this, the phrase `big house` will never be generated on their own.

Adding support for this could also allow phrases to be used in language files, for languages that have phrases where having the words be separate would not make much grammatical sense.

**Comment by historybandgeek** [comment]
For more context, this is especially useful for those learning stenography, but also applies to those wanting to expand from seeing a whole word and typing/thinking the word instead of the individual characters to seeing phrases. For the stenographer, one can write much faster when one "chord" of input is mapped to a whole phrase. ("ladies and gentlemen of the jury"/"and I said"/"before you went" - there are thousands of great opportunities for phrasing) 

Additionally, to further this, it may be useful to have some way of showing the phrase as a phrase in a test or practice session - highlighted/underlined subtly would aid the learner in seeing "is it the" instead of "is", "it", "the" etc. 

Stenographers and typists alike are very grateful for this awesome tool!

**Comment by pran01** [comment]
Can I try this?

**Comment by Miodec** [comment]
Go for it @pran01

**Comment by pran01** [comment]
I am trying to run it locally for the first time. Followed everything step by step given in https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md
Had some problems in mongodb first but even after solving that, an error is there and i can't run it. Can some one explain the error to me?
Log:

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/pranav/.nvm/versions/node/v14.17.5/bin/node',
1 verbose cli   '/home/pranav/.nvm/versions/node/v14.17.5/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:dev'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'prestart:dev', 'start:dev', 'poststart:dev' ]
5 info lifecycle monkeytype@1.5.6~prestart:dev: monkeytype@1.5.6
6 info lifecycle monkeytype@1.5.6~start:dev: monkeytype@1.5.6
7 verbose lifecycle monkeytype@1.5.6~start:dev: unsafe-perm in lifecycle true
8 verbose lifecycle monkeytype@1.5.6~start:dev: PATH: /home/pranav/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/pranav/Storage/Root/Personal/Projects/Development/monkeytype/node_modules/.bin:/home/pranav/.local/bin:/home/pranav/.nvm/versions/node/v14.17.5/bin:/home/pranav/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle monkeytype@1.5.6~start:dev: CWD: /media/pranav/Storage/Root/Personal/Projects/Development/monkeytype
10 silly lifecycle monkeytype@1.5.6~start:dev: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run build && concurrently --kill-others "npx gulp watch" "nodemon ./backend/server.js" "firebase serve"'
10 silly lifecycle ]
11 silly lifecycle monkeytype@1.5.6~start:dev: Returned: code: 1  signal: null
12 info lifecycle monkeytype@1.5.6~start:dev: Failed to exec start:dev script
13 verbose stack Error: monkeytype@1.5.6 start:dev: `npm run build && concurrently --kill-others "npx gulp watch" "nodemon ./backend/server.js" "firebase serve"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/pranav/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/home/pranav/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid monkeytype@1.5.6
15 verbose cwd /media/pranav/Storage/Root/Personal/Projects/Development/monkeytype
16 verbose Linux 5.11.0-27-generic
17 verbose argv "/home/pranav/.nvm/versions/node/v14.17.5/bin/node" "/home/pranav/.nvm/versions/node/v14.17.5/bin/npm" "run" "start:dev"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error monkeytype@1.5.6 start:dev: `npm run build && concurrently --kill-others "npx gulp watch" "nodemon ./backend/server.js" "firebase serve"`
22 error Exit status 1
23 error Failed at the monkeytype@1.5.6 start:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
