### ISSUE TITLE
Applied theme is not always selected theme.

### ISSUE THREAD

**Issue by kndshein** [Miodec/monkeytype#1737]
**Describe the bug** 
Randomly (usually after the 3rd change), the selected theme is not the applied theme.

No.

**To Reproduce** 

1. Go to `https://monkeytype.com/` default page on desktop.
2. Click on `custom theme toggle` at the bottom right of the site.
3. Select a theme.
4. Select another theme.
5. Keep selecting another theme until you see that the applied theme isn't the selected theme.

**Expected behavior** 
Expects the selected theme to be the applied theme.

**Screenshots** 
https://imgur.com/a/5pmMJzA
If you look at the first image, `stealth` is applied, yet if you look at the second image, the selected theme is `strawberry`.
Ignore `wavez`, I had to reopen the theme selector to show the selected theme.

**Desktop:** 

- OS: [Windows 10 Home] 
- Browser [Firefox] 
- Browser Version [91.0 (64 bit)] 

**Additional context**

**Comment by Miodec** [comment]
Do you have any favorite themes? Can you un-favorite all themes and check if this happens? I just uploaded a little fix for favorite themes in the command line, maybe its somehow related.

**Comment by kndshein** [comment]
I do not have any. I didn't even know it was an option -- just double checked.

**Comment by Miodec** [comment]
So its still happening

**Comment by kndshein** [comment]
Yes, just tested again.

**Comment by Miodec** [comment]
Is it all good now?

**Comment by kndshein** [comment]
Nope, it's still happening. But, it's not that big of a deal though because the bug only occurs when I click on the themes quickly (which I was doing when I was going through all the themes).

**Comment by Miodec** [comment]
Im just gonna close it then. I don't think people will spam the theme buttons often.

**Comment by kndshein** [comment]
I figure as well. Thanks for humoring me!
