### ISSUE TITLE
Cannot specify layouts whose names have spaces in them in custom layoutfluid

### ISSUE THREAD

**Issue by molohov** [Miodec/monkeytype#1744]
**Describe the bug** 
Layouts like "colemak dh" are defined in Monkeytype's layout list with a space. If one tries to use this layout in the custom layoutfluid list, which assumes a space separated list of layouts, this will not work.

**To Reproduce** 

1. Go to Settings
2. Scroll down to "custom layoutfluid"
3. Enter `colemak dh` into the text box (I've also tried `"colemak dh"`)
4. See error "One of the layouts was not found. Make sure the name matches exactly. Reverting to default."

**Expected behavior** 
I expected that all layouts that are in the list of "layout override" and "keymap layout" would work with layoutfluid.

**Screenshots** 

**Desktop:** 

- OS: [Windows 10] 
- Browser [Vivaldi] 
- Browser Version [4.1.2369.16] 

**Additional context**

**Comment by Miodec** [comment]
Currently, you need to replace the spaces with  underscores `_`. I want to replace the text field with a popup with dropdown menus in the future.
