### ISSUE TITLE
English 5k containing German word `verzeichnis`

### ISSUE THREAD

**Issue by luehmann** [Miodec/monkeytype#1785]
https://github.com/Miodec/monkeytype/blob/master/static/languages/english_5k.json#L3154

**Comment by FukurouMakoto** [comment]
I can take care of this if given the go-ahead

**Comment by luehmann** [comment]
@FukurouMakoto thanks, but we need a replacement, right? it's called 5k after all

**Comment by FukurouMakoto** [comment]
Ah, correct, totally missed that. 
I can substitute some of the following if any of these work:
zealousness
zigzagged
zillionaire
zoologists

**Comment by CrumblyLiquid** [comment]
I don't think this really matters. Lot of language files have less words than the specified amount. I mean in a 5k word file one word is 0.02% difference.

**Comment by FukurouMakoto** [comment]
True. I'll add one just to be safe. 
Changes made:
- Removed "verzeichnis" from english_5k.json file and added it to german_10k.json file.
- Replaced it with "Zealousness".
