### ISSUE TITLE
Add "on" text. Settings -> behavior -> blind mode

### ISSUE THREAD

**Issue by salemalem** [Miodec/monkeytype#1795]
![image](https://user-images.githubusercontent.com/42411937/131501119-61b96a89-a873-4e43-9317-2c30a64ba2d5.png)

**Comment by TheeKevin** [comment]
@Miodec you've oughta put a textbox there that literally says "this is a joke don't worry"

but anyway @salemalem this is just a joke. There's not meant to be "on" there because the joke is that it's "blind" don't worry I thought the same as well when I started Monkeytype

**Comment by Miodec** [comment]
Not a bug, button is blind.
