### ISSUE TITLE
Command line doesn't update after deleting ">" symbol

### ISSUE THREAD

**Issue by coolcart** [Miodec/monkeytype#1844]
**To Reproduce**: 

1. Go to command line
2. Type ">" with some value after it
3. Delete ">" without deleting the following text
4. See that results continue acting as if the ">" wasn't removed

**Expected behavior**: the results should respond to deletion of the ">" symbol

**Screenshots**:
![12345](https://user-images.githubusercontent.com/83957950/133040584-206d75bc-8361-4044-a26b-b31347653312.gif)
**Desktop:** 

- OS: [Linux] 
- Browser [Chrome] 
- Browser Version [Version 93.0.4577.63 (Official Build) (64-bit)]

**Comment by coolcart** [comment]
The bug is still there

**To reproduce:**
1. Type > with some option
2. Delete the option you typed, but keep >
3. The results will be shown as if there is no > at the beginning

![12345](https://user-images.githubusercontent.com/83957950/133267048-3af0314d-0631-4fcc-9057-6abf01c0926d.gif)

**Comment by Miodec** [comment]
Just deployed a new version. Clear your cache and test again. Should be all good.

**Comment by coolcart** [comment]
now the bug has reverted to what it was previously when removing ">" with delete button
and removing ">" with backspace just clears the input field

**Comment by Miodec** [comment]
Clearing the input field is the best way around the issue I think. Because it changes the way commands are filtered and shown. I think most people wont run into this anyway.

**Comment by coolcart** [comment]
ok, though i don't like the idea of retyping the whole word instead of just one character

**Comment by Miodec** [comment]
You can avoid having to type the > symbol if you enable single list command line

**Comment by coolcart** [comment]
i think you haven't yet fixed the issue with using delete button, your fix currently only applies to backspace key

**Comment by Miodec** [comment]
I think i fixed the delete issue and managed to make it not clear on delete.

**Comment by coolcart** [comment]
it works, ty!
