### ISSUE TITLE
Close button for notification popups appear in the middle of the popup.

### ISSUE THREAD

**Issue by Maryll-castelino** [Miodec/monkeytype#1868]
**Describe the bug** 
When a notification popup shows up on the website for any reason (eg: test too short!) and when the mouse is hovered over the notificatoin popup then the button to close the popup shows up in the middle of the popup blocking the content. It also happens in incognito mode.

**To Reproduce** 

1. Go to 'monkeytype.com'
2. Change the word/time value to something low which will show an error of 'test too short!'
3. complete the test and see the notificatoin popup
4. hover mouse over the notification popup

**Expected behavior** 
The close button should be to the right of the content of the notification popup

**Screenshots** 
![close notification button is in the middle](https://imgur.com/THPzKKb.png)

**Desktop:** 

- OS: [Linux]  
- Browser [Brave browser]  
- Browser Version [1.25.68-1]  

**Additional context** 
This happens for any kind of notification not just the one i have described

**Comment by Miodec** [comment]
Intended. Indicates you can click anywhere on the notification to close.
