### ISSUE TITLE
Constantly logs me out within hours.

### ISSUE THREAD

**Issue by starmadegeek** [Miodec/monkeytype#1885]
**Description of the problem** 
When I log in, I expect it to stay logged in unless I logout manually or cleared chaches or cookies in my browser or the session token expires. But MonkeyType website logs me out within hours if not minutes. I constantly loose many productive sessions without being recorded and tracked. I later discover that I was not logged in and nothing got recorded. This is quite disappointing tbh.
My preffered login method is email and password. I also keep the '_Remember me_' toggle turned on all the time.
I see that MonkeyType uses Google firebase for login authentication. But Firebase authentication does not have this problem of logging out frequently. This has to be a problem with MonkeyType session management. Or it could be my problem which is somehow causing clearing of session cookies. I don't know. I'm hoping someone could point me to a solution if thats the case.

**Expected behavior:** 
Expected behaviour is to stay logged in for longer durations and update the user if logged out of session expiry and lead user to logging again.

- OS:  Windows 10
- Browser: Google Chrome
- Browser Version: 93.0.4577.82

**Comment by Miodec** [comment]
Check your privacy settings, privacy extension - I'm not getting any other reports of this so it has to be your browser or extension clearing cookies.

oooooor it could be that you didn't press `Remember me` ;)

**Comment by starmadegeek** [comment]
Ok. I'll try logging in different browser and device and see if this persists and let you know. But I always toggle on the 'Remember me' button. That is not the issue. 
Thanks for responding.

**Comment by Miodec** [comment]
Any update?

**Comment by starmadegeek** [comment]
I tried loging in different browser (Tried on Edge and Firefox). It absolutely works fine. There's no issue with the website. I'm still yet to find out what's causing this on my chrome browser. I think some extension is messing it up or Chrome's new 'Enhanced Protection' feature. But you said no one else is reporting this issue. So I reckon it is my problem now. Thanks! I'm closing this.
