### ISSUE TITLE
Unable to use actual layout of OS

### ISSUE THREAD

**Issue by alfonz19** [Miodec/monkeytype#1902]
App allows to switch to CZ language. However if I use my own layout or official layout, symbols I'm supposed to type (č,ž, í …) are not typable, because I think the app reads scancodes or smth like that, not actual symbols typed.

I understand that this is primarily ENG app, but if it offers different languages, there should be way how to use it. Simple solution could be to turn off interpreting scancodes (or smth like that) and actually using what OS think it was typed.

**Comment by Miodec** [comment]
What system are you on. Are you sure your layout is set to `default` in the settings?

**Comment by alfonz19** [comment]
google-chrome on fedora 33. Checked more browser, firefox behave correctly, brave also, surprisingy. No idea what's wrong. I tried to disable all plugins, still the same.

I see default on, yes. These are exported settings:

`{"theme":"serika_dark","customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":30,"mode":"quote","quoteLength":[1],"language":"czech","fontSize":15,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"capsLockBackspace":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showLiveBurst":false}`

**Comment by SeerLite** [comment]
Hi, does it work correctly on the preview page of #1325? You can test it [here](https://seerlite.github.io/monkeytype/issue/531-input-rewrite/)

**Comment by alfonz19** [comment]
Yes, it does work in google-chrome in this rewrite. But it's weird, that there issue exist (for me) only for chrome. I did the same test for you also in firefox and brave, and it work there as well. Seems (from this very quick glance) that rewrite fixes the issue whatever it is. Thanks!

**Comment by Katamave** [comment]
same issue  with german. Rewrite works. Im on Arch.

**Comment by Miodec** [comment]
The inupt rewrite is live now on the main site. Give it a quick test and let me know.

**Comment by alfonz19** [comment]
seems to be working for CZ, thanks!
