### ISSUE TITLE
Page not centered

### ISSUE THREAD

**Issue by 4shutosh** [Miodec/monkeytype#1905]
![Screenshot from 2021-09-26 11-53-13](https://user-images.githubusercontent.com/53831987/134796147-1a53dfe8-a227-42eb-9530-0ff4dfdef605.png)
![Screenshot from 2021-09-26 11-57-57](https://user-images.githubusercontent.com/53831987/134796275-018e602b-70ea-4671-bd07-25a0aa532cd1.png)

**Describe the bug** 
I feel the page is not centered properly. (It's more towards the right) This can be verified when the page is zoomed in like 150%+, there is more padding to left than right.

**Expected behavior** 
The page should be centered properly

- OS: []  Linux
- Browser []  Chrome
- Browser Version []  Version 92.0.4515.159 (Official Build) (64-bit)

**Additional context** 
I might be wrong, but the anxiety that it gives is killing me all the time. Please verify

**Comment by Miodec** [comment]
Can you test other browsers? Could also be a linux issue because it doesnt happen for me on windows or mac

**Comment by Miodec** [comment]
Also try increasing the page width in the settings.

**Comment by 4shutosh** [comment]
I tried other browsers. It worked perfectly fine in Brave.

What could be the issue with Chrome?

**Comment by Miodec** [comment]
Maybe you increased your chromes font size? I feel like the footer is quite condensed on your screen, could be causing the overflow. Normally the footer switches layouts before the overflow can happen. Have you tried increasing the page width in monkeytype settings?

**Comment by 4shutosh** [comment]
Yes, I've increased the font size for my chrome.
Increasing the page width from the monkeytype settings, fixed the issue.

Thank you so much 🎉
Have a great week ahead.
