### ISSUE TITLE
Sellout Video Ads Blocking Parts of Result Page UI

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#1911]
**Describe the bug** 
Video ads in sellout mode block parts of the Monkeytype UI. Parts of the result UI in specific.

**To Reproduce** 

1. Open command palette
2. Type `Enable ads...`
3. Select `sellout`
4. Finish a test
5. Wait for a video ad...

**Expected behavior** 
Video ads would maybe appear at the bottom of the screen(with margin).

**Screenshots** 
![Screenshot 2021-09-28 7 48 13 PM](https://user-images.githubusercontent.com/79121360/135194718-156e80c3-561f-42bc-afcc-6fbb3af750bf.png)
As you can see, the ad covers part of the results page(note that the screenshot button is covered).
**Desktop:** 

- OS: [ChromeOS] 
- Browser [Chrome] 
- Browser Version [93.0.4577.85 (Official Build) (64-bit)] 

**Additional context** 
This might not be a problem for larger viewports. @Miodec, @SeerLite  how does it look for you? Is there sufficient margin for the ads?

**Comment by Miodec** [comment]
This will probably only be a problem on smaller displays

**Comment by Miodec** [comment]
Yeah, it works fine for me. Smaller viewports hide the side banners anyway, so the solution here is just to disable sellout mode.
