### ISSUE TITLE
iOS and iPadOS unbuffering text typed during the result screen into the next test

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#1921]

**Comment by peppy** [comment]
Video showing this happening (iPadOS 15 / external keyboard):

https://user-images.githubusercontent.com/191335/135499841-aa7d85a0-ecdc-430c-9743-a62bb03e9a1e.MP4

- Mashing keyboard at results/fail screen
- Hit tab to restart test (with quick restart turned on)
- Next keypress will unbuffer all mashing from results screen

**Comment by SeerLite** [comment]
Hi Peppy! Can you confirm that it's fixed over [here](https://seerlite.github.io/monkeytype/issue/1921-omg-hi-peppy/)? Thank you

**Comment by peppy** [comment]
> Hi Peppy! Can you confirm that it's fixed over [here](https://seerlite.github.io/monkeytype/issue/1921-omg-hi-peppy/)? Thank you

It indeed does look resolved!

**Comment by Miodec** [comment]
Issue now is that you can't tab over to the next test button on the result screen, and the words are not refocused on the next test @peppy

**Comment by peppy** [comment]
I did very limited testing with "quick tab" on, so probably would not have run into that. With that disabled I can repro the issues you mention, which does seem a bit broken.

**Comment by Miodec** [comment]
Confirmed fixed
