### ISSUE TITLE
Funbox settings invalidate pb

### ISSUE THREAD

**Issue by Azirine** [Miodec/monkeytype#1949]
**Describe the bug** 

Getting a pb with funbox setting 'read ahead easy' doesn't register as a pb.

**To Reproduce** 

1. Go to 'settings'
2. Click on 'read ahead easy'
3. Get a pb on English Time 15
4. The run is recorded but there is no crown and the personal best list doesn't update to include the new run

**Expected behavior** 

A crown to be awarded for the run and the personal best list to update to include the new record.

**Screenshots** 

<img width="971" alt="run" src="https://user-images.githubusercontent.com/30378821/135994264-69112732-7ebf-4418-8e18-18dccf39d658.png">
<img width="476" alt="pb" src="https://user-images.githubusercontent.com/30378821/135994291-059116be-9fd7-461a-9bdf-8316f72f2638.png">

**Desktop:** 

- OS: [MacOS] 
- Browser [Firefox] 
- Browser Version [92.0.1] 

**Additional context**

**Comment by Miodec** [comment]
Personal bests for funboxes are disabled by default because some of them modify the word generation, make the test easier or harder.

**Comment by Azirine** [comment]
'Read ahead' does not modify the word generation, so personal bests should not be disabled for them.
