### ISSUE TITLE
Only one single line of text visible of the first test when opening site

### ISSUE THREAD

**Issue by bilfri** [Miodec/monkeytype#1959]
DISCLAIMER: this bug is very elusive to me, but I have encountered it a couple of times over a longer period (maybe 2 months). I thought it was a good idea to put the issue here, so that I or others have a place to add information when it occurs again. If that is not how you work, feel free to delete the issue

**Description**
When I open monkeytype.com without any cookies or being logged on, the first test that is presented only shows a single line of text, instead of the usual three lines. I can type the line as usual, but when I complete the line, the test doesn't finish (indicating that there is more text, but I just can't see it, I guess). This only happens with the first test after opening the site, the next one always works fine.

**Did it happen in incognito mode?**
Not explicitly incognito mode, but my cookie and history settings are pretty much the same as incognito mode

**To Reproduce**
I have had it happen maybe 10 times, but can't reliably reproduce it. Here's my best bet so far:
1. Start computer
2. Open browser
3. Open some other website
4. Open monkeytype.com
5. Notice how there is only one line of text in the first test instead of the expected three.

**Desktop:** 
- OS: Fedora 34
- Browser: Firefox
- Browser Version: 92.0.1

**Comment by bilfri** [comment]
It had just happened again when I wrote the issue yesterday - and happens pretty rarely, maybe one in 20 times I open the site or so.

**Comment by staticssleever668** [comment]
This just happened to me. Zooming in/out didn't help. It has gone away after refreshing the page.
The only variable I see here is the random sentence, here it is in case it matters: `course also more write one not course also turn last leave group`.

**Comment by Miodec** [comment]
The words won't affect this issue. The bug has to be in here, I don't see any other possibility.... Still dont understand why it's so inconsistent though..

https://github.com/Miodec/monkeytype/blob/5aa781fdfc411ad7008c4c1c1b35dbf8ec2704e2/src/js/test/test-ui.js#L142-L148

**Comment by Miodec** [comment]
@bilfri Can you confirm in which test modes is this happening? Time or any other mode? Is your `showAllLines` setting enabled or disabled?

**Comment by bilfri** [comment]
It has only happened to me when I first open the website, not logged in, no cookies, all settings default. Also it hasn't happened to me since I filed the bug report (maybe the defaults changed?). I dunno, maybe just let it sit for now, I have the feeling its something very specific to my and @staticssleever668's systems (browser, plugins, os, vpn, whatever). Hope your therapy is coming along well :)

cc: @staticssleever668 has it happened to you again since you wrote last time? what browser are you using?

**Comment by staticssleever668** [comment]
This happened to me on Tor Browser, which is basically a Firefox instance with different default settings and integrated proxy. This problem hasn't happen to me since then, I even tried continuously restarting the test for a while right now, still hasn't appeared, but I didn't use monkeytype much other than right now in this period of time. It should be noted that Tor Browser has been rebased on Firefox ESR 91 some time after my comment here.

**Comment by Miodec** [comment]
I've added a debug message to the console `Showing words. wordHeight: ${wordHeight}, wordsHeight: ${wordsHeight}`.

If you encounter this bug let me know what mode you used, your `showAllLines` setting and browser.

**Comment by Miodec** [comment]
Bonus points if you can get a screen recording of this issue.

**Comment by staticssleever668** [comment]
Hi, I was lucky enough to get this when I opened monkeytype literally right after seeing your reply.
The debug message says `Showing words. wordHeight: 11.84, wordsHeight: 0`. Unfortunately I accidentally started the test after making a screenshot so I couldn't try changing the `showAllLines` setting.
Browser is Tor Browser 11.0.3 (based on Firefox 91.4.1esr).

![Screenshot](https://user-images.githubusercontent.com/64694940/146993641-6a4748e5-adc9-4ed0-9521-6e38de153958.png)

**Comment by Miodec** [comment]
Just a check up on this - have you guys experienced it lately?

**Comment by bilfri** [comment]
@Miodec No, haven't experienced it this year

**Comment by Miodec** [comment]
Alright, ill close it for now. Comment if you see it again.

**Comment by hvzhim** [comment]
I'm experiencing this issue quite a bit lately. Usually when I first load the site it's fine but if I refresh it gets stuck in the 1-line mode.

OS: Ubuntu 20.04
Browser: Chrome
Browser Version: 97.0.4692.99 

![monkeytype](https://user-images.githubusercontent.com/27097476/154200719-97d2af0a-7ea0-48ea-bab5-f3e22b5c76bd.png)
