### ISSUE TITLE
Locked out of account

### ISSUE THREAD

**Issue by ghost** [Miodec/monkeytype#1967]
**Describe the bug** 

I was trying out different settings and suddenly got logged out and can't log back in (tried with different browsers). Please help me recover my account.

**To Reproduce** 

1. Go to 'Settings'
2. Click on different settings (not sure which ones I did)
3. Refresh page to apply new settings
4. See 'Signed out' error
5. Try to log in again
6. See 'Signed out' and other errors

**Expected behavior** 

No problems when trying to log in.

**Screenshots** 

<img width="350" alt="Screenshot 2021-10-07 at 21 23 56" src="https://user-images.githubusercontent.com/30378821/136457077-6a1c1126-468b-4c4c-8ce0-34913c5ac110.png">

**Desktop:** 

- OS: [MacOS] 
- Browser [Firefox] 
- Browser Version [93.0] 

**Additional context**

**Comment by Azirine** [comment]
Update: I can now login with Safari but still getting errors on Firefox.

**Comment by Miodec** [comment]
This is not dependent on the browser, but how many times you request your account data. The limit is 60 times per hour as far as i remember. Any more will result in rate limiting like you see here.
