### ISSUE TITLE
Weird words in English 5k

### ISSUE THREAD

**Issue by ghost** [Miodec/monkeytype#1974]
Looking at the [English 5k list](https://github.com/Miodec/monkeytype/blob/master/static/languages/english_5k.json), there are a lot of weird entries like 'usc', 'trembl', 'wv' and 'ns' that are not words, nor are they in the larger English 10k or 25k lists. The number of entries that are not words is astounding and feels obvious when typing (I can get a faster time on 10k than on 5k). I found a higher quality list of 5k English words on this [Oxford dictionary website](https://www.oxfordlearnersdictionaries.com/wordlists/oxford3000-5000), which can be used in replacement of the current list.

**Comment by Azirine** [comment]
I found a good list of 5k English words on this [Oxford dictionary website](https://www.oxfordlearnersdictionaries.com/wordlists/oxford3000-5000).

**Comment by Miodec** [comment]
Nevermind, i think i got it to work. For some reason it was not being copied correctly.
