### ISSUE TITLE
Improve GitHub templates

### ISSUE THREAD

**Issue by SeerLite** [Miodec/monkeytype#1979]
### Issue templates
It looks like GitHub has a [new beta feature](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) to turn issue creation into forms. I think that's a lot cleaner than the current Markdown comments and could make new users a lot more comfortable reporting issues.
See [Kakoune](https://github.com/mawww/kakoune/blob/21494e5d7890935f9c45c326dd278671b7c02042/.github/ISSUE_TEMPLATE/bug_report.yml)'s issue template as an example. I'm not sure if pull requests have this functionality yet but if they do it'd be nice to have it for them too.

### Redirect to Discussions in new issue options
I'm not too sure about how this works: When [creating issues in the Kakoune repository](https://github.com/mawww/kakoune/issues/new/choose), there's an option with a link to an IRC channel. Instead of filling a template, it redirects to a page with a web IRC client. It's defined in the [config.yml](https://github.com/mawww/kakoune/blob/21494e5d7890935f9c45c326dd278671b7c02042/.github/ISSUE_TEMPLATE/config.yml), but it looks like it's just for contact links?

Monkeytype has that too but for security vulnerabilities but it's not set anywhere so I guess that's a repository setting.

Anyway where I want to get with this is that feature requests are currently not allowed as issues but the option when creating them is still there. It'd be nice to figure out a way to redirect to the Discussions tab directly from the option. Again, not sure how it works so I'm not sure if it's possible.

---

Thoughts?

**Comment by Miodec** [comment]
Discussed on Discord.

Updated the bug report template to use the new form system.
