### ISSUE TITLE
restarting test without quick tab in safari breaks scrolling

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2051]
Only happens when test is active.
Only happens when using tab + enter.
Scrolling becomes sluggish, doesn't have momentum anymore.
Scroll bar is not visible.
Changing the size of the browser fixes the issue.

**Comment by Miodec** [comment]
Looks like this got fixed by 76664fc7ae778a58bf803a8558dc71e2279d6941 - probably an issue with changing focus too many times?
