### ISSUE TITLE
Typing ` on a test provides NaN% accuracy.

### ISSUE THREAD

**Issue by delivey** [Miodec/monkeytype#2057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

When the first character you type on a test is the "`" character, the accuracy display shows NaN%

### Expected Behavior

It should show 0% instead.

### Steps To Reproduce

1. Enable live accuracy.
2. Start a typing test (time, words, doesn't matter)
3. Press the ` button on the keyboard.

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: Version 95.0.4638.69 (Official Build) (64-bit)

### Anything else?

![image](https://user-images.githubusercontent.com/35540227/140064727-99fd1ba2-9ac8-4789-9056-083da8cc37a6.png)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Fixed. UI will no longer update if accuracy is nan. Will be live soon.
