### ISSUE TITLE
A tag cannot be created with special symbols, but it could be edited to have those

### ISSUE THREAD

**Issue by qezz** [Miodec/monkeytype#2058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Error popup appears when I'm trying to create a tag with a colon (or any other special symbol) in it's name. Although it is possible to edit a tag to have those.

### Expected Behavior

It looks like tags could have special symbols in their names, so I guess the expected behavior is to be able to create tags with special symbols.

### Steps To Reproduce

1. Go to settings
2. Click 'create new tag'
3. Attempt to use any special symbols in its name

It's expected to fail

1. Go to settings
2. Click 'create new tag'
3. Don't use any special symbol in its name
4. Then, edit that tag to have special symbols

This expected to succeed

### Environment

- OS: Windows
- Browser: Firefox
- Browser Version: 93.0 (64-bit)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by qezz** [comment]
@Miodec strange. Would it be useful if I share some tag IDs, so you can check them inside the database?

Let me know if any other information would be useful.

**Comment by Miodec** [comment]
I don't think if that would be useful but sure, whats your user name? This code runs both on tag creation and tag name edit, so I'm not sure how you added a colon to the tag name.

```js
if (name === null || name === undefined || name === "") return false;
  if (name.length > 16) return false;
  return /^[0-9a-zA-Z_.-]+$/.test(name);
```

**Comment by qezz** [comment]
@Miodec My username is `kezvision`

BTW, I can see that tag's name changed after a successful POST request to `https://api.monkeytype.com/user/tags/edit` with the `newname` value being whatever I typed into the tag edit form.

**Comment by Miodec** [comment]
Welp, i found it. Smooth brain moment from me.

**Comment by qezz** [comment]
Great, thanks!
