### ISSUE TITLE
Logging in doesnt work

### ISSUE THREAD

**Issue by hugohabicht01** [Miodec/monkeytype#2065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

All requests to the api and firebase time out or fail, making it impossible to log in

### Expected Behavior

All api calls as well as calls to firebase should succeed

### Steps To Reproduce

Go to [monkeytype](https://monkeytype.com/login) and try logging in

### Environment

- OS: Arch
- Browser: Brave
- Browser Version:1.31.88, doesnt matter tho

### Did you check incognito mode?

- [ ] I have checked incognito mode

**Comment by Miodec** [comment]
Server had a bit of a panic attack. All good now.
