### ISSUE TITLE
Helvetica font is Comic Sans

### ISSUE THREAD

**Issue by mrbrianevans** [Miodec/monkeytype#2074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

When the Helvetica font family is selected in settings, the font of the webpage is set to Comic Sans instead.

### Expected Behavior

I would expect it to set the font to Helvetica

### Steps To Reproduce

1. Open settings command palatte
2. click on the font family setting
3. choose "helvetica"
4. the webpage is now comic sans

### Environment

- OS: Windows 10
- Browser: Chrome and Firefox tested
- Browser Version:

### Anything else?

This is what helvetica should look like:
![helvetica](https://upload.wikimedia.org/wikipedia/commons/2/28/HelveticaSpecimenCH.svg)

For more info, see https://en.wikipedia.org/wiki/Helvetica

This is whats causing the issue: https://github.com/Miodec/monkeytype/blob/81b4173bdc31d76f326bc86e796409ccb50e9570/static/fonts/_list.json#L33-L34

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Intended.
