### ISSUE TITLE
Clavier AZERTY, impossible d'utiliser les accents circonflexe : ê û ô...

### ISSUE THREAD

**Issue by sannier3** [Miodec/monkeytype#2081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Etant avec un clavier AZERTY, il m'est impossible d'utiliser les accents circonflexe : ê û ô...
Sur le clavier AZERTY, pour marquer le mot côté, nous devons utiliser l'accent(le chapeau) et ensuite la lettre qui va avec
Quand je marque l'accent circonflexe : pour le mot côté -> appui sur ^ = c_ | appui sur o -> c**ôt** avec ôt en rouge qui compte la frappe comme une erreur

### Steps To Reproduce

Sur le clavier AZERTY, pour marquer le mot **côté,** nous devons utiliser l'accent(le chapeau) et ensuite la lettre qui va avec
pour le mot côté -> appui sur ^ = c_ | appui sur o -> c**ôt** avec ôt en rouge qui compte la frappe comme une erreur

### Environment

- OS : Windows 11 or Windows 10
- Browser : Google Chrome DEV and edge
- Browser Version : Chrome = 97.0.4692.8 (Build officiel) dev (64 bits) | EDGE = 95.0.1020.44 (Version officielle) (64 bits)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Use English please
