### ISSUE TITLE
Previous play cursor doesn't pause

### ISSUE THREAD

**Issue by Kuameh** [Miodec/monkeytype#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

The previous play cursor which shows your previous typing speed doesn't pause when the typing session is out of focus
![MONKEYTYPE BUG](https://user-images.githubusercontent.com/56304597/142447223-d9d7b8c5-ab13-4b28-990b-b7bebdaea31b.gif)

### Expected Behavior

I was expecting the cursor to pause also when I'm out of focus and resume when I click to focus

### Steps To Reproduce

- Start a new typing session. (I used the words mode)
- Finish the session and repeat it.
- Start the repeated session to a point and go out of focus.
- The gray cursor would continue to move

### Environment

- OS: Windows 10
- Browser: Chrome
- Browser Version: 95.0.4638.69 (Official Build) (64-bit)

- Browser: Firefox
- Browser Version: 94.0.1 (64-bit)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Its not meant to stop.
