### ISSUE TITLE
issue with wikipedia mode

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2112]

**Comment by Miodec** [comment]
![image](https://user-images.githubusercontent.com/13181393/142959755-0512421f-c3a0-4bdb-8d6d-11dc00bdca46.png)

Looks like no space is being inserted where a reference link used to be in the original wiki article. 

@Jonny-exe do you think you could have a look at this?

**Comment by Jonny-exe** [comment]
Yes, no problem, I'll have a look at it.

**Comment by Jonny-exe** [comment]
The data I get from the Wikipedia API doesn't contain the space ([API data](https://en.wikipedia.org/w/api.php?action=query&format=json&pageids=242702&prop=extracts&exintro=true&explaintext=true&origin=*)).

**Comment by Miodec** [comment]
Maybe we can use regex to add the missing spaces?

**Comment by DanGonite57** [comment]
Have you considered just using the "extract" field from the REST API call (https://en.wikipedia.org/api/rest_v1/page/random/summary)? https://github.com/Miodec/monkeytype/blob/87a9e9aa25ec5ef4a673bce9ecc26d3dba747747/src/js/test/wikipedia.js#L15-L16

Granted it will generally provide a much shorter segment compared to TextExtracts's.

**Comment by Estebene** [comment]
Should it be a new line or space?

**Comment by Miodec** [comment]
Space
