### ISSUE TITLE
Slow timer in Microsoft Edge

### ISSUE THREAD

**Issue by karhincheong** [Miodec/monkeytype#2172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

https://user-images.githubusercontent.com/89685568/145708808-0e87fb8b-7cc9-48c7-8ccd-c40c49effb2b.mp4

As in the video, the cursor lags and it will say that there was a bad timer error and stop the test immediately. This only happens in 'time' mode

### Steps To Reproduce

1. Go to [Monkeytype](https://monkeytype.com)
2. Take a typing test

### Environment

- OS: Windows 10 Version 21H2 (OS Build 19044.1348)
- Browser: Microsoft Edge (Dev build)
- Browser Version: Microsoft Edge version 98.0.1093.6 (Official build) dev (64-bit)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
The 'cursor lag' is the website disabling animations to hopefully recover from the timer running slowly. 

Does this happen in other browsers?

**Comment by karhincheong** [comment]
Also happens in Microsoft Edge Stable version

**Comment by Miodec** [comment]
What about chrome?

**Comment by karhincheong** [comment]
Nope. Doesn't happen in Google Chrome

**Comment by blitzcaster** [comment]
Did you enable Edge's Efficiency Mode? I'm also having the same problem and disabling Efficiency Mode helps.

**Comment by karhincheong** [comment]
> Did you enable Edge's Efficiency Mode? I'm also having the same problem and disabling Efficiency Mode helps.

Yep, that solves the problem. Thanks!
