### ISSUE TITLE
Launching command-line tool resets custom font to times new roman 

### ISSUE THREAD

**Issue by jameszhang-a** [Miodec/monkeytype#2188]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Font used: Cascadia Code Mono

- Launching command-line tool changes all fonts back to Times New Roman
- If exiting tool without changing any settings, then the font goes back to the custom font
- If I make a change in the command-line tool, then the font changes to Times New Roman until I refresh the page

### Expected Behavior

- The font stays the same

### Steps To Reproduce

1. Change font to custom: Cascadia Code Mono (with it installed)
2. Launch command-line tool with either `esc` or `cmd+shift+p`

### Environment

- OS: macOS Monterey 12.1
- Browser: Brave 1.33.106 and Safari 15.2 (both tested)
- Browser Version: ^

## Default
![Screen Shot 2021-12-17 at 1 04 37 AM](https://user-images.githubusercontent.com/83667312/146503428-385fa723-7872-4049-b27a-f469da9b3fc4.png)

## Command-line tool up
![Screen Shot 2021-12-17 at 1 05 00 AM](https://user-images.githubusercontent.com/83667312/146503477-477b70bb-7588-4b3e-b46e-bc29e59a653a.png)

## After making a selection 
![Screen Shot 2021-12-17 at 1 05 47 AM](https://user-images.githubusercontent.com/83667312/146503576-bc43da78-5318-49bb-98cd-f3894db37377.png)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Estebene** [comment]
Just had a little look into this, it is really weird. To more fully understand the problem, could I get you to use something like [WhatFont](https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm). If I am correct, it will tell you that the font you have is not Cascadia Code Mono but rather Roboto Mono. When the font is first set, it also adds the option for Roboto Mono, but when the commandLine searches in removes this option which is why the browser defaults to Times New Roman. Thanks for your help.

**Comment by jameszhang-a** [comment]
Ya you're completely right, and the reason this happens is because the font is actually called either `Cascadia Code` or `Cascadia Mono`, but I mistakenly combined the two. 

So it looks like if any font that doesn't exist is applied, the bug I encountered will happen. 

Here's a random font in the app: 
![Screen Shot 2021-12-17 at 4 54 46 PM](https://user-images.githubusercontent.com/83667312/146617046-7ace2c7f-d7ef-4967-80ab-7134b785cf93.png)
 
Here's the same font in command-line:
![Screen Shot 2021-12-17 at 4 55 44 PM](https://user-images.githubusercontent.com/83667312/146617119-4825fd59-66f6-4038-bbd9-f2f287b34185.png)

I guess one possible solution is to make the default font always `Roboto Mono` even if it's in the command-line? Or better yet, check if the custom font the user entered is valid or not, if not just override it or throw an error popup.

**Comment by Miodec** [comment]
There is no way to check if the font is valid (by that im assuming you mean if its installed on the system)

**Comment by Miodec** [comment]
Alright after some testing, looks like the settings page custom button is falling back to roboto mono, while the command line doesnt. 

Settings page
![image](https://user-images.githubusercontent.com/13181393/146652630-7ac602d2-93dd-4197-afd1-ca86f07502f5.png)


Command line
![image](https://user-images.githubusercontent.com/13181393/146652634-f576d6a8-39f2-4738-9135-887ea3409d5c.png)


Should be easy
