### ISSUE TITLE
username no more bind with email 

### ISSUE THREAD

**Issue by ans1genie** [Miodec/monkeytype#2197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

when login with email asked to have a new username, my old username seem to be taken.

### Expected Behavior

should not ask about username!

### Environment

- OS: macOS Monterey
- Browser: Google Chrome
- Browser Version: Version 96.0.4664.93 (Official Build) (x86_64)

### Did you check incognito mode?

- [X] I have checked incognito mode

### Config

{"theme":"serika_dark","customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":30,"mode":"time","quoteLength":[1],"language":"english","fontSize":15,"freedomMode":false,"resultFilters":null,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false}

**Comment by Miodec** [comment]
Whats your username? Whats the message that youre getting?

**Comment by ans1genie** [comment]
username: ans1genie

message
![image](https://user-images.githubusercontent.com/16513804/146691734-35afc7a3-bc1b-4d46-bddd-ee15ffe1b5f3.png)

**Comment by Miodec** [comment]
I checked your account and everything seems fine. Can you clear website data and try to login again?

**Comment by Miodec** [comment]
Try setting it to `ans1genie1` or something as a test?

**Comment by ans1genie** [comment]
set to ans1genie1 but can't be change to ans1genie again :3 
![image](https://user-images.githubusercontent.com/16513804/146810340-2f738dae-0d67-40e4-a46b-672b1821b7b1.png)

**Comment by Miodec** [comment]
Right, as i suspected - you created 2 accounts. The `ans1genie1` is using google sign in and doesn't have any data. Please go to the settings page and delete that account. Your main account, `ans1genie` is using email authentication, not gmail. The email you used is `a**s@a******a.me`.
