### ISSUE TITLE
Problems with caret mode

### ISSUE THREAD

**Issue by iambeingtracked** [Miodec/monkeytype#2221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

It simply doesn't work

### Expected Behavior

So that it works

### Steps To Reproduce

It's not properly working because i've made too much browser customizations. 
Find where your firefox profile is open about:profiles and open the root directory of the currently used profile (or create a new one).
drop firefox.cfg and prefs.js into there
Create a directory defaults and a directory called distribution.
Drop policies.json into distribution and inside defaults create a directory pref in which drop autoconfig.js 

I'm really sorry but i can't upload

### Environment

- OS: GNU/Linux
- Browser: Firefox
- Browser Version: 95.0.2

### Anything else?

firefox.cfg: 
// IMPORTANT: Start your code on the 2nd line
pref("app.normandy.api_url", "");
pref("app.normandy.enabled", false);
pref("app.shield.optoutstudies.enabled", false);
pref("app.update.auto", false);
pref("beacon.enabled", false);
pref("breakpad.reportURL", "");
pref("browser.aboutConfig.showWarning", false);
pref("browser.cache.offline.enable", false);
pref("browser.crashReports.unsubmittedCheck.autoSubmit", false);
pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
pref("browser.crashReports.unsubmittedCheck.enabled", false);
pref("browser.disableResetPrompt", true);
pref("browser.fixup.alternate.enabled", false);
pref("browser.newtab.preload", false);
pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
pref("browser.newtabpage.enabled", false);
pref("browser.newtabpage.enhanced", false);
pref("browser.newtabpage.introShown", true);
pref("browser.safebrowsing.appRepURL", "");
pref("browser.safebrowsing.blockedURIs.enabled", false);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.downloads.remote.enabled", false);
pref("browser.safebrowsing.downloads.remote.url", "");
pref("browser.safebrowsing.enabled", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.phishing.enabled", false);
pref("browser.search.suggest.enabled", false);
pref("browser.selfsupport.url", "");
pref("browser.send_pings", false);
pref("browser.sessionstore.privacy_level", 2);
pref("browser.shell.checkDefaultBrowser", false);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.tabs.crashReporting.sendReport", false);
pref("browser.urlbar.groupLabels.enabled", false);
pref("browser.urlbar.quicksuggest.enabled", false);
pref("browser.urlbar.speculativeConnect.enabled", false);
pref("browser.urlbar.trimURLs", false);
pref("datareporting.healthreport.service.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("device.sensors.ambientLight.enabled", false);
pref("device.sensors.enabled", false);
pref("device.sensors.motion.enabled", false);
pref("device.sensors.orientation.enabled", false);
pref("device.sensors.proximity.enabled", false);
pref("dom.battery.enabled", false);
pref("dom.event.clipboardevents.enabled", false);
pref("dom.webaudio.enabled", false);
pref("experiments.activeExperiment", false);
pref("experiments.enabled", false);
pref("experiments.manifest.uri", "");
pref("experiments.supported", false);
pref("extensions.blocklist.enabled", false);
pref("extensions.getAddons.cache.enabled", false);
pref("extensions.getAddons.showPane", false);
pref("extensions.greasemonkey.stats.optedin", false);
pref("extensions.greasemonkey.stats.url", "");
pref("extensions.pocket.enabled", false);
pref("extensions.shield-recipe-client.api_url", "");
pref("extensions.shield-recipe-client.enabled", false);
pref("extensions.webservice.discoverURL", "");
pref("general.useragent.override", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0");
pref("media.autoplay.default", 1);
pref("media.autoplay.enabled", false);
pref("media.eme.enabled", false);
pref("media.gmp-widevinecdm.enabled", false);
pref("media.navigator.enabled", false);
pref("media.peerconnection.enabled", false);
pref("media.video_stats.enabled", false);
pref("network.allow-experiments", false);
pref("network.captive-portal-service.enabled", false);
pref("network.cookie.cookieBehavior", 1);
pref("network.dns.disablePrefetch", true);
pref("network.dns.disablePrefetchFromHTTPS", true);
pref("network.http.referer.spoofSource", true);
pref("network.http.speculative-parallel-limit", 0);
pref("network.predictor.enable-prefetch", false);
pref("network.predictor.enabled", false);
pref("network.prefetch-next", false);
pref("network.trr.mode", 5);
pref("pdfjs.enableScripting", false);
pref("privacy.firstparty.isolate", true);
pref("privacy.resistFingerprinting", true);
pref("privacy.trackingprotection.cryptomining.enabled", true);
pref("privacy.trackingprotection.enabled", true);
pref("privacy.trackingprotection.fingerprinting.enabled", true);
pref("privacy.trackingprotection.pbmode.enabled", true);
pref("privacy.usercontext.about_newtab_segregation.enabled", true);
pref("security.ssl.disable_session_identifiers", true);
pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite", false);
pref("signon.autofillForms", false);
pref("toolkit.telemetry.archive.enabled", false);
pref("toolkit.telemetry.bhrPing.enabled", false);
pref("toolkit.telemetry.cachedClientID", "");
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.firstShutdownPing.enabled", false);
pref("toolkit.telemetry.hybridContent.enabled", false);
pref("toolkit.telemetry.newProfilePing.enabled", false);
pref("toolkit.telemetry.prompted", 2);
pref("toolkit.telemetry.rejected", true);
pref("toolkit.telemetry.reportingpolicy.firstRun", false);
pref("toolkit.telemetry.server", "");
pref("toolkit.telemetry.shutdownPingSender.enabled", false);
pref("toolkit.telemetry.unified", false);
pref("toolkit.telemetry.unifiedIsOptIn", false);
pref("toolkit.telemetry.updatePing.enabled", false);
pref("webgl.disabled", true);
pref("webgl.renderer-string-override", " ");
pref("webgl.vendor-string-override", " ");

prefs.js:
user_pref("app.normandy.api_url", "");
user_pref("app.normandy.enabled", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.auto", false);
user_pref("beacon.enabled", false);
user_pref("breakpad.reportURL", "");
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
user_pref("browser.disableResetPrompt", true);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.newtab.preload", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.safebrowsing.appRepURL", "");
user_pref("browser.safebrowsing.blockedURIs.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.selfsupport.url", "");
user_pref("browser.send_pings", false);
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.urlbar.groupLabels.enabled", false);
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("browser.urlbar.speculativeConnect.enabled", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("device.sensors.ambientLight.enabled", false);
user_pref("device.sensors.enabled", false);
user_pref("device.sensors.motion.enabled", false);
user_pref("device.sensors.orientation.enabled", false);
user_pref("device.sensors.proximity.enabled", false);
user_pref("dom.battery.enabled", false);
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("dom.webaudio.enabled", false);
user_pref("experiments.activeExperiment", false);
user_pref("experiments.enabled", false);
user_pref("experiments.manifest.uri", "");
user_pref("experiments.supported", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.greasemonkey.stats.optedin", false);
user_pref("extensions.greasemonkey.stats.url", "");
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.shield-recipe-client.api_url", "");
user_pref("extensions.shield-recipe-client.enabled", false);
user_pref("extensions.webservice.discoverURL", "");
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0");
user_pref("media.autoplay.default", 1);
user_pref("media.autoplay.enabled", false);
user_pref("media.eme.enabled", false);
user_pref("media.gmp-widevinecdm.enabled", false);
user_pref("media.navigator.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.video_stats.enabled", false);
user_pref("network.allow-experiments", false);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dns.disablePrefetchFromHTTPS", true);
user_pref("network.http.referer.spoofSource", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enable-prefetch", false);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.trr.mode", 5);
user_pref("pdfjs.enableScripting", false);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.resistFingerprinting", true);
user_pref("privacy.trackingprotection.cryptomining.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
user_pref("privacy.trackingprotection.pbmode.enabled", true);
user_pref("privacy.usercontext.about_newtab_segregation.enabled", true);
user_pref("security.ssl.disable_session_identifiers", true);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite", false);
user_pref("signon.autofillForms", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.cachedClientID", "");
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.hybridContent.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.unifiedIsOptIn", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("webgl.disabled", true);
user_pref("webgl.renderer-string-override", " ");
user_pref("webgl.vendor-string-override", " ");

policies.json:
{
  "policies": {
    "NewTabPage": false,
    "DisplayMenuBar": true,
    "DisableFirefoxAccounts": true,
    "NetworkPrediction": false,
    "DisableFirefoxScreenshots": true,
    "CaptivePortal": false,
    "DNSOverHTTPS": {
      "Enabled": false
    },
    "DisableFirefoxStudies": true,
    "DisableTelemetry": true,
    "DisablePocket": true,
    "ExtensionSettings": {
      "uBlock0@raymondhill.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "jid1-MnnxcxisBPnSXQ@jetpack": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "https-everywhere@eff.org": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/https-everywhere/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "CanvasBlocker@kkapsner.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/canvasblocker/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "FirefoxMulti-AccountContainers@mozilla.org": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/multi-account-containers/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "TemporaryContainers@stoically": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/temporary-containers/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "ClearURLs@kevinr": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/clearurls/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "Decentraleyes@ThomasRientjes": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/decentraleyes/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "uMatrix@raymondhill.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/umatrix/latest.xpi",
        "installation_mode": "normal_installed"
      },
      "CookieAutoDelete@kennydo.com": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/cookie-autodelete/latest.xpi",
        "installation_mode": "normal_installed"
      }
    },
    "DisableAppUpdate": true,
    "DisableBuiltinPDFViewer": true,
    "DisableFormHistory": true
  }
}

autoconfig.js:
pref("general.config.filename", "firefox.cfg");
pref("general.config.obscure_value", 0);

### Did you check incognito mode?

- [X] I have checked incognito mode

### Config

{"theme":"serika_dark","customTheme":true,"customThemeColors":["#2b3339","#a7c080","#4b565c","#4b565c","#d3c6aa","#e67e80","#e67e80","#e67e80","#e67e80"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[1],"language":"english_1k","fontSize":15,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"mini","colorfulMode":false,"randomTheme":"fav","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"CaskaydiaCove_Nerd_Font","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false}

**Comment by CameronCT** [comment]
> It's not properly working because i've made too much browser customizations.

Why should Monkeytype be expected to fix something if it's a problem with your external customization?

**Comment by Miodec** [comment]
I agree with @CameronCT on this, im afraid I can't really do much here, especially with the number of changes you've made - who knows which one breaks it.

If incognito is not working then yeah, it's gonna be an issue with your browser customizations.

Sorry.

**Comment by iambeingtracked** [comment]
Okay, no problem
