### ISSUE TITLE
Caret bouncing in zen mode

### ISSUE THREAD

**Issue by ansh-saini** [Miodec/monkeytype#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

When "strict space" is turned on in zen mode, typing empty space characters cause the caret to bounce up and down.

https://user-images.githubusercontent.com/32511936/147849099-6170266f-4e3e-49b7-ae9f-fb4be5a7f178.mp4

### Expected Behavior

Caret should travel in a straight line regardless of what character is being typed.

### Steps To Reproduce

1. Switch to zen mode
2. Press `esc` key to bring up the command palette.
3. Set "strict space" to "on".
4. Start pressing spacebar multiple times.

### Environment

- OS: Windows 11
- Browser: Google Chrome
- Browser Version: 96.0.4664.110

### Did you check incognito mode?

- [X] I have checked incognito mode

### Config

```JSON
{
  "strictSpace": true
}
```

**Comment by ansh-saini** [comment]
Hi, my apologies if I missed something while opening the issue. Can you please tell me why it was closed?

**Comment by Miodec** [comment]
![image](https://user-images.githubusercontent.com/13181393/147856763-e9aceae9-fa2d-49d6-a75d-fe1fceaa18c5.png)

This message references the 3b9f90fb7f8482561a9ce3c64ddf7436e9952ff3 commit, in which i fixed this issue.

If you dont see it on the live website, it either means that I have not pushed the changes yet, or you need to clear cache.

**Comment by ansh-saini** [comment]
Oh okay. Thanks for the clarification Jack.
