### ISSUE TITLE
Overlapping Parts in Homescreen

### ISSUE THREAD

**Issue by teddinotteddy** [Miodec/monkeytype#2266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

(I don't have an image of this issue but I do have an image of the part that overlap) When on iPad live wpm and accuracy overlap with the part displayed in the image.
 

### Expected Behavior

Rather than having the parts overlap the settings box could be moved to the side.

### Steps To Reproduce

(This is only visible on mobile or kinda small screens) Turn on live wpm and accuracy. Then make time style to text. 

### Environment

- OS: iPadOS 15 
- Browser: Safari 
- Browser Version: Safari 15

### Anything else?

<img width="1552" alt="Screen Shot 2022-01-06 at 2 20 26 PM" src="https://user-images.githubusercontent.com/83455454/148446763-7f276111-08c7-4a07-bdfe-2be9920e2367.png">

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
They overlap to make sure the typing page has no scrollbars. You can always disable the tips, disable the monkey, or change the timer style to text, which is way smaller.
