### ISSUE TITLE
[Bépo keyboard] the ^ on a letter does not work in french

### ISSUE THREAD

**Issue by mayweed** [Miodec/monkeytype#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Hi
I use a bépo keyboard and test my typing speed in french. When i try to type a word like plaît i’ve got a mistake on the i and t. I must press two keys to got the î (one for the ^ and the other for the given letter). It’s as if monkey type is waiting for a î in a single key press which is not possible in bépo! Would be nice if you could correct that, will make monkeytype perfect :)
Thx
Guillaume

### Expected Behavior

You would expect that î in two key presses does not make a mistake in two letters.

### Steps To Reproduce

Just try to type a î in bépo or a ê in two key presses.

### Environment

- OS: Arch Linux
- Browser: Chromium
- Browser Version:

### Anything else?

no

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by druotoni** [comment]
Hi, I tried with bepo "official" layout for Windows (from https://bepo.fr/) and it works ok for "plaît".
I presume you're not using the layout emulator because it don't handle dead key like ^.

Maybe the bug is due to how the bépo layout is implemeted on linux.
According to bepo.fr    http://bepo.fr/wiki/Console_GNU/Linux

> La disposition est nommée « fr-bepo » sauf si installée « à la main » auquel cas elle est nommée « fr-dvorak-bepo-utf8 » (il faudra alors adapter les commandes à taper).
> 
> De plus, le comportement des touches mortes étant défini en dehors des pilotes, leur comportement peut-être incomplet ou partiellement différent des spécifications officielles de la disposition
> 
> Les dispositions « fr-bepo-latin9 » et « fr-dvorak-bepo » ne possèdent que les caractères iso-8859-15 de la disposition sont disponibles. Seules certaines touches mortes (accent grave, aigu, circonflexe, tilde, tréma, cédille, ogonek, caron, brève et double accent aigu sont disponibles — ce qui exclu notamment la touche morte grecque, monétaire et la barre inscrite).

**Comment by mayweed** [comment]
Hello
Thanks @Miodec I switch off the emulator and it works fine!!
