### ISSUE TITLE
Funbox style is still applied in pages other than the test page

### ISSUE THREAD

**Issue by YarikRevich** [Miodec/monkeytype#2313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Menu screen starts to rotate after the test

### Expected Behavior

Menu screen SHOULD NOT rotate

### Steps To Reproduce

1. Go to settings and set "read ahead hard" test
2. Pass the test
3. See bug when menu screen starts to rotate

### Environment

- OS: MacOS
- Browser: Google Chrome
- Browser Version: 97.0.4692.71 (Official Build) (x86_64)

### Did you check incognito mode?

- [x] I have checked incognito mode

**Comment by Miodec** [comment]
Are you sure you don't have the round round baby funbox enabled instead?

**Comment by teddinotteddy** [comment]
Could you provide a video of this?

**Comment by YarikRevich** [comment]
I'm sorry. The mode was "round round baby". After the test, menu screen sometimes can unexpectedly start to rotate

**Comment by Miodec** [comment]
Any chance you can record this?

**Comment by Miodec** [comment]
This happens if you complete a round round baby (or any style funbox i think) and go to the settings page directly from the result page.

**Comment by Miodec** [comment]
Turns out you dont even need to complete the test.

**Comment by YarikRevich** [comment]
You are right.

**Comment by YarikRevich** [comment]
It's completely what i wanted to report

**Comment by YarikRevich** [comment]
So, will you fix that?

**Comment by Miodec** [comment]
Its fixed

**Comment by YarikRevich** [comment]
Ok. Thanks
