### ISSUE TITLE
Inconsistent behaviour when reverting funbox

### ISSUE THREAD

**Issue by tricarbonate** [Miodec/monkeytype#2325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

When reverting a funbox and going back to a timed mode, the 'punctuation' and 'numbers' settings get turned on/off randomly

### Expected Behavior

I think it could be better if 'punctuation' and 'numbers' settings are set to their original state when reverting funbox.

### Steps To Reproduce

1. Activate 'time' mode, with 'punctuation' and 'numbers' settings on.
2. Change funbox to '55808'
3. Change funbox to 'none', you'll see 'numbers' is off now
4. Do the same with the funbox 'specials' or any other, and you'll see a different behaviour

### Environment

- OS: Linux Mint
- Browser: Tried on Firefox, Chrome and Opera
- Browser Version:

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by tricarbonate** [comment]
Also, if this is indeed not intended behaviour, could I be assigned to this issue

**Comment by Miodec** [comment]
Not intended
