### ISSUE TITLE
Clicking "restart test" when practicing missed words will start a new test with new words

### ISSUE THREAD

**Issue by Kelvets** [Miodec/monkeytype#2344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

If 1- you click to practice missed/slow words or 2- click to repeat the test with the same sequence of words as before, if you click the "repeat test" button in the middle of the test, it will instead give you a completely new test and your missed/slow words or the sequence you wanted to practice are seemingly lost forever. When clicking the button a "Notice: reverting to previous settings" notification will appear in the top-right corner.

### Expected Behavior

Keeps the same words configuration as before, allowing you to restart properly.

### Environment

- OS: Windows 10
- Browser: Firefox
- Browser Version: 92

### Anything else?

I have tested it on Chrome in Incognito and the same thing happens.

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
This is intended. If you want to continue to practice you need to complete that test and then click "repeat" or "practice missed/slow words" again.
