### ISSUE TITLE
Unexpected 403 status code in development

### ISSUE THREAD

**Issue by Bruception** [Miodec/monkeytype#2362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Suddenly started getting 403 HTTP responses when trying to access the frontend. No changes in any configurations where made.

### Environment

- OS: macOS Monterey Version 12.2
- Browser: Google Chrome
- Browser Version: 97.0.4692.99 (Official Build) (arm64)

### Anything else?

![Screen Shot 2022-01-28 at 1 55 05 PM](https://user-images.githubusercontent.com/58147810/151605602-50a5a1c8-82e8-4c20-9432-afec3b8358fc.png)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by CameronCT** [comment]
Do you have the actual console logs of what it shows when you start the server / frontend?

**Comment by Bruception** [comment]
Just attached them here.

![Screen Shot 2022-01-28 at 2 01 36 PM](https://user-images.githubusercontent.com/58147810/151605928-bf279298-46cf-4228-9466-f11b2c3a3caf.png)

**Comment by Miodec** [comment]
What OS are you using

**Comment by Bruception** [comment]
> What OS are you using?
> 
> EDIT: If Mac, disable AirPlay Receiver in Sharing preferences.

How did you figure this out lol.

**Comment by Miodec** [comment]
> > What OS are you using?
> > EDIT: If Mac, disable AirPlay Receiver in Sharing preferences.
> 
> How did you figure this out lol. For future reference: https://developer.apple.com/forums/thread/682332

A lot of googling when i ran into this myself.
