### ISSUE TITLE
Modern Ink mistype font is bugged

### ISSUE THREAD

**Issue by shashumgaGIT** [Miodec/monkeytype#2370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

The font of the mistyped letters are bugged when using the 'modern ink' theme
![Screenshot 2022-01-29 190046](https://user-images.githubusercontent.com/98660711/151672233-699f2a85-bab6-4f78-82b1-906db3b1188a.jpg)

### Environment

- OS: Windows 10 Education N
- Browser: Opera GX
- Browser Version: 82.0.4227.50
and 
- Browser: Google Chrome
- Browser Version: 97.0.4692.99 (Official Build) (64-bit)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Bruception** [comment]
I think this is intentional:
https://github.com/Miodec/monkeytype/pull/2145/files#diff-463e9c1fef27f13e38bc638fa595809c34da300d376f326880a0bb70383c335dR21

**Comment by Miodec** [comment]
It is part of the theme yeah.

**Comment by Miodec** [comment]
Alright, after trying the theme out for a couple tests im gonna remove that.
