### ISSUE TITLE
Failes to save results.

### ISSUE THREAD

**Issue by Skeef79** [Miodec/monkeytype#2383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Monkey type show this messages, even after clearing cache and hard reload
![image](https://user-images.githubusercontent.com/35370908/151807465-18163833-cd30-4dc1-ae04-1b1895fb58bc.png)

![image](https://user-images.githubusercontent.com/35370908/151807832-a2ee8f2a-b6e8-45cc-96a1-d2c801d4c2f5.png)

### Environment

- OS:
- Browser:
- Browser Version:

### Did you check incognito mode?

- [x] I have checked incognito mode

**Comment by Miodec** [comment]
Please test now

**Comment by Miodec** [comment]
Comment if still an issue.

**Comment by Skeef79** [comment]
Everything is fine, thanks!
