### ISSUE TITLE
Adjust to new legal situation regarding use of google fonts and analytics in Germany and Austria

### ISSUE THREAD

**Issue by bilfri** [Miodec/monkeytype#2386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

The website sends user data (IP address etc.) to google-analytics.com and fonts.googleapis.com without prior consent.

### Expected Behavior

There has recently been a court case where a site was sentenced to a GDPR penalty for using google fonts.
https://news.ycombinator.com/item?id=30135264
Like wise there has been an Austrian ruling that the continued use of Google Analytics is illegal
https://news.ycombinator.com/item?id=29918496

I think these are sane rulings and I hope that Monkeytype will follow the sentiment. I understand it's not straight-forward to switch away from the very convenient use of google services so what's the situation like? what are the obstacles to self-hosting fonts and what's Google Analytics used for at the moment?

### Environment

- OS:
- Browser:
- Browser Version:

### Anything else?

Best,
Lukas

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
There is a section on what kind of log data is collected in the [privacy policy](https://monkeytype.com/privacy-policy), under the `What log data do we collect?` section.

The privacy policy also mentions by using the website you accept those terms.
```
By using the Services, you are expressly and voluntarily accepting the terms and conditions of this Privacy Statement and our Terms of Service, which include allowing us to process information about you.
```

We are using Google Fonts and other CDN's to offload some of the traffic away from the Monkeytype hosting server to those services. Google Analytics is used, well, for analytical and logging purposes.

**Comment by CameronCT** [comment]
I'm pretty sure GDPR violations and whatnot are the responsibility of Google to handle. Meaning if they have to deny it in Austria/Germany, then they will likely deny it from their end and not Monkeytypes.

**Comment by Miodec** [comment]
I see. Can you link me to a site that asks for consent in a way that aligns with the GDPR rules?

**Comment by bilfri** [comment]
First some disclaimers: I'm not a lawyer and I think it's sad how surveillance advertising manipulates the world.

@CameronCT: No, it is also the responsibility of the website that calls Google services. The verdict is pretty clear in that regard (it was the sites owners that was ordered to pay the compensations). If a landlord drills a peephole to the bathroom of a flat they rent out, it doesn't matter who looks through the hole, the landlord is also responsible (not an accusation, just an analogy)

@Miodec: There is a difference regarding consent in the two cases. The first one with the fonts is maybe manageable with the right consent checkbox pop-up thingy, but I would argue that it is preferable in that case to self host.
More importantly the second case (about analytics) says that Google Analytics violates GDPR, no matter what kind of consent is given. 
Here's a pretty well measured article about it:
https://www.infoq.com/news/2022/01/austrian-privacy-gdpr-google/
