### ISSUE TITLE
Failed to save result: incorrect result hash

### ISSUE THREAD

**Issue by mrbrianevans** [Miodec/monkeytype#2389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

I am getting "Failed to save result: incorrect result hash" after finishing a typing test this morning. It does not seem to be a consistent issue as I tried another test and it worked fine. However this is a problem if it sometimes occurs because it could happen on someones PB and then its not recorded. 
As shown in the screenshot below, the test mode was 30 second english.

### Expected Behavior

Should always save result, and if there is an error, clicking retry should work.

### Steps To Reproduce

Unfortunately this doesn't appear to be a very easily reproducable problem, which doesn't help debugging.

### Environment

- OS: Windows 10
- Browser: Firefox 
- Browser Version: 96.0.3 (20220126154723) (64-bit)

### Anything else?

![image](https://user-images.githubusercontent.com/53117772/151936572-8fb97d9c-3375-4202-b1eb-d96d31f8cc7e.png)
The HTTP request to save the result has this request body:
```
POST https://api.monkeytype.com/results/add
```
```json
{"result":{"wpm":100.77,"rawWpm":105.56,"charStats":[252,4,0,0],"acc":95.93,"mode":"time","mode2":30,"quoteLength":-1,"punctuation":false,"numbers":false,"lazyMode":false,"timestamp":1643704211584,"language":"english","restartCount":0,"incompleteTestSeconds":0,"difficulty":"normal","blindMode":false,"tags":[],"keySpacing":[30013],"keyDuration":[101,114,63,73,204,189,78,45,69,280,76,23,106,82,176,51,106,117,89,120,178,104,6,157,132,31,80,149,126,71,146,90,90,182,121,90,51,73,193,72,39,58,82,72,67,66,167,302,246,102,44,105,138,116,59,64,113,16,211,65,120,82,125,59,45,16,104,46,164,58,86,153,127,126,228,46,104,176,107,123,101,85,113,126,81,97,95,85,126,139,92,43,27,115,125,85,144,159,53,37,139,98,100,87,61,169,12,107,69,112,151,169,157,137,155,122,189,113,134,127,48,63,67,97,117,57,99,111,118,51,61,50,107,525,155,83,203,94,68,67,206,77,139,131,167,65,7,142,142,86,191,65,87,120,204,107,138,63,152,63,76,136,99,125,190,73,120,129,200,54,63,75,171,81,120,108,86,43,150,63,49,118,96,144,49,183,64,79,85,72,94,206,89,117,89,132,88,118,100,111,91,48,170,29,131,86,66,4,241,63,86,126,82,222,84,57,158,79,71,95,139,209,131,33,112,5,152,153,54,155,74,100,130,66,31,134,109,97,90,136,61,37,132,93,143,216,172,105,157,104,68,278,241,238,77,64,157,125,103,143,152,145,87,64,30,102,109,85,62,90,222,55,86,80,125],"consistency":82.79,"keyConsistency":null,"funbox":"none","bailedOut":false,"chartData":{"wpm":[96,108,112,111,101,108,111,106,107,108,110,104,102,104,102,102,102,102,102,103,104,105,105,105,106,107,103,99,100,100],"raw":[114,116,116,112,108,116,112,116,112,124,112,96,92,88,100,92,104,104,112,116,120,116,116,112,120,104,88,84,100,120],"err":[0,0,0,0,1,0,0,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,2,0,0]},"testDuration":30.01,"afkDuration":0,"smoothConsistency":90.04,"wpmConsistency":96.4,"uid":"R3xcYIAArteSNs2o8dPernrGA083","hash":"70f092259450aa170c054c6dacb42a309a5066af"}}
```
And the response is:
```
400 Bad Request
```
```json
{"message":"Incorrect result hash"}
```

The timestamp of the response is `Tue, 01 Feb 2022 08:31:41 GMT` if you want to try and find logs relating to it.

### Did you check incognito mode?

- [ ] I have checked incognito mode

**Comment by mrbrianevans** [comment]
Possibly related to #2250, but due to empty description I cannot tell

**Comment by Miodec** [comment]
Alright, i switched the package that does the hashing. Also temporarily disabled hashing all together while i wait for the clients to update their cache.

**Comment by Miodec** [comment]
Server-side hash checking is currently disabled. Created #2433 to find out what's causing this behavior.
