### ISSUE TITLE
Convert API routes to always respond with a data, message object

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2393]
Currently the API is very not predictable. The routes should always return data in the same format. We should convert the endponits to always return data in this format:
```js
{
    data: {}, //any data that was requested - object
    message: "", //status messages OR error message - string
}
```

Requires #2394 to be complete.

**Comment by Mustafiz04** [comment]
Hey @monkeytypegeorge 
Can I do this and #2394 both ??

**Comment by Miodec** [comment]
> Hey @monkeytypegeorge Can I do this and #2394 both ??

#2394 takes priority + this issue will have to be done on a different branch. 

Either way, @Bruception already done some parts of #2394, you gonna have to ask him there if you can do some parts.

**Comment by Bruception** [comment]
> Hey @monkeytypegeorge
> Can I do this and #2394 both ??

Sure. Ideally we want to avoid having to build this object per controller. I was thinking of building this object in a centralized location. Perhaps within the asyncHandlerWrapper function.

**Comment by Mustafiz04** [comment]
@Miodec Got it.
@Bruception can we discuss the way we can do it by tomorrow ??

**Comment by Bruception** [comment]
> @Miodec Got it.
> @Bruception can we discuss the way we can do it by tomorrow ??

Sure. I think it would be easier if you join the Monkey Type discord server though.

**Comment by Mustafiz04** [comment]
I have joined, just let me know when to discuss.

**Comment by Bruception** [comment]
> I have joined, just let me know when to discuss.

Let us discuss in the Development channel.
