### ISSUE TITLE
Setting custom test duration popup loses focus on typing

### ISSUE THREAD

**Issue by wblazej** [Miodec/monkeytype#2406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

The dialog popup is opened and while the user start typing, focus is changed on typing test as shown below:
https://user-images.githubusercontent.com/62674438/152382754-c6df93bd-7189-4506-b204-f0c3ee45ffd8.mov

### Expected Behavior

Focus shouldn't be changed so user can input a number.

### Steps To Reproduce

1. Go to https://monkeytype.com/
2. Select option `time`
3. Choose custom amount of seconds
4. Try to type a number while game is ready to be started in background

### Environment

- OS: MacOS
- Browser: Brave Browser
- Browser Version: [1.34.81 Chromium: 97.0.4692.99](https://brave.com/latest/)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Bruception** [comment]
Found the issue: https://github.com/Miodec/monkeytype/commit/ec4c65356d03d242ae1b5254a31a420fb44cd68f#diff-b463855759e657a5522683c71a13992c8de15084190a0c409379f58c7c83f8e6R666

Seems like the logic should be inverted. Should be `&&` instead of `||`
