### ISSUE TITLE
Issues with outdated npm version 

### ISSUE THREAD

**Issue by TheRealKai** [Miodec/monkeytype#2418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

I am using the latest version of NODE.js. When trying to run my cloned repository on my local machine, I attempted to install the dependencies with `npm install`, however I encountered the error: 

<img width="1440" alt="Screen Shot 2022-02-05 at 11 42 58 AM" src="https://user-images.githubusercontent.com/84258692/152650534-29bf9501-d27b-4f83-9c43-9eb57d9d630a.png">

I see that I am supposed to be using NODE.js version 14.18.1 LTS and the packages install properly when I use this version however, I am wondering why monkeytype isn't using the latest version of NODE for the project.
Also, when using the latest version of npm I got the dependencies to install when I commented out the `engine-strict=true` in `.npmrc` which you can see in the screenshot below, but I do not know if this is a good practice.

<img width="1440" alt="Screen Shot 2022-02-05 at 11 31 45 AM" src="https://user-images.githubusercontent.com/84258692/152650202-6c711b5f-b782-4eb6-9c4c-e71863a3bf6d.png">

### Expected Behavior

I expected to be able to use the latest version of npm to install monkeytype locally on my machine. 

### Steps To Reproduce

1. Clone the repository to local machine
2. Install the latest version of node/npm
3. Follow the steps in `CONTRIBUTING.md` then install packages

### Environment

- OS: Mac 11.4
- Browser: Brave browser
- Browser Version: 1.35.100

### Did you check incognito mode?

- [ ] I have checked incognito mode

### Config

{"theme":"serika_dark","customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":30,"mode":"time","quoteLength":[1],"language":"english","fontSize":15,"freedomMode":false,"resultFilters":null,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false}

**Comment by Miodec** [comment]
Because some things break in latest version. Just use nvm and switch node versions with that.
