### ISSUE TITLE
API overhaul

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2428]
- [x] Make new frontend client
- [x] Change the API to be more RESTful
- [x] Convert frontend to use new client
- [x] After conversion is done test every endpoint to make sure everything works as expected
  - [x] Config
      - [x] GET `/configs`
      - [x] PATCH `/configs`
  - [x] Leaderboards
      - [x] GET `/leaderboards`
      - [x] GET `/leaderboards/rank`
  - [x] Preset
      - [x] GET `/presets`
      - [x] POST `/presets`
      - [x] PATCH `/presets`
      - [x] DELETE `/presets`
  - [x] PSA
      - [x]  GET `/psas`
  - [x] Quotes
      - [x] GET `/quotes`
      - [x] POST `/quotes`
      - [x] POST `/quotes/approve`
      - [x] POST `/quotes/reject`
      - [x] GET `/quotes/rating`
      - [x] POST `/quotes/rating`
      - [x] POST `/quotes/report`
  - [x] Result
      - [x] GET `/results`
      - [x] POST `/results`
      - [x] PATCH `/results/tags`
      - [x] DELETE `/results`
  - [x] User
      - [x] GET `/users`
      - [x] POST `/users/signup`
      - [x] GET `/users/checkName`
      - [x] DELETE `/users`
      - [x] PATCH `/users/name`
      - [x] PATCH `/users/leaderboardMemory`
      - [x] PATCH `/users/email`
      - [x] DELETE `/users/personalBests`
      - [x] GET `/users/tags`
      - [x] POST `/users/tags`
      - [x] PATCH `/users/tags`
      - [x] DELETE `/users/tags`
      - [x] DELETE `/users/tags/:tagId/personalBest`
      - [x] POST `/users/discord/link`
      - [x] POST `/users/discord/unlink`
- [x] Deploy

**Comment by Bruception** [comment]
I can work on this.

**Comment by Miodec** [comment]
@Bruception added some tasks to the description, feel free to add more

**Comment by Bruception** [comment]
Tested all endpoints locally. Everything seems to be functional. Need peer validation though.

**Comment by Miodec** [comment]
- [ ] After conversion is done test every endpoint to make sure everything works as expected
  - [ ] Config
      - [ ] GET `/configs`
      - [ ] PATCH `/configs`
  - [ ] Leaderboards
      - [ ] GET `/leaderboards`
      - [ ] GET `/leaderboards/rank`
  - [ ] Preset
      - [ ] GET `/presets`
      - [ ] POST `/presets`
      - [ ] PATCH `/presets`
      - [ ] DELETE `/presets`
  - [ ] PSA
      - [ ]  GET `/psas`
  - [ ] Quotes
      - [ ] GET `/quotes`
      - [ ] POST `/quotes`
      - [ ] POST `/quotes/approve`
      - [ ] POST `/quotes/reject`
      - [ ] GET `/quotes/rating`
      - [ ] POST `/quotes/rating`
      - [ ] POST `/quotes/report`
  - [ ] Result
      - [ ] GET `/results`
      - [ ] POST `/results`
      - [ ] PATCH `/results/tags`
      - [ ] DELETE `/results`
  - [ ] User
      - [ ] GET `/users`
      - [ ] POST `/users/signup`
      - [ ] GET `/users/checkName`
      - [ ] DELETE `/users`
      - [ ] PATCH `/users/name`
      - [ ] PATCH `/users/leaderboardMemory`
      - [ ] PATCH `/users/email`
      - [ ] DELETE `/users/personalBests`
      - [ ] GET `/users/tags`
      - [ ] POST `/users/tags`
      - [ ] PATCH `/users/tags`
      - [ ] DELETE `/users/tags`
      - [ ] DELETE `/users/tags/:tagId/personalBest`
      - [ ] POST `/users/discord/link`
      - [ ] POST `/users/discord/unlink`
