### ISSUE TITLE
Find out which values are causing object hashes to be different

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2433]
Currently the issue with object hashes is that different browsers can handle object values differently. The primary suspect is floats. Its possible that somewhere in the request process there is a rounding error, and the resulting server side hash of the result object is different to the client side hash. One possibility is to stringify every field before sending or hashing.

**Comment by paurana** [comment]
i'll take this

**Comment by Miodec** [comment]
> i'll take this

Did you find anything @paurana ?

**Comment by Ferotiq** [comment]
👻

**Comment by Miodec** [comment]
Rounding all the floats to 2 decimal places as well as rewriting how custom text values are stored seems to have fixed the issue. The biggest problem was the JSON does not have `NaN` and instead uses `null` - that's why the hashes ended up different.
