### ISSUE TITLE
Theme selector are duplicating on settings page

### ISSUE THREAD

**Issue by guijun13** [Miodec/monkeytype#2477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

On the settings page, theme section, when clicking to select a theme, all themes table is duplicated. Also, when clicking to favorite a theme, they are duplicated on top.

### Expected Behavior

When selecting a theme, do not duplicate the themes table.
When clicking to favorite a theme, show only 1 on the top of the 'theme' section.

### Steps To Reproduce

1. Go to "Settings"
2. Select the "Theme" section at the top of the page. Or just scroll down.
3. Select any theme on the themes table.

### Environment

- OS: Ubuntu 18.04.6 LTS
- Browser: Google Chrome
- Browser Version: 97.0.4692.71 (Official Build) 64-bits

### Anything else?

https://user-images.githubusercontent.com/48109548/153690665-bc0e24f0-ecff-4419-a6af-90ea0ac0a0e6.mp4

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Synertry** [comment]
I'm also having this issue in v1.14.
Getting two configs, the second one is empty.

- OS: Windows 11 21H2
- Browser: Google Chrome
- Browser Version: 101.0.4929.5 (Official Build) dev (64-bit)

Same results in icognito mode.

**Comment by Miodec** [comment]
> I'm also having this issue in v1.14. Getting two configs, the second one is empty.
> 
> * OS: Windows 11 21H2
> * Browser: Google Chrome
> * Browser Version: 101.0.4929.5 (Official Build) dev (64-bit)
> 
> Same results in icognito mode.

What do you mean by two configs?

**Comment by Synertry** [comment]
It was described in the original post at the end so I thought I should include it.
In dev tools > network tab, toggling randomize theme gives me two configs each:
![Monkeytype - Theme duplicating - double config](https://user-images.githubusercontent.com/60792595/158079783-c2fcca52-735c-454c-9f81-291d49d4e132.png)
