### ISSUE TITLE
Results in Leaderboard Cut Off

### ISSUE THREAD

**Issue by UnrealApex** [Miodec/monkeytype#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

The results in the leaderboard are cut off and don't display user names.

### Expected Behavior

Leaderboard would fully show the names of users.

### Steps To Reproduce

1. Click the leaderboard icon or type `View Leaderboards page` in the command line
2. See error

### Environment

- OS: Windows 10 Enterprise
- Browser: Firefox
- Browser Version: 97.0(64-bit)

### Anything else?

![image](https://user-images.githubusercontent.com/79121360/153736516-49572f10-ffe0-4f3e-b90b-5d38d202d4f7.png)

Note that this issue also occurs in Chrome.

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Is your browser zoom level set to like 300% ?

**Comment by UnrealApex** [comment]
Browser zoom is the default 100%, the system UI scaling(Windows) is the problem
**100% UI scaling**:
![image](https://user-images.githubusercontent.com/79121360/153778917-b0fc570f-7f86-4899-8341-dd868eddab1c.png)

**125% UI scaling(where some the leaderboard is janky)**:
![image](https://user-images.githubusercontent.com/79121360/153778930-3f427879-687c-4271-852a-c365937b9be3.png)

**Comment by karimk123** [comment]
I'm also having this issue and my browser zoom is 133% but shouldn't Monkeytype adapt to this ?

**Comment by UnrealApex** [comment]
I'm pretty sure Monkeytype's leaderboard can with media queries.

**Comment by Miodec** [comment]
What resolution are you using @UnrealApex ?

**Comment by UnrealApex** [comment]
`1366 x 768`

**Comment by UnrealApex** [comment]
Think it's fixed, I'll test it on there when I can. Thanks!
