### ISSUE TITLE
input lag when typing 

### ISSUE THREAD

**Issue by nightser727** [Miodec/monkeytype#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

there is an input latency when typing

### Environment

- OS: artix linux
- Kernel: zen
- Init: runit
- Browser: librewolf
- Browser Version: latest
- Search engine: searx

### Anything else?

https://user-images.githubusercontent.com/84193446/153821885-85df16fb-17a2-4961-a2d9-8a24009b547d.mp4

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Have you tried different browsers?

**Comment by nightser727** [comment]
Thanks

**Comment by nightser727** [comment]
> 

Yes i tried with firefox and it works

**Comment by CordasMC** [comment]
I'm having this problem as well. I'm able to temporarily fix the issue by switching themes, after re-opening the site when having closed it, however, it occurs again. 

MT: v25.16.0
Browser: Zen, 1.11.2b (Firefox 137.0.1) (aarch64)
Computer & OS: MacBook Air m2, 2022, macOS 15.3.2 (24D81)

Video of the issue: https://streamable.com/whlgib
