### ISSUE TITLE
Firebase Analytics Issue

### ISSUE THREAD

**Issue by KendallDoesCoding** [Miodec/monkeytype#2506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

Issue with feature of firebase.

### Expected Behavior

Issue with firebase anayltics

### Steps To Reproduce

Go to console

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: idk

### Anything else?

``
firebase-analytics.js:1 [2022-02-14T17:02:06.956Z]  @firebase/analytics: DOMException: Transaction timed out due to inactivity.
xe @ firebase-analytics.js:1
Fe.error @ firebase-analytics.js:1
(anonymous) @ firebase-analytics.js:1
```
2firebase-analytics.js:1 [
``
2022-02-14T17:02:06.957Z]  @firebase/analytics: DOMException: Transaction timed out due to inactivity.
xe @ firebase-analytics.js:1
Fe.error @ firebase-analytics.js:1
(anonymous) @ firebase-analytics.js:1
```

### Did you check incognito mode?

- [ ] I have checked incognito mode

**Comment by Miodec** [comment]
Are you using an adbocker?

**Comment by KendallDoesCoding** [comment]
> Are you using an adbocker?

Yes, ig that's the issue... Closing
