### ISSUE TITLE
Layout fluid invalid value

### ISSUE THREAD

**Issue by cursorweb** [Miodec/monkeytype#2557]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account information

{"theme":"8008","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#000000","#75b8ff","#1100ff","#c2f5ff","#89bef0","#ff4242","#ff0000","#da3333","#791717"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":false,"numbers":false,"words":25,"time":15,"mode":"words","quoteLength":[0],"language":"english","fontSize":"15","freedomMode":false,"difficulty":"master","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":true,"layout":"qwerty","funbox":"layoutfluid","confidenceMode":"off","indicateTypos":"off","timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"next","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":150,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"custom","minAccCustom":80,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAvg":false}

### Current Behavior

When typing in `qwerty dvorak` for `custom layoutfluid`, I am informed that this is an invalid value. This feature has worked for me before in the past, so maybe it's because there needs to be a minimum of 3 layouts?

### Expected Behavior

I'm expecting layoutfluid to allow 2 keyboard layouts

### Steps To Reproduce

1. `esc`
2. `custom layoutfluid`
3. `qwerty dvorak`

### Environment

- OS: Windows 11
- Browser: Firefox
- Browser Version: 97.0.1

**Comment by Ferotiq** [comment]
Layoutfluid was never meant to support two layouts, I'm pretty sure. The config validator was added recently and it will only accept 3 layouts for layoutfluid.
