### ISSUE TITLE
"Invalid Result Spacing" is bypassable by using retry button

### ISSUE THREAD

**Issue by Ferotiq** [Miodec/monkeytype#2559]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

If a result has been flagged for invalid result spacing, using the retry saving result button will bypass this and save the result anyways.

### Expected Behavior

If a result has been flagged for invalid result spacing, it should never be saved to the database.

### Steps To Reproduce

1. Finish an invalid test.
2. See "Error: Invalid Result Spacing"
3. Use the retry saving result button.

### Environment

- OS: Windows 11
- Browser: Chrome
- Browser Version: 98.0.4758.102

**Comment by Miodec** [comment]
Thats okay, invalid result spacing doesnt mean the test is invalid - it means the tests are being saved too often.
