### ISSUE TITLE
Incomplete test recorded as if it was completed

### ISSUE THREAD

**Issue by corbintuason-coding** [Miodec/monkeytype#2564]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account information

Account Name: ignisfox
```
{"theme":"nord","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":[1],"language":"english","fontSize":"15","freedomMode":false,"difficulty":"master","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAvg":false}
```

### Current Behavior

I was facing an issue where I couldn't login. No matter how many times I attempted to login, I was always prompted with the error: `Missing Account Data. Please Refresh`. 

### Steps To Reproduce

Not sure if this is even replicable, but this is _**exactly**_ what happened before I experienced this bug. 

> I was facing an issue where I couldn't login. No matter how many times I attempted to login, I was always prompted with the error: `Missing Account Data. Please Refresh`. 

- Refreshed The Website
- Attempted to Login Again
- The error  `Missing Account Data. Please Refresh` was still present
- At this point, I decided to just type even if I am not logged in. Even while logged out, I was still on MonkeyType's `master` mode.
- I made a mistake while typing, so the usual Test Failed because of difficulty popped out.
- At this point, I decided to try to login again just for the heck of it because I'm attempting to beat my 60 seconds record
- The error still popped out, so I opened the Console just to see if there are any leads as to why this is happening
- Right after I opened the console, my account was suddenly retrieved. Which was great, but then I found this bug. The previously failed typing test was **_suddenly_** recognized as a legitimately finished test! What's even worse is that I moved up in the leaderboard because of this _fake_ successful test 😢

Attached Screenshots for Reference:

> ![Monkey](https://user-images.githubusercontent.com/99730081/155143688-d67b031e-be8e-4463-a31b-a81a66da8042.PNG)
> ![record](https://user-images.githubusercontent.com/99730081/155143760-a611e455-c269-4469-bd56-c77a880c5160.PNG)
> ![wrong record](https://user-images.githubusercontent.com/99730081/155143831-75c5f5dd-edc3-4f55-a293-065a7cf09068.PNG)

### Environment

- OS: Windows
- Browser: Brave
- Browser Version: [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by Miodec** [comment]
So basically... a failed test while logged out got saved as legit after logging in?

**Comment by Miodec** [comment]
Thanks, thats a nasty bug. Ill try to fix your account by removing the score and reverting the pb and leaderboard.

**Comment by corbintuason-coding** [comment]
@Miodec please be careful on the revert since I have replaced my pb with a real successful test. Maybe just delete that incomplete record on my history instead? 

![careful](https://user-images.githubusercontent.com/99730081/155243337-f0851e49-b6c9-409d-b9cc-78c543b11940.PNG)

**Comment by corbintuason-coding** [comment]
![happening again](https://user-images.githubusercontent.com/99730081/155292472-cd9a0c93-5310-4d11-80f9-1fc51b570c84.PNG)
Hi @Miodec , this missing account data is happening again, even in incognito mode. Also happening on my macbook. Is this an account specific issue? hope this can be resolved asap

**Comment by Miodec** [comment]
> Hi @Miodec , this missing account data is happening again, even in incognito mode. Also happening on my macbook. Is this an account specific issue? hope this can be resolved asap

Thats just when the database daemon runs out of memory. Ill be looking into this today, talking with my server provider. Ill fix your account today (yesterday was a bit of a messy day)
