### ISSUE TITLE
The on button in the settings for blind mode is not visible

### ISSUE THREAD

**Issue by Aman1131145** [Miodec/monkeytype#2591]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account name

AmanMishra

### Current Behavior

There is no text showing "ON" on the button that turn on the blind mode in settings 

### Expected Behavior

There have to be a text showing "On" 

### Steps To Reproduce

Go to settings 
Then go to behaviour
Then go to blind mode

### Environment

- OS: Windows 11
- Browser: Brave
- Browser Version: Latest

**Comment by Miodec** [comment]
Intended, button is "blind"
