### ISSUE TITLE
Wrong category selected

### ISSUE THREAD

**Issue by Salama** [Miodec/monkeytype#2596]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Salama_

### Current Behavior

https://user-images.githubusercontent.com/20580796/155873614-d4b31387-a7af-4b3d-ae63-23797419f17f.mp4

### Expected Behavior

The category that I click should be selected

### Steps To Reproduce

1. Go to https://monkeytype.com/
2. Click the categories

### Environment

- OS: Artix Linux
- Browser: Firefox Developer Edition & Ungoogled Chromium
- Browser Version: Firefox Developer Edition: 98.0b6-1, Ungoogled Chromium: 98.0.4758.80-1

**Comment by CameronCT** [comment]
https://github.com/Miodec/monkeytype/pull/2593

Related to this, there is an approved PR but the actual PR is not merged into production yet. Will likely be when @Miodec wakes up.
