### ISSUE TITLE
Store already typed quotes to make sure they dont repeat

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2600]
- Store already typed quotes during the current session (reset this if language changes)
- When selecting a new quote, check if it was already typed. If yes, get another quote.
- Once all quotes are typed, reset the storage.

**Comment by Paolo-Cosentino** [comment]
May I look into this, I think there may be a simple way to solve this issue using the browsers local storage.

**Comment by Miodec** [comment]
> May I look into this, I think there may be a simple way to solve this issue using the browsers local storage.

No need to store it in local storage - in memory is fine.

**Comment by Bruception** [comment]
I’ll take this
