### ISSUE TITLE
Last word in the input history is 0 WPM

### ISSUE THREAD

**Issue by Ferotiq** [Miodec/monkeytype#2611]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Ferotiq

### Account config

{"theme":"vscode","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#1e1e1e","#007acc","#007acc","#646669","#007acc","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["vscode"],"showKeyTips":false,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":false,"numbers":false,"words":10,"time":30,"mode":"words","quoteLength":[-2],"language":"english","fontSize":"4","freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"underline","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"replace","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"overrideSync","fontFamily":"Cascadia_Code","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":true,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":150,"repeatedPace":true,"pageWidth":"150","chartAccuracy":false,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":420,"highlightMode":"word","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAvg":true}

### Current Behavior

The last word of the input history is 0 WPM.

### Expected Behavior

The last word of the input history should be whatever it was typed at.

### Steps To Reproduce

1. Go to monkeytype.com
2. Take a typing test
3. Turn on input history
4. Hover over the last word

### Environment

- OS: Windows 10
- Browser: Chrome
- Browser Version: 98.0.4758.102

### Anything else?

![image](https://user-images.githubusercontent.com/64989416/156246669-fb9fefb1-9ce5-4039-a3c8-781db17cbc02.png)

**Comment by KyleMcKell** [comment]
Interestingly, this only applies when the last word is spelt correctly.

See here: (last word was spelt incorrectly)

![Word history with incorrect last word](https://user-images.githubusercontent.com/46072760/156285831-cea27d06-7635-455d-9b44-30c707c02672.png)

**Comment by KyleMcKell** [comment]
This also happens with timed tests as well, it's not isolated to word count

![Timed Test 0wpm last word](https://user-images.githubusercontent.com/46072760/156288041-5750f5e0-0ddd-41b5-8dd9-924bdd648d14.png)
