### ISSUE TITLE
`event` keyword in `code csharp` language is mistakenly entered as `even`

### ISSUE THREAD

**Issue by AlFasGD** [Miodec/monkeytype#2672]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

One of the registered words for the language is `even`

### Expected Behavior

It should be `event`; `even` is not a valid C# keyword (as of C# 10, the current one)

### Steps To Reproduce

1. Select the `code csharp` language
2. Expect a test to include the `even` keyword, when the intended one should be `event`

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 99.0.4844.51 (Official Build) (64-bit)

### Anything else?

![image](https://user-images.githubusercontent.com/8298332/157700882-d116b577-8f59-429c-a198-decd284de9ac.png)

**Comment by Ferotiq** [comment]
You can make a simple pull request for this.

**Comment by AlFasGD** [comment]
Closed in #2673
