### ISSUE TITLE
Smoothing and toggle settings aren't saved

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#2706]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Smoothing and toggle settings in the account view are not saved
![image](https://user-images.githubusercontent.com/17170199/158368002-c1756573-6b28-450f-8e53-e3ebe6036589.png)

### Expected Behavior

They should be saved and backed up with the account

### Steps To Reproduce

1. Go to account
2. Change the smoothing and the toggle
3. Refresh the page/Do some tests

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 99.0.4844.51 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Smoothing setting isnt meant to be saved. I just tested and the accuracy and style settings are saving correctly. Keep in mind that there is a new batching timeout when saving configs. Please around a second after toggling the setting before refreshing the page.

**Comment by pingshunhuangalex** [comment]
Ok, why not tho
