### ISSUE TITLE
Smooth Caret Lags on LibreWolf

### ISSUE THREAD

**Issue by baralsoumyadeep** [Miodec/monkeytype#2712]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Helventer

### Current Behavior

I am using Librewolf browser on my arch linux os. This issue does not happen on any other browser other than librewolf. Switching browsers is not an option. 

**When ever I try to practice on Librewolf, the smooth caret feature does not work. I made sure the keep the smooth caret option to "on". But this has continued to annoy me.**

I have uninstalled and reinstalled the browser and made sure that I am on the latest release. 

If you don't know what LIbrewolf is: It is a fork of Firefox but less bloated.

https://user-images.githubusercontent.com/99474195/158616011-6d476f4d-32af-425a-8972-adf818fff20b.mp4

 

### Expected Behavior

The smooth caret feature should work. 

### Steps To Reproduce

1. Download the Librewolf browser from the instructions given on there official website - [https://librewolf.net/](https://librewolf.net/)
2. Go to [Monkeytype.com](monkeytype.com) on the browser.
3. Start typing after making sure the smooth caret feature option is set to "on".

### Environment

- OS: EndeavourOS Linux (Based on Arch LInux)
- Browser: Librewolf
- Browser Version: 98.0

**Comment by Ferotiq** [comment]
This is most likely not an issue with smooth caret. This is probably librewolf having some efficiency optimization that makes the site laggy. Edge’s “efficiency mode” does the same thing.

**Comment by Ferotiq** [comment]
Here’s a [reddit thread](https://www.reddit.com/r/LibreWolf/comments/oim01q/stutteringlag_in_typing_practice_sites/) I found that might have a fix

**Comment by baralsoumyadeep** [comment]
Thank You so much! Turning **Off** the **privacy.resistFingerprinting** in **about:config** totally resolved the issue for me.

https://user-images.githubusercontent.com/99474195/158626095-e6a38005-37ec-4502-a2ad-db7879a5d974.mp4

**Comment by Ferotiq** [comment]
Awesome! I might have to make Mio make an announcement for librewolf users.

**Comment by Ferotiq** [comment]
I've done a bit of research and it seems to be a Firefox feature, yet disabled by default. And maybe enabled by default on LibreWolf.

**Comment by baralsoumyadeep** [comment]
Yeah! I found that too. So I think i will keep it turned on when i am not using monkeytype.com and turn it off while practicing. Later, I guess I can make a script which will automate this process for me.
