### ISSUE TITLE
[Safari 13.1.2] TypeError: undefined is not a function (near '...m.addEventListener...')

### ISSUE THREAD

**Issue by BelKed** [Miodec/monkeytype#2730]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Whole page is just grey:

![Screen Shot 2022-03-18 at 15 28 56](https://user-images.githubusercontent.com/66956532/159022076-1beb6172-552f-4bc7-8d6a-4492ddbdaf9a.png)

With opened *Web Inspector*:

![Screen Shot 2022-03-18 at 15 30 04](https://user-images.githubusercontent.com/66956532/159023424-562cea90-9fd8-40bc-af07-40692ecb4f1e.png)

### Expected Behavior

There should be such a typing test on the website:

![Screen Shot 2022-03-18 at 15 45 05](https://user-images.githubusercontent.com/66956532/159024902-db02973b-1de7-4133-8cfc-9d81b63ea6a0.png)

### Steps To Reproduce

1. Go to https://monkeytype.com
2. See blank grey page
3. Open *Web Inspector*
4. See errors in console

### Environment

- **OS:** macOS High Sierra 10.13.6 (17G14042)
- **Browser:** Safari
- **Browser Version:** 13.1.2 (13609.3.5.1.5)

### Anything else?

You can see a screenshot of the console output below.

![Screen Shot 2022-03-18 at 15 30 04](https://user-images.githubusercontent.com/66956532/159024025-c1a59b45-4deb-40f4-ae3e-d54eecf7700b.png)

---

Looks like a problem with identifying a color theme...
However, it works on all other browsers (Firefox, Chrome, Edge, Tor) on the same computer.

Anyways, thanks for creating such an amazing typing website :)

**Comment by Miodec** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/13181393/159026164-22375666-0448-4d2a-ab76-376313714865.png">

Is this clickable? If it is can you show me the code that it leads to? It looks like something that is not supported in older Safari.

**Comment by BelKed** [comment]
Yes, it's clickable :D
Here you are:

![Screen Shot 2022-03-18 at 15 57 55](https://user-images.githubusercontent.com/66956532/159027193-d54a6628-aa92-4e7a-a434-437e9169485b.png)

Now I realize that after clicking, the row number and column have changed ...

**Comment by Miodec** [comment]
Alright, ive added a try catch in that area - maybe it helps. Please try again. If it doesn't work try clearing your cache from the Develop menu, or trying private mode.

**Comment by BelKed** [comment]
Amazing, thanks for the quick fix, it works now :)

![Screen Shot 2022-03-18 at 16 13 11](https://user-images.githubusercontent.com/66956532/159029837-f8e2c352-a08d-4b96-8f39-606cb1fee4fb.png)

**Comment by Miodec** [comment]
Could you also quickly test this for me:

What do you get when you paste `window.matchMedia?.("(prefers-color-scheme: dark)")?.addEventListener` into the Safari console? And then Chrome console?

**Comment by BelKed** [comment]
Sure thing 😉

Safari:
![Screen Shot 2022-03-18 at 16 19 39](https://user-images.githubusercontent.com/66956532/159031795-37a36bb9-9798-4519-b07d-24e7328608e3.png)

Chrome:
![Screen Shot 2022-03-18 at 16 22 31](https://user-images.githubusercontent.com/66956532/159031819-9e2f23f0-639e-465f-bd5f-aa6a853b48d4.png)

**Comment by Miodec** [comment]
Alright, thanks!

**Comment by BelKed** [comment]
It doesn't seem to be working now...
Did you really want to revert this fix in https://github.com/Miodec/monkeytype/commit/8845a8576a67768de846711b45e5075bedfa4520?
