### ISSUE TITLE
"Missing account data. Please refresh." when trying to log in

### ISSUE THREAD

**Issue by clompi104** [Miodec/monkeytype#2736]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

clompi

### Current Behavior

When trying to log in to my account, after a short pause, I am redirected to the /account page, not logged in, with the text "Missing account data. Please refresh." on the page. Error pop-ups saying:

- Missing account data. Please refresh.
- Failed to get user data: Could not connect to the database. It may be down. (user)

appear.

The issue persists on any browser as well as on entirely different computers which leads me to believe it's an issue with my account.

![after trying to log in](https://user-images.githubusercontent.com/60186277/159131399-b725e045-1bef-4cfe-945e-f587789940e3.png)

### Expected Behavior

I expect to be logged in to my account after entering my email and password and pressing the Sign In button on the login page.

### Steps To Reproduce

1. Go to the main page (monkeytype.com).
2. Click the account symbol (monkeytype.com/login).
3. Enter account details (email and password) in the login form.
3.5 (optional). Check the "Remember me" option. Problem persists whether or not it is toggled.
4. Click the "Sign In" button.

### Environment

- OS: Windows 10
- Browser: Mozilla Firefox with customized about:config
- Browser Version: 97.0.2 (64-bit)

**Comment by Miodec** [comment]
Sorry about that - the database service configuration got reset somehow. Everything should be all good now.

**Comment by clompi104** [comment]
Thank you very much!
