### ISSUE TITLE
Randomized text with three words is repeated infinitly

### ISSUE THREAD

**Issue by MaxiBerdy** [Miodec/monkeytype#2742]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

When using the custom mode, and using three words (for example a b and c), checking random to type these words in a random order, and setting a timer of, let's say 30 seconds, the website will give you an infinitly repeated pattern, such as "c b a c b a"...

### Expected Behavior

I believe that for any number of words as the input of the custom text, while the random option is checked, should always show a randomized order of words that should not repeat.
So with the words a b and c, the website could produce "a b c c b a c c b b a a c b" but should not produce "b a c b a c b a c b a c".

### Steps To Reproduce

1. Select custom on the top right of monkeytype
2. Click "change"
3. input three words separated by a space, for example : "a b c"
4. Check "Random"
5. Specify a time in the "Time" field
6. Press "ok"
7. There should be a loop of the three words repeated infinitly

### Environment

- OS: Windows 10
- Browser: Vivaldi
- Browser Version: 4.0.2312.33 (Stable channel) (64 bits)

### Anything else?

I am using three words for example to train my fingers on a single column, by entering a q w for my left pinky finger on a AZERTY layout, so this is not a random use case haha.
I haven't tried if this is the case with different number of words, I tried with like my whole home row and didn't have any issues !
I also tried with Firefox 98.0.1 (64 bits), I got the same results.

Other than that I'd like to say thank you for this awesome website, it helps me practice my touch typing as a fresh newcomer on the subject ! I especially love the design :)

**Comment by Ferotiq** [comment]
This is likely because monkeytype will never show you two words in a row.

**Comment by Miodec** [comment]
Yeah it will stop `X X` sequences but also `X Y X`. Easy fix.
