### ISSUE TITLE
Add -n't to english when punctuation is enabled

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2753]

**Comment by DenelDuck** [comment]
I could work on this, any more specifications?

**Comment by Miodec** [comment]
> I could work on this, any more specifications?

- If punctuation is enabled and the current language is one of the English ones, have a 50% chance of replacing for example `have` with `haven't`.
- Build a bank of possible 'pairs' (are - aren't).

Whole thing would be pretty similar to British English setting.

**Comment by DenelDuck** [comment]
I'm not that experienced so I just did what I thought looked right and I hope someone can take a look at it and give some feedback.
