### ISSUE TITLE
Swear word in English 10k

### ISSUE THREAD

**Issue by Topech** [Miodec/monkeytype#2761]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The language English 10k contains the word "shit".

### Expected Behavior

English 10k should not contain the word "shit". The language guidelines state "Do not include swear words".

### Steps To Reproduce

1. Go to settings.
2. in the behavior section, change the language to "english 10k".
3. Use the app as normal until you come across the swear word.

### Environment

- OS: MacOS Monterey 12.3
- Browser: Firefox
- Browser Version: 98.0.1 (64-bit)

### Anything else?

I am not concerned myself, but do respect the guidelines.

The evidence is in the image below, last sentence. The word is contained in `frontend/static/languages/english_10k.json`, but I am not sure if it is elsewhere in the codebase.

![image](https://user-images.githubusercontent.com/44491043/159830166-ce308c66-803b-401c-85ac-69619fe2a506.png)

**Comment by Topech** [comment]
I would be happy to remove the word from the `frontend/static/languages/english_10k.json` file, I am just not sure what to replace the word with to keep the list at 10k.

Could anyone point me in the direction to properly fixing this?

**Comment by Miodec** [comment]
Its not important to keep it exactly at 10k. You can just remove it.
