### ISSUE TITLE
Pipe delimiter and new line characters don't work together at all

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2772]

**Comment by Jazzinghen** [comment]
I have reproduced the bug by using a simple input for the custom text mode and enabled "Pipe delimiter":
```
a|b
a
b
c|d
```
This input generate the following test:
![image](https://user-images.githubusercontent.com/230921/160843380-6e504e6d-bdf3-49ea-9d7e-1a2c9a7ed322.png)
Where the `∨` seems to be indicating a "Newline character" (i.e. `<letter class="nlChar">`), or so I think it is.

The test resulting from this input should be:
```
a b
a
b
c d
```

**Comment by Jazzinghen** [comment]
Actually, the current behaviour is almost correct. It could generate tests like:
```
a d b ∨
a ∨
b ∨
c
```
or
```
d b ∨
a ∨
b ∨
c a
```
