### ISSUE TITLE
Remember Me box is ambiguous and should use symbols instead of just colors

### ISSUE THREAD

**Issue by Soundtoxin** [Miodec/monkeytype#2776]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

When I've been logged out (happens a lot for some reason, but let's not discuss that here) and have to log in I always struggle with whether the box is "ticked" or not due to lack of any symbol. I usually end up cycling through several themes in case any make it more obvious, but it all feels very much like a shot in the dark. This is very bad in terms of accessibility.

### Expected Behavior

I expect a little checkmark symbol or X or something when the box is set to "true" or "on".

### Steps To Reproduce

1) go to the login page
2) click the remember me box both ways
3) realize it's just changing between two colors that could really mean anything

### Environment

- OS: Guix System GNU/Linux
- Browser: qutebrowser
- Browser Version: qutebrowser v2.4.0

### Anything else?

The bug fixed in https://github.com/Miodec/monkeytype/issues/177 was actually an improvement in a sense when it wasn't fixed (although I never experienced this bug that I recall, and of course ideally you would not have two boxes)

I do mostly use my own custom theme but I can't tell with or without it which way the box is, and because I keep getting logged out I don't know if it's my own fault for clicking the box to the wrong color(?!) or a bug in the site.

**Comment by Miodec** [comment]
I meeean... i wouldn't say this is ambiguous
![image](https://user-images.githubusercontent.com/13181393/160285801-78841751-c91f-4866-aa8c-384a14a861d2.png)

How does it look like for you?

**Comment by Soundtoxin** [comment]
You may happen to know what the colors for that theme signify, but it's still ambiguous if you don't, and made much worse if you're color blind. (FYI, I am not at all color blind, and it's still a problem)

This scenario is a bit like curb ramps on sidewalks. Originally added for people with wheelchairs, but they end up making it easier for able-bodied people to get on/off the curb as well. People on bikes can smoothly change heights thanks to them, and it helps people pushing shopping carts as well. Maybe you don't think it's necessary to improve this, but it would be a major help to some people and would be unlikely to bother others, I think.

![2022-03-27-121718_grim](https://user-images.githubusercontent.com/3146494/160292856-94bd9d61-79af-455f-a145-199a89ff6ab9.png)

Here is how it looks with the custom theme I use, and how I usually see it initially, but I'd like to reiterate that I often cycle through several themes before logging in, just in case one of them makes it more obvious, but I can still never feel confident. Does the box start checked or unchecked? I'm not sure. I would feel so much better if I could ignore the colors regardless of the theme and focus on the presence or absence of some sort of symbol within the box.

There's already at least one case of symbol usage, on the Sign In button to the left side. I think something like that which contrasts with the box's current color could still fit in fine with the design. I just want to be able to click back and forth and really know for sure which way things are set.

**Comment by Miodec** [comment]
Alright, added a check icon
