### ISSUE TITLE
Trend Line dependent on Smoothing

### ISSUE THREAD

**Issue by HISEROD** [Miodec/monkeytype#2796]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

HISEROD

### Account config

{"theme":"shadow","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#000000","#a0a0a0","#c40000","#404040","#707070","#c40000","#730c0c","#c40000","#730c0c"],"favThemes":["stealth"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":false,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":25,"time":15,"mode":"quote","quoteLength":[0],"language":"english","fontSize":"125","freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"outline","paceCaretStyle":"default","flipTestColors":true,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"bar","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"uppercase","keymapLayout":"qwerty","fontFamily":"IBM_Plex_Sans","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"5","soundVolume":"0.5","startGraphsAtZero":false,"swapEscAndTab":false,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":false,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"on","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"https://blenderartists.org/uploads/default/original/4X/d/3/c/d3ccf07399c74d5ac3cb2817b9457cf3811a9be7.jpeg","customBackgroundSize":"cover","customBackgroundFilter":[0,1,0.7,0.2],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off"}

### Current Behavior

Just found a minor trend line bug that seems to be caused by the data smoothing feature. Notice the slight difference in the line's position when smoothing is set to 20.

### Expected Behavior

The line should stay in place regardless of smoothing.

### Steps To Reproduce

1. create a new tag for a clean graph
2. do a test typing slowly and another typing quickly
3. look at your graph for the new tag with no smoothing
4. change the smoothing and notice the trend line updates

### Environment

- OS: Windows 10
- Browser: Brave
- Browser Version: Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)

### Anything else?

![image](https://user-images.githubusercontent.com/94516882/161375778-4bd2083e-f25c-4c6b-9289-57052785d09f.png)
![image](https://user-images.githubusercontent.com/94516882/161375781-cf24f718-1e48-446f-bb9e-66a7e3362745.png)

**Comment by Miodec** [comment]
Thats fine by me.

Plus it would be hard to keep the line stationary because the trendline is just a plugin.
