### ISSUE TITLE
Can't sign in, firebase error

### ISSUE THREAD

**Issue by rowario** [Miodec/monkeytype#2798]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Rowario

### Current Behavior

![image](https://user-images.githubusercontent.com/14127958/161423932-b5ad65f3-d242-421b-8a72-a85523fdd11f.png)
![image](https://user-images.githubusercontent.com/14127958/161424038-3fcb247f-7f50-431a-aafd-854bc5bca702.png)

### Environment

- OS: Windows 11
- Browser: Chrome
- Browser Version:100.0.4896.60

### Anything else?

i guess firebase is now blocked in my city, i'm from Ukraine, Donetsk, and that might be the reason of that.

**Comment by Miodec** [comment]
Are any other google services blocked for you?

**Comment by rowario** [comment]
FIrebase, Google Cloud Platform, Google Pay.
Google itself works fine, I can auth via google account on other sites, i guess they are using something else than firebase.

**Comment by Miodec** [comment]
Whats the url of the request that gets the 403 error?

**Comment by Miodec** [comment]
Ok, made some changes. Try again in 15 minutes.

**Comment by rowario** [comment]
Nothing changed, the same url, and 403

**Comment by Miodec** [comment]
Whats in the response tab for both of those requests?

**Comment by rowario** [comment]
![image](https://user-images.githubusercontent.com/14127958/161793312-2f5e198e-eff4-43a7-8d6e-603f9560ba2d.png)
![image](https://user-images.githubusercontent.com/14127958/161793345-553f6f2c-1eae-4745-8add-baf6ec086919.png)

**Comment by Miodec** [comment]
What extensions do you have installed

**Comment by rowario** [comment]
![image](https://user-images.githubusercontent.com/14127958/161794919-9e19c957-84fc-4a7f-baa2-2ded5f5fbf45.png)

**Comment by rowario** [comment]
i guess any of firebase urls gonna answer with 403 for me 
this is the answer for https://firebase.google.com/
![image](https://user-images.githubusercontent.com/14127958/161795074-30e6d2dd-1e2b-4e2e-95b1-b3414587e2ca.png)

**Comment by rowario** [comment]
time for vpn :(
thanks for your time.

**Comment by roshaan005** [comment]
I had this error when I was connecting my app to firebase a while ago, every time I tried logging/signing in I got that exact same error, for some reason I still do not know how to fix that and unfortunately there is not much information as well as to how it can be fixed

**Comment by Syaw0** [comment]
i had the same issue , you must change your ip -_-
