### ISSUE TITLE
Keyboard emulation error Colemak dh iso on ISO keyboard

### ISSUE THREAD

**Issue by KarlRemarks** [Miodec/monkeytype#2800]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

KarlRemarks

### Current Behavior

I am unable to type the letter z while emualting colemak mod dh iso on a hardware-iso keyboard layout. I type "z" but it outputs "\\" as it would by default if there was no layout emulation. I even enabled the keyboard layout map to make sure I wasn't doing anything stupid, but the map puts z where it should be and the keyboard emulation still doesn't perform as it should.

### Expected Behavior

The letter z should be outputted.

### Steps To Reproduce

Set layout emulation to colemak mod dh iso
Use a iso-layout-hardware keyboard
Attempt to type the letter z. 

### Environment

- OS: Windows 11
- Browser: Chrome
- Browser Version: 100.0.4896.60

**Comment by Miodec** [comment]
Do you get Z if you press the key to the left of 1?

**Comment by KarlRemarks** [comment]
> Do you get Z if you press the key to the left of 1?

Why, yes I do! I'd tried most of the keyboard must have missed that one. How come this is the case?

**Comment by Miodec** [comment]
What system keyboard layout are you using?

**Comment by KarlRemarks** [comment]
> What system keyboard layout are you using?

QWERTY English UK primarily, but the same issue occurs on both Swedish and Greek.

**Comment by Miodec** [comment]
https://keycode.info/

What `event.code` do you get here when you press the key to the right of the left shift?

**Comment by KarlRemarks** [comment]
Correction: IntlBackslash

220

(I pressed control to copy and it changed the code, apologies)
