### ISSUE TITLE
Keymap next mode with turkish layouts

### ISSUE THREAD

**Issue by gkaply532** [Miodec/monkeytype#2828]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The keymap next mode doesn't highlight the correct key when using either turkish q or turkish f layout. Instead of highlighting `i` (lowercase dotted i), it highlights `ı` (lowercase dotless i).

### Expected Behavior

When typing `i` on a turkish layout, `i` should be highlighted.

### Steps To Reproduce

1. Set `Keymap mode > next`
2. Refresh the page for the keymap to appear
3. Set `Layout emulator > turkish q` (or `turkish f`...)
4. Set `Mode > custom`
5. `Change custom text`
6. Enter a single lowercase `i`
7. Click `ok`

### Environment

- OS: Windows 11
- Browser: Firefox
- Browser Version: 99.0 (64-bit)

### Anything else?

current behaviour on turkish q
![image](https://user-images.githubusercontent.com/48455693/162636802-f912e09c-3bc2-413e-8ac4-acdb374ffca1.png)
also on turkish f
![image](https://user-images.githubusercontent.com/48455693/162636816-485f31a9-deec-4071-8ebc-8a7ecf66f608.png)

**Comment by gkaply532** [comment]
while I don't have any experience with the monkeytype codebase, I think this happens because all uses of (that I found using github) `highlightKey` calls `.toUpperCase()`
https://github.com/Miodec/monkeytype/blob/fdf9517a5b29ae1026f14f430fcc9c9218ab741b/frontend/src/scripts/elements/keymap.ts#L7
for both letters, it returns uppercase `I`
```ts
"i".toUpperCase() // "I"
"ı".toUpperCase() // "I"
```
unless if the letter is already uppercase
```ts
"İ".toUpperCase() // "İ"
"I".toUpperCase() // "I"
```
this explains why this only happens for lowercase dotted `i`

**Comment by Ferotiq** [comment]
hmm, could be fixed by using `.toLocaleUpperCase()` instead. Can you try that?

**Comment by gkaply532** [comment]
I don't have a setup ready to test it. but I was more just wondering why is the letter being converted to uppercase
https://github.com/Miodec/monkeytype/blob/fdf9517a5b29ae1026f14f430fcc9c9218ab741b/frontend/src/scripts/elements/keymap.ts#L21
using devtools I found that `data-key` contains both upper and lowercase. maybe another layout requires it?
