### ISSUE TITLE
Wikipedia mode and brackets

### ISSUE THREAD

**Issue by 3coma3** [Miodec/monkeytype#2835]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

3coma3

### Account config

{"theme":"onedark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":0,"time":0,"mode":"time","quoteLength":[3],"language":"spanish","fontSize":"2","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"underline","paceCaretStyle":"outline","flipTestColors":false,"layout":"default","funbox":"wikipedia","confidenceMode":"off","indicateTypos":"below","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"letter","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"overrideSync","fontFamily":"Atkinson_Hyperlegible","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":true,"playSoundOnClick":"4","soundVolume":"1.0","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"on","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"both"}

### Current Behavior

When using Wikipedia mode, upon reaching a pair of [] brackets (which is very often due to Wikipedia footnotes/quotes), it's always an error to press space after the closing bracket. When using stopOnError modes, this also implies you cannot continue typing at all. Without stopOnError, you can just leave the "mistake".

### Expected Behavior

Pressing space after a closing bracket continues normal typing and is not an error.

### Steps To Reproduce

1. Enable Wikipedia mode
2. Go to practice with a Wikipedia article that has brackets

### Environment

- OS: Debian based
- Browser: Google Chrome
- Browser Version: Version 99.0.4844.84 (Official Build) (64-bit)

**Comment by 3coma3** [comment]
![image](https://user-images.githubusercontent.com/1572047/163224829-449e29de-c317-44bd-8b3c-5da3211ea747.png)
Actually not only space, but any other character (see this sequence of "])" - the closing parenthesis isn't typeable after entering the bracket.

**Comment by 3coma3** [comment]
@Miodec Thanks for replying, I'm testing now with another keyboard and the issue persists. I'll try with other browsers, and another keymap, as these are my main suspects for now.

**Comment by 3coma3** [comment]
Testing with FF 99.0.1 (64-bit) produces the same error, even in incógnito mode with a fresh session. The only settings changed were enable Wikipedia mode, change set to spanish 10k, and test duration to 100 words. The space after the closing bracket is registered as an error (it lets me continue since I haven't set stop on error in this test).

**Comment by Ferotiq** [comment]
what if you leave it on english, instead of spanish?

**Comment by 3coma3** [comment]
If I leave it on english:

1) Can't reproduce the issue anymore: any character that should be typed after a closing bracket is not counted as an error
2) It's much harder to come across brackets at all as Miodec mentioned (the Spanish Wiki somehow has lots of these)
3) Now there are a whole lot of other hard / impossible to type unicodes: the English Wiki abounds in phonetic transcriptions, original language translation (Hindi, Japanese, whatever)
4) I cannot practice my native language and its accents anymore (I do use English a lot btw, but hoped to practice Spanish as well as other languages I use with diacritics like Portuguese and German)

Haven't yet attempted Portuguese or German though, and for now I'm wondering why is this happening with Spanish and closing brackets but not with English

**Comment by 3coma3** [comment]
Hi @Miodec,  I should mention that the issue is actually easily reproducible, you just have to select a Spanish variant.

**Comment by Miodec** [comment]
> Hi @Miodec, I should mention that the issue is actually easily reproducible, you just have to select a Spanish variant.

Ill try that today.

**Comment by 3coma3** [comment]
> > Hi @Miodec, I should mention that the issue is actually easily reproducible, you just have to select a Spanish variant.
> 
> Ill try that today.

Thanks!

**Comment by Miodec** [comment]
Alright, pushed a change in dce8f59d2f199a9de7fe0ddf422d6b9a1bb28c2c to just remove the reference links. Give it a test now.

**Comment by 3coma3** [comment]
> Alright, pushed a change in [dce8f59](https://github.com/Miodec/monkeytype/commit/dce8f59d2f199a9de7fe0ddf422d6b9a1bb28c2c) to just remove the reference links. Give it a test now.

On a quick test I can confim the ref links are all but gone (did not even have to type, just refreshed tens of times and the wiki entries appear always without the brackets, whereas before it was a 80% chance they would appear. I will now conduct longer tests typing for a while, but it does look that his might do the trick!

I'll post a follow up after the typing test.

**Comment by Miodec** [comment]
Yeah, maybe the references had some invisible character. Ill keep looking.

**Comment by Miodec** [comment]
Try now

**Comment by 3coma3** [comment]
Yessssssssssssss It works perfect now! :partying_face: So it was actual garbage characters :)

Thanks so much for solving this issue Miodec, the Wiki mode on MT is the single most useful tool I found to practice typing, so I'm super grateful for this one.
