### ISSUE TITLE
"Failed to save config: Network Error" bug when the user logged in 

### ISSUE THREAD

**Issue by Mahmoud-Skafi** [Miodec/monkeytype#2841]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

MaDps

### Account config

{"theme":"dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":false,"numbers":false,"words":25,"time":60,"mode":"time","quoteLength":[1],"language":"english","fontSize":"15","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"underline","paceCaretStyle":"block","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off"}

### Current Behavior

when I try to log in the "Failed to save config: Network Error" error appears every time I try to log in, and everytime I open the website 

### Expected Behavior

When the user logs in import the user config correctly.

### Steps To Reproduce

1 - try to log in 
2- if the error doesn’t appear try to import the config that I post 

### Environment

- OS: macOS
- Browser: Google Chrome
- Browser Version: Version 100.0.4896.88 (Official Build) (arm64)

**Comment by Miodec** [comment]
I tried importing your config and it saves correctly for me. Are you still running into this issue?

**Comment by Mahmoud-Skafi** [comment]
> I tried importing your config and it saves correctly for me. Are you still running into this issue?

yes, I'm facing this problem for a month or two, it started when I can't log in to my account.

**Comment by Mahmoud-Skafi** [comment]
> When you open the leaderboards on the website does that work or does that also give you a network error?

No, just when I log in/ when I open the website while I'm logged in.

**Comment by Miodec** [comment]
I can try to clear your account config, see if that helps.

**Comment by Mahmoud-Skafi** [comment]
The same problem, I try to reset the local storage/session again, but nothing seems to work.

**Comment by Mahmoud-Skafi** [comment]
New Issue appear "Failed to get user data: Network Error (config)" the website logs me out after I log in and open the website again

**Comment by Miodec** [comment]
No, i mean i can try to reset your config in the database, if you want to try that.

**Comment by Mahmoud-Skafi** [comment]
Ok let's try that, I thought you already did that sorry

**Comment by Miodec** [comment]
Be sure to clear your local data aswell, and then try to login in 5 minutes.

**Comment by Mahmoud-Skafi** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/55147169/164467686-8708e386-d68c-41f5-ac19-e5a63c4576e8.png">

**Comment by Miodec** [comment]
Set the indicate typos setting to off and see if it saves then

**Comment by Mahmoud-Skafi** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/55147169/164468779-59f1b9e3-1940-4f57-bd7e-913ba56c23ec.png">

**Comment by Miodec** [comment]
Could you join the Discord server and ping me in the #bugs-and-support channel? This could be a bit easier in real time.
