### ISSUE TITLE
Banner does not extend across the full width of the screen on Windows

### ISSUE THREAD

**Issue by brianschnee** [Miodec/monkeytype#2875]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The top banner has a gap on the right side on each browser I've tested with Windows. It looks proper on my macOS device, extending the full width of the browser window

Windows(improper):

1. Firefox
![windows_firefox](https://user-images.githubusercontent.com/77141303/165028886-15f607db-78aa-4b02-abb1-d37724ff6855.jpg)

2. Brave
![windows_brave](https://user-images.githubusercontent.com/77141303/165028891-9351e4c7-ac56-4bda-b9a6-7fcb1f39a02f.jpg)

3. Chrome
![windows_chrome](https://user-images.githubusercontent.com/77141303/165029005-b9b896d4-1ef1-405f-89d6-912ec2d82afe.jpg)

macOS (proper):

1.
<img width="529" alt="macOS_no_gap" src="https://user-images.githubusercontent.com/77141303/165029006-50da7202-d3f0-4b41-afb5-18c319cb4b76.png">

.

### Expected Behavior

The banner should extend across the full width of the window for each device.

### Steps To Reproduce

1. Open up Chrome, Brave, Firefox on a windows device
2. Go to https://monketype.com
3. Look at the top right of the banner

4. Open up any browser on macOS
5. Go to https://monketype.com
6. The desired behavior should be proper here

### Environment

- OS: Windows 10
- Browser: Brave
- Browser Version: 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 100.0.4896.127 (Official Build) (64-bit)

- OS: Windows 10
- Browser: Mozilla Firefox
- Browser Version: 99.0.1 (64-bit)

- OS: macOS Monterey Version 12.3
- Browser: Mozilla Firefox
- Browser Version: 98.0.2 (64-bit)

**Comment by Miodec** [comment]
Looks like safari handles scroll bars differently.

Either way this is not a bug and is intended. This is there to make sure the content doesn't "jump" a small amount to the left when a scrollbar appears.
