### ISSUE TITLE
Not generating enough words

### ISSUE THREAD

**Issue by Coding-Kiwi** [Miodec/monkeytype#2876]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":50,"mode":"words","quoteLength":[1],"language":"german","fontSize":"15","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

when using language german and 50 words it sometimes only generates 9 or 10 words

### Expected Behavior

It should generate the configured 50 words

### Steps To Reproduce

1) switch to 50 words
2) switch to german
3) press f5 until bug occurs

### Environment

- OS: Windows 11
- Browser:
- Browser Version: 1.37.116 Chromium: 100.0.4896.127

### Anything else?

![image](https://user-images.githubusercontent.com/5007641/165032858-ba906235-d9d3-4a65-9286-cd3b171d8599.png)

**Comment by Coding-Kiwi** [comment]
![image](https://user-images.githubusercontent.com/5007641/165032927-38c38b47-eab0-4136-a3dc-3f77b986697f.png)
its also not possible to complete it this way

**Comment by Miodec** [comment]
Does it happen every time for you? I keep refreshing and it only happens 10% of the time for me. Maybe less.

**Comment by Miodec** [comment]
Found it, should be good now.

**Comment by Coding-Kiwi** [comment]
Yes, its fixed :)
