### ISSUE TITLE
When will mandarin to be supported

### ISSUE THREAD

**Issue by zhanglianyu0911** [Miodec/monkeytype#2886]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Steps To Reproduce

Search `Chinese`  or `Mandarin` during search a language

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by rizwanmustafa** [comment]
This is not a bug but a discussion. Please use the proper channels.
