### ISSUE TITLE
Focus words when cookie popup is closed

### ISSUE THREAD

**Issue by VRG7** [Miodec/monkeytype#2888]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

I don't have a monkeytype account.

### Current Behavior

I've encountered very weird bug that happens every time I open a new Firefox session. I go straight to Monkeytype and start typing in the words and I have noticed that I always get the first few words wrong. Sometimes It's only the first one, sometimes it' first three or two words. I thought It was weird and tried the exact same thing multiple times and typed them very SLOWLY and I know I didn't make any mistake and they came out wrong anyway.

### Expected Behavior

Open new firefox session. Go to Monkeytype. Start typing and expect the correct result of the first words, when you type them in perfectly correct.

### Steps To Reproduce

1. Open new firefox session
2. Go to monkeytype
3. start typing in the words

### Environment

- OS: Windows 11
- Browser: Firefox
- Browser Version: 99.0.1

**Comment by rizwanmustafa** [comment]
This bug is not reproducible. At least not for me. And how do you get the indication that the words are wrong. Do you get a error color or do you get a dotted underline in the input history at the end of the result. Also a video proof would be helpful.

**Comment by VRG7** [comment]
Yeah the words get red error color. I wouldn't mind If they were actually wrong, but I know that they are correct, because I have already tested it like 100 times. I think it might have something to do with my Firefox settings, because after closing Firefox session all my cache, cookies, history etc. deletes automatically, then I open another and and go straight to monkeytype and after accepting cookies the first word is always wrong. I could use some simple keylogger script to record my input and record the screen and show, that the bug is actually there.

**Comment by rizwanmustafa** [comment]
If you could try firefox in private mode?

**Comment by VRG7** [comment]
Video proof of the bug:

https://user-images.githubusercontent.com/95353326/165539463-862a53cd-2e36-4c9b-bcf5-772523e452f4.mp4

**Comment by VRG7** [comment]
> If you could try firefox in private mode?

This is happening in private mode.

**Comment by Miodec** [comment]
> Video proof of the bug:
> 
>  bug.mp4

I didn't see you click the words to focus them. Try opening the website, clicking the words (make sure the caret appears) and then type. You typed 4 characters but only 3 showed up as red. This tells me the first keypress was the one that focused the words and then you started actually typing.

**Comment by VRG7** [comment]
Yeah, It works perfectly now. My bad.

**Comment by Miodec** [comment]
> Yeah, It works perfectly now. My bad.

Looks like the auto focus was lost when I added cookie popup. Ill fix that.
