### ISSUE TITLE
Indicate Typos>Below Clips into certain letters on certain fonts, specifically Comfortaa

### ISSUE THREAD

**Issue by MaxACartwright** [Miodec/monkeytype#2894]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Arsun

### Account config

{"theme":"oblivion","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":false,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":false,"numbers":false,"words":50,"time":1800,"mode":"time","quoteLength":[1],"language":"english","fontSize":"4","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Lexend_Deca","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":false,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"max","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":true,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"letter"}

### Current Behavior

When "Indicate Typos" is set to below, the typos that are shown below the letters clip into each other.

### Expected Behavior

The typo letters are evenly spaced.

### Steps To Reproduce

1. Open Monkeytype
2. Set "Indicate Typos" To below
3. Use the "Comfortaa" font family
4. Make a few typos
5. See that they clip into each other

### Environment

- OS: Chrome OS
- Browser: Google Chrome
- Browser Version: Version 98.0.4758.107 (Official Build) (64-bit)

### Anything else?

This might not work on all fonts, I've just noticed that it only happens on the font family "Comfortaa".
This also might only work if typos are made frequently.
Only works on certain letters, at certain times.
Not only do they clip into each other, but they also might double-space (See below)
![image](https://user-images.githubusercontent.com/51039735/165611657-d575c750-4db9-4843-8ee0-65b4dab6eacd.png)
An example of what happens

![image](https://user-images.githubusercontent.com/51039735/165615146-4d5620f4-4732-40ea-8a4a-f053ad485ec2.png)
Double Spacing

![image](https://user-images.githubusercontent.com/51039735/165612064-166a24fb-5ac5-4213-a0f6-e29b977b5e6d.png)
What is supposed to happen

I understand the large number of issues that are received and that this might take a while.
Thanks!

**Comment by MaxACartwright** [comment]
Note: Tape mode also needs to be off.

**Comment by Miodec** [comment]
Looks like the indicators were not centered below the letters. This is fine on monospace fonts but on fonts like Comfortaa, letter widths can be very different.

Fix should be live later today.
