### ISSUE TITLE
Add Wikipedia Mode

### ISSUE THREAD

**Issue by madnight** [Miodec/monkeytype#306]
I would like to type Wikipedia articles. This mode should be like the quote mode, but instead of quotes it fetches the texts from Wikipedia.

As for the technical aspect, I could either imagine to do a live query to the Wiki API to obtain the texts or to use one of the text-only Wiki dumps.

**Comment by rolfvreijdenberger** [comment]
+1 and abstract it away so it would be possible to integrate more data providers. how-to-type.com has an affiliate program with amazon.com to type quotes.

**Comment by UnrealApex** [comment]
Might be possible accessing Wikipedia articles using the Wikipedia api or via web scraping. 
https://stackoverflow.com/questions/7185288/how-to-get-wikipedia-content-using-wikipedias-api
https://stackoverflow.com/questions/53127383/how-to-pull-data-from-wikipedia-page
https://www.freecodecamp.org/news/scraping-wikipedia-articles-with-python/

**Comment by Liquidmantis** [comment]
@Miodec I actually came to open an issue for the Amazon affiliate link.  Plenty of times doing quote typing exercises I'm intrigued by the quote, look at the source, and I'm surprised it's not a link.

**Comment by TheSmallTeaBoi** [comment]
Hey, any news on this? I think this is an awesome idea!

**Comment by Jonny-exe** [comment]
I would be happy to work on this.
