### ISSUE TITLE
Time typing showing different results.

### ISSUE THREAD

**Issue by mhd101** [Miodec/monkeytype#3611]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

mhd101

### Current Behavior

When going to https://monkeytype.com/account . I'm seeing different results in time typing. I've attached the screenshot.

### Environment

- OS: Window 11
- Browser: Google Chrome
- Browser Version: Version 105.0.5195.127 (Official Build) (64-bit)

### Anything else?

![1](https://user-images.githubusercontent.com/89081678/192776020-1c3d4927-50ba-469f-96c9-089468e3d660.jpg)
![2](https://user-images.githubusercontent.com/89081678/192776024-056cd422-36d3-4b45-8527-5429d8daaec4.jpg)

**Comment by nishu-murmu** [comment]
I suppose the second one is for the tests which have been completed.

**Comment by Miodec** [comment]
Second one is affected by filters, top one is the correct one if youre looking for your all time stats
