### ISSUE TITLE
make sure password managers work with the site

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#368]

**Comment by greenbigfrog** [comment]
The built in password manager in FF popped up asking if I want to save the login, but bitwarden did not.

**Comment by krmbzds** [comment]
I cannot make auto-fill work with Bitwarden.
It fills up the registration form and leaves the login form empty.

**Comment by krmbzds** [comment]
@Miodec, please [check this resource](https://web.dev/sign-in-form-best-practices/#current-password) to make it compatible with password managers.

Quoting the relevant section:
> Use `autocomplete="current-password"` and `id="current-password"` for the password input in a sign-in form, or the input for the user's old password in a change-password form. This tells the browser that you want it to use the current password that it has stored for the site.
> For a sign-up form:
```html
<input type="password" autocomplete="new-password" id="new-password" …>
```
> For sign-in:
```html
<input type="password" autocomplete="current-password" id="current-password" …>
```

**Comment by Miodec** [comment]
Followed the rules, pushed an update.

**Comment by krmbzds** [comment]
I checked the forms and they conform with the conventions, great! Bitwarden still fails to auto-fill the login form so I filed an [auto-fill failure report](https://forms.gle/yYVQkepxxLKZ3kR6A). I guess it's on [Bitwarden](https://github.com/bitwarden/browser/issues/1621) now. Either way, I think this was productive, thanks for the quick fix. :slightly_smiling_face:

**Comment by whoibrar** [comment]
Thanks for opening an issue, I was so confused as to where the issue was!

**Comment by pc00per** [comment]
> @Miodec, please [check this resource](https://web.dev/sign-in-form-best-practices/#current-password) to make it compatible with password managers.
> 
> Quoting the relevant section:
> 
> > Use `autocomplete="current-password"` and `id="current-password"` for the password input in a sign-in form, or the input for the user's old password in a change-password form. This tells the browser that you want it to use the current password that it has stored for the site.
> > For a sign-up form:
> 
> ```
> <input type="password" autocomplete="new-password" id="new-password" …>
> ```
> 
> > For sign-in:
> 
> ```
> <input type="password" autocomplete="current-password" id="current-password" …>
> ```

I don't understand any of this mate. How exactly can I fix bitwarden autofill issue? Can you explain step by step ?

**Comment by krmbzds** [comment]
@pc00per Bitwarden has to fix their own broken autofill mechanism -- nothing you can do at the moment.
