### ISSUE TITLE
Copy and paste settings as JSON

### ISSUE THREAD

**Issue by LeSirH** [Miodec/monkeytype#382]
There could be a "Copy JSON" button to copy all the current settings of a user. If someone were to ask "What are your settings? I want to use them.", users can paste in their settings JSON to rather than having to share multiple screenshots. If the JSON is invalid, the site can display: "An error occurred while saving settings: Invalid JSON configuration".

**Comment by dmartin-tech** [comment]
Working on an implementation now

**Comment by dmartin-tech** [comment]
Should it be a single button (like the old theme share) or two (import & export)?
