### ISSUE TITLE
refreshing the page -> leads to double refresh happening

### ISSUE THREAD

**Issue by callmeberzerker** [Miodec/monkeytype#419]
Press CTRL + R or F5 and you will see the test initializing twice.. if you start typing in the interim period the test will be failed (if you have difficulty set as master)

**Comment by Miodec** [comment]
Double refresh should only happen if your local config is different to your db config. Should only happen once because the db config is then applied to the local one. Also, if the test is already started - the db config will not be applied and not restart the test.

**Comment by callmeberzerker** [comment]
@Miodec it seems the problem is that CTRL + R or F5 blows away any local config and leads to double refresh... using the app s "Restart test" or "Next test" buttons doesn't lead to a double refresh.

**Comment by Miodec** [comment]
Do you have any extensions that could be blocking cookies or something?

**Comment by callmeberzerker** [comment]
Nope, just tested it out in both Microsoft Edge (latest - Version 86.0.622.38 (Official build) (64-bit)
) and Chrome (latest - Version 86.0.4240.75 (Official Build) (64-bit))

Refreshing the page (F5 / CTRL + R, once logged in) leads to a test that is shown briefly (1 sec) and then refresh happening and initializing a new test...

**Comment by Fasani** [comment]
It's a timing issue, so you have 2 different word databases I guess. You render the guest words db then the login flow with firebase completes and then you replace the guest db with my personalised words db?

You could keep the word wrapper hidden or with a loading state until after the login happens and on success/fail of user login, you could unhide the word wrapper, something like that would fix this.

**Comment by Fasani** [comment]
I was experiencing this earlier today but now I am not seeing it and I do not think any code was merged regarding the topic so it might be a hard one to track down.

**Comment by Miodec** [comment]
Do you think you could get a screen recording?

**Comment by callmeberzerker** [comment]
Just tested it and the issue is still present. :)

**Comment by Miodec** [comment]
Im guessing it doesnt happen when you refresh the page without being logged in

**Comment by callmeberzerker** [comment]
![monkeytype](https://user-images.githubusercontent.com/1324069/96905468-c5243100-1498-11eb-8f31-2ab93f124318.gif)

Here it is using MacOS and latest Chrome. This issue is exactly the same also on my Windows PC (and latest Chrome/Edge/Firefox).

First 2x times i reload using CMD + R shortcut... the third time you see me press the refresh browser button. See all the swaps in the test happening.

I didn't upload a video before because I think this happens to all logged in users and should be straight-forward to reproduce.

**Comment by Fasani** [comment]
@callmeberzerker I would argue it's not so easy to reproduce. I was having the same repeating behavior for a few weeks but the last 5 days or so it has not happened once for me.

**Comment by callmeberzerker** [comment]
@Fasani check if you are logged in. It seems the domain is changed and you might have been logged out - in that mode, you can not reproduce it.

**Comment by Fasani** [comment]
I am logged in, I check my stats often.

**Comment by Miodec** [comment]
Okay boys, in the latest update i added some console logs to identify whats going on, because the recording tells me its definitely the db config. Make sure to clear your cache to get the latest file, and check the console if you get a double refresh. Let me know if you get any logs about the config

**Comment by callmeberzerker** [comment]
Just tested it, the bug is still present here are the logs:

```
getting language json
account.js:12 ..config is different: manual != undefined
```

Pretty sure the config shouldn't be different on page refresh right?

**Comment by Miodec** [comment]
@callmeberzerker Alright, i pushed a change. Give it a hard refresh to clear cache, and try again. It should properly save the config now. I think before it was having issues saving the DB config properly, so it was in this comparison loop

**Comment by Miodec** [comment]
I've also made some general optimizations to minimize the double refresh. Test it and let me know!

**Comment by callmeberzerker** [comment]
@Miodec ok, I think I narrowed the bug. It only happens when choosing mode `master`. If I select any other mode -> then refreshing the page, doesn't lead to double init of the test.

**Comment by Miodec** [comment]
Even after the recent changes its still double refreshing?

**Comment by callmeberzerker** [comment]
now this is strange -> after choosing `normal` and then back to `master` -> it doesn't happen anymore. :\

**Comment by Miodec** [comment]
I think its the config sync changes doing work, and properly saving this time

**Comment by callmeberzerker** [comment]
cool beans, I don't think I can reproduce it anymore so I will close it :)

thx a lot

**Comment by Miodec** [comment]
Nice! Sorry it took a while :)
