### ISSUE TITLE
Compromised Password Message on Chrome

### ISSUE THREAD

**Issue by Fasani** [Miodec/monkeytype#429]
The compromised password message on chrome..... it was a little tricky to understand what the message was about until I then saw the message and understood why.

Contacting chrome will not solve this issue. The issue does not appear for me until I use the password reset form.

The issue is that I use a password on `firebaseapp.com` to reset and I then use the same password again the `monkeytype.com` domain to login. This issue will not be fixed by chrome, you need to host the forgot password form on the `monkeytype.com` domain and then the issue will go away.

**Comment by Miodec** [comment]
I've asked around in the Firebase discord and they believe that this would not fix the issue

**Comment by Fasani** [comment]
Well they are likely misunderstanding your issue or completely clueless. 😃

**Comment by Miodec** [comment]
Closing for now as this shouldnt affect new users
