### ISSUE TITLE
United States-International keyboard single quote not supported

### ISSUE THREAD

**Issue by GeorgesMainville** [Miodec/monkeytype#430]
Since the motion to write a single quote on a United States-International keyboard layout is the combination of two key one after the other like this ( [' "] + [SPACE] ) the caret don't register the symbol and simply go to the end of the word like it does when you hit space.

How to Reproduce:
1. In windows 10 go to Settings -> Time & Language -> Language -> Options of a preferred language -> Add a keyboard -> United States-International
2. Select the language as the current one (Windows + Space)
3. Go to https://monkeytype.com/
4. Try to do a quote typing test that include a single quote in it ( ' ).

Expected result:
![image](https://user-images.githubusercontent.com/26386976/96349001-beea1b00-107a-11eb-93df-ea7d8fd1e985.png)

Actual result:
![image](https://user-images.githubusercontent.com/26386976/96349207-fefdcd80-107b-11eb-9ef4-760bed495283.png)

**Comment by Miodec** [comment]
Sounds like a deadkey - those are not supported at this moment I'm afraid.
