### ISSUE TITLE
Ability to delete own scores

### ISSUE THREAD

**Issue by Jeremiidesu** [Miodec/monkeytype#440]
Not too long ago I had fun with a 2 word run, and now I'm stuck with an unrealistic for me 220wpm top speed. Therefore I would love to be able to delete scores such as these in order to restore a more reasonable top speed.

**Comment by Miodec** [comment]
You can use advanced filters to filter out custom tests, or you can use tag those results and then filter out the tag.

**Comment by Jeremiidesu** [comment]
I wish I could delete the score, but you're the boss

**Comment by Miodec** [comment]
Sorry, but IMO it can lead to handpicking results.

**Comment by r3tex** [comment]
I wish I could delete scores. 
My son is enjoying learning how to type and I messed up his PB caret by typing on his account.

**Comment by asherweintraub** [comment]
I'm with the others here, there are plenty of other ways to handpick results. My friends have used my account and set high PB's that I'm nowhere near.

Maybe a one-delete per day limit or something along those lines?

**Comment by Aarc-Noa** [comment]
I think the best compromise, should this ever exist, is not have the user themselves delete the score, but rather have the deletion request be handled by whoever hosts the system to minimize score handpicking – my reason may not be valid but these two look much more legitimate to me
