### ISSUE TITLE
Scatter plot without connecting dots

### ISSUE THREAD

**Issue by gonzalofrancoceballos** [Miodec/monkeytype#441]
When the user has done a large amount of tests, the chart showing historical results becomes too noisy and hard to read. It would be nice to have the option to remove the lines that connect the dots

**Comment by Miodec** [comment]
I mean, the noise will become very bad if you view a lot of modes at once (where the wpm difference will be large). I feel like most of the time we only view one mode at once right? (for example using the 'current settings' button)

**Comment by gonzalofrancoceballos** [comment]
Here is a screenshot of my stats for 15-sec tests:

[<img width="901" alt="image" src="https://user-images.githubusercontent.com/36130174/96479520-5eeda300-1239-11eb-9c5f-5f2b844cffde.png">](url)

I think even for longer tests, will also emerge over time, as people practice more and more
