### ISSUE TITLE
Tab key not working on results page after a test is complete

### ISSUE THREAD

**Issue by gs1293** [Miodec/monkeytype#445]
Earlier tab key worked everywhere to restart the test.
Now it has stopped working at the results page after a test is complete.
Now either have to reload the page or click on the keyboard symbol to restart the test.

**Comment by dhalley** [comment]
The quick tab mode seems to be working in google chrome but not in safari, for me at least.

**Comment by Miodec** [comment]
This should be fixed already. If not, clear your cache

**Comment by gs1293** [comment]
👍 Thanks, fixed after clearing the cache for google-chrome.
