### ISSUE TITLE
Remove more fancy typography

### ISSUE THREAD

**Issue by DreymaR** [Miodec/monkeytype#446]
I tested the "Remove Fancy Typography" option of a custom text. On the upside, seems it can take a whole book text – yay. But it only replaced the “” curly quotes for me, not the «» guillemets nor the en dash (–) although it did replace the em dash (—). It also had no affect on accented letters; not sure if it should.

**Comment by Miodec** [comment]
Accented letters shouldn't be affected by this. What should the guillemets be replaced with? `>>`?

**Comment by DreymaR** [comment]
Either just double or single quotes for «»/‹›, but I've also seen them replaced with <<>>/<> which is more clunky but visually more similar. Personally, I'd prefer just straight quotes.

Will you fix the en dash too? Technically, both en and em dashes should be replaced with -- (at least in my opinion).

For the plebs, you probably should remove at least the most common accents as well. They'll stumble and fall, the poor things. I'd do the major six (äáàãâ) at least. Probably not necessary to involve ạảᶏǎąăåāȧ, hehe... (Oh, and the ellipsis too, do that!)
