### ISSUE TITLE
Make statistics of most commonly misstyped characters, character cominations /words

### ISSUE THREAD

**Issue by mrkvicka22** [Miodec/monkeytype#448]
Statistics for each character. 

- accuracy for each character individually

- confidence/consistency for each character

- what character do you most commonly type instead of this one

- I am sure there is plenty more like these.

**Comment by Miodec** [comment]
Duplicate of #44

**Comment by mrkvicka22** [comment]
> 
> 
> Duplicate of #44

I read that one and did not consider it to be a duplicate :D
