### ISSUE TITLE
Problem typing ^ and _ in special mode

### ISSUE THREAD

**Issue by 17steen** [Miodec/monkeytype#450]
In the special characters gamemode of the funbox, I noticed that typing the undescore caused to skip the word instead of typing the character.

Most likely reason why it does this : on my layout, the underscore symbol is located on the spacebar when I press right alt.

I also encounter this problem when pressing space to type the character ^ which is located on a dead key.

**Comment by Miodec** [comment]
The ^ will be an issue because dead keys are not supported at the moment. As for the _ located on the space, when you press space (which sends _), what keycode do you get on this website: https://keycode.info/

**Comment by 17steen** [comment]
AltGraph (18) followed by Space (32)
![image](https://user-images.githubusercontent.com/43650869/97309172-f79ba880-1861-11eb-9094-57996741007e.png)

**Comment by Miodec** [comment]
So _ is also a dead key?

**Comment by Miodec** [comment]
Nevermind, i think i understand. I need to switch everything over to `event.key`, and this should fix android aswell

**Comment by Miodec** [comment]
Well, it didnt fix android at all, but maybe it will fix your issue. Try now. Make sure to clear your cache

**Comment by 17steen** [comment]
![image](https://user-images.githubusercontent.com/43650869/97358714-f1c2b900-189b-11eb-817e-d5db29b88184.png)
I think you’re taking the wrong variable xD

**Comment by 17steen** [comment]
this also broke ê and î (^ Dead key) in French tests, making it skip the word :
![image](https://user-images.githubusercontent.com/43650869/97360006-e7092380-189d-11eb-8334-dd194a123c66.png)

**Comment by Miodec** [comment]
Alright, fixed altgraph and dead appearing in text. Try again

**Comment by 17steen** [comment]
Everything seems to be working fine !

**Comment by DreymaR** [comment]
I tried it using EPKL on Windows. Special characters work fine whether the underlying Windows layout has a dead key on a key or not.
