### ISSUE TITLE
PB cursor jumping around when typing <Space> or <Backspace>

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#453]
Not sure if it's intended but if I type <Space> or <Backspace> when the PB cursor is turned on, it kinda jumps around trying to do something which is quite annoying... Hope you know what I meant. Thanks.

**Comment by Miodec** [comment]
Not a bug. This is happening because if you make a mistake the pace caret shows you where you would have to be to achieve the desired speed.
