### ISSUE TITLE
Ideas for improved keyboard only navigation

### ISSUE THREAD

**Issue by jeffalexander** [Miodec/monkeytype#456]
Love this tool! I have been using it to practice Colemak Mod-DHm.

I try to minimize use of the mouse when possible. I love that this tool includes the 'esc hud'. The following are some small spots where I had to reach for my mouse.

- The esc HUD does substring search matching but I found myself trying searches that could make sense but don't match.
  - 'type' shows no results because the menu item is "view typing page"... so need 'typ' or 'typing'.
  - **perhaps support search aliases?**
     - 'type' -> "view typing page"
     - 'begin test' -> "view typing page"
     - 'start test' -> "view typing page"
     - this could just be me learning the right word to search for... but I wish what I type into the hud could be more nemonic/command like.
- from most pages 'tab' will get you to the next element, which after a test will let you press 'tab then enter' to start a new test. You can also shift tab to navigate to the header icons but **pressing enter does not select the highlighted icon**.
  - also perhaps **add some title and alt text attributes** to these navigation elements which give hints as to which hud terms to use?
- While the 'esc hud' is open, **could tab move the selection to the next item** in the list? and shift tab move to previous?
  - ex: esc then 'view' then tab then tab then tab then enter would view settings page.
  - ex: esc then 'typ' then tab then enter would start a new test.
  - note: up/down arrows do work here already.
- Allow full screen mode from keyboard. On my MacBook, 'command+esc' in Chrome will enter full screen but this does not currently work on monkeytype. Also maybe add a 'fullscreen' hud command?

Thanks again for such a great tool with simple but powerful features!

**Comment by Miodec** [comment]
- [ ] Command line command aliases
- [ ] Command line tab and shift tab to navigate suggestions
- [ ] Toggle fullscreen command


As for the title and alt attributes - what will they help with?

**Comment by jeffalexander** [comment]
I think the title/alt text on the navigation icons could potentially help users learn the "domain language" of the tool.

Though I think making the nav menu icons activate on keyboard enter would be more useful than the alt text suggestion if we are setting priority.

**Comment by Miodec** [comment]
Added aliases, should be live.
