### ISSUE TITLE
No words loading in Microsoft Edge: script.js:14 Uncaught (in promise) ReferenceError: getLanguage is not defined

### ISSUE THREAD

**Issue by darrenangle** [Miodec/monkeytype#460]
Body of the test completely missing: 

<img width="784" alt="Screen Shot 2020-10-23 at 4 19 40 PM" src="https://user-images.githubusercontent.com/3577932/97055041-90bd7d00-154b-11eb-8d69-8c4dab6f3ea6.png">

With this error in the console: 

<img width="854" alt="Screen Shot 2020-10-23 at 4 20 09 PM" src="https://user-images.githubusercontent.com/3577932/97055077-a0d55c80-154b-11eb-82da-81775d5d36bf.png">

Breaks on the `await getLanguage` call here:
<img width="320" alt="Screen Shot 2020-10-23 at 4 20 37 PM" src="https://user-images.githubusercontent.com/3577932/97055103-b185d280-154b-11eb-991b-1d0d023ee546.png">

This is in Microsoft Edge with strict mode: on. It's possible your getlanguage function is affected by blocking the google ad syndication script. Edge does this automatically in strict mode. 

<img width="879" alt="Screen Shot 2020-10-23 at 4 22 58 PM" src="https://user-images.githubusercontent.com/3577932/97055235-0590b700-154c-11eb-8409-ca53e582bf12.png">

**Comment by Miodec** [comment]
Clear cache and try again - it should work
