### ISSUE TITLE
zen mode

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#468]

**Comment by szmarczak** [comment]
Is this kind of like a Zen mode?

**Comment by Miodec** [comment]
What do you mean by zen?

**Comment by szmarczak** [comment]
endless mode

**Comment by Miodec** [comment]
Yeap, pretty much

**Comment by TheeKevin** [comment]
wait doesn't this already exist?

**Comment by Jack92829** [comment]
I'll have a crack at this one

**Comment by jeffalexander** [comment]
Could / should zen mode go full screen or is that personal preference?

**Comment by szmarczak** [comment]
I'd say personal preference. Anybody can just press F11 to go fullscreen.

**Comment by Jack92829** [comment]
Yeah I think that's more of a personal preference thing, although do you think you guys would prefer a new timer/word count for zen mode? Because I feel like the massive counters don't feel to 'zen'. I'll probably make some new ones and see how they look anyway but just wondering what you guys think.

**Comment by jeffalexander** [comment]
Cool question. What would a zen timer be like? Rather than digital and functional, perhaps something calm and simple and not-visually-jarring. Like lines or dots on a progress bar that fade in or out slowly?

**Comment by szmarczak** [comment]
I'd say let's make the WPM counter take last 15s into count. Endless sentences.

**Comment by Jack92829** [comment]
> Cool question. What would a zen timer be like? Rather than digital and functional, perhaps something calm and simple and not-visually-jarring. Like lines or dots on a progress bar that fade in or out slowly?

Yeah that's kind of the aim, just something that's a bit more calm and less noticeable

**Comment by Cosmeeeen** [comment]
Playing around just thought it would be cool if it would be an endless instant death mode. Tracking how many words/for how long have you been typing without making a mistake. 
It can have 3 difficulties: 

1. Easy, the game ends if you fall below a certain set wpm 
2. Medium, the game ends if you fall below a certain set wpm, or submit a wrong word 
3. Hard, the game ends if you fall below a certain set wpm, or press a wrong key 

Just an idea, didn't know if I should start a new issue or post it here, as I thought it's kind of related and didn't want to crowd the issues.

**Comment by Miodec** [comment]
Zen mode is planned to just behave like notepad, with the added ability to shift+enter to finish the 'test' to check your wpm.

**Comment by TheeKevin** [comment]
Wait so that means you can type whatever you want into it? Would you have the ability to copy and paste what you type in it?
