### ISSUE TITLE
Delimiter Problem in Bengali Language

### ISSUE THREAD

**Issue by mm-crj** [Miodec/monkeytype#4696]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

mmcrjx

### Current Behavior

In the Bangla language, the sentence delimiter is '।' however '.' shows up in the text. I think this is just an issue of the input text, a simple regex should fix this. Eg s%/./।/gc

### Expected Behavior

When I open up to type the sentenses are delimited by . instead of ।

### Steps To Reproduce
1. Open [Monkeytype.com](https://monkeytype.com/)
2. Change typing language to Bangla
3. Turn on punctuation

### Environment

- OS: ubuntu 22.04
- Browser: firefox
- Browser Version: 117.0.1 (64-bit)

**Comment by Miodec** [comment]
Please provide steps to reproduce this issue

**Comment by Miodec** [comment]
> I updated the steps to reproduce, the numbers are also in English if you open that. Should I open another issue?

You can comment here
