### ISSUE TITLE
monkeytype not working on chromium

### ISSUE THREAD

**Issue by Eddy-Arch** [Miodec/monkeytype#473]
on specifically ungoogled chromium, ver 86.0.4240.80
![image](https://user-images.githubusercontent.com/58888419/97143669-c640b100-176b-11eb-9ce2-531d51f5e480.png)

**Comment by Eddy-Arch** [comment]
no text is being rendered.
the platform is gentoo linux k

**Comment by someotherotherguy** [comment]
Have you tried clearing cache/hard refreshing (i.e. ctrl + shift + r)?

**Comment by Miodec** [comment]
Clearing cache will work. Recent language change made it so no words will be generated if old script files are cached.
