### ISSUE TITLE
Rename Colemak DH to DHk due to recent update

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#476]
Thanks to the recent update, Colemak DHm is now the default layout for all keyboard types while the previous recommended staggered layout is now an alternative layout marked as `DHk`.

In short:
```
DHk = DH
DH = DHm
```

![image](https://user-images.githubusercontent.com/17170199/97171334-684eb080-17e1-11eb-9202-f30d728a4433.png)

In Monkey Type's case, we should rename the 2 options to:
```
colemak dh(m)        colemak dhk
```

**Comment by Miodec** [comment]
So, `dh` should be renamed to `dhk` ?

**Comment by pingshunhuangalex** [comment]
Yes, and the 2 options need to be swapped cuz `dhm` is now the default one.

You can also rename `dhm` to `dh` or `dh(m)` to add a bit more clarity. Your choice tho...

**Comment by Miodec** [comment]
Aight, will be live soon

**Comment by DreymaR** [comment]
Actually, I'd consider just dropping the DHk or marking it (old variant) or something. This is confusing enough to the newcomer as it is. It's far more important to get the Angle mod options right than to offer historical variants.
