### ISSUE TITLE
Delete Account and Update Email options

### ISSUE THREAD

**Issue by caburum** [Miodec/monkeytype#484]
Have a way to remove account or change username/email.

**Comment by rockingrohit9639** [comment]
Is anyone working on this issue or I can work on this issue?

**Comment by Miodec** [comment]
Updating email is already live on the website. Account deletion is very annoying to do in Firebase, and is already an option in the soon to be merged in mongo rewrite.

**Comment by rockingrohit9639** [comment]
> Updating email is already live on the website. Account deletion is very annoying to do in Firebase, and is already an option in the soon to be merged in mongo rewrite.

Okay, Thanks for your reply 😃

**Comment by Miodec** [comment]
Both finally in.

**Comment by rockingrohit9639** [comment]
> Both finally in.

Awesome
