### ISSUE TITLE
Custom mode rewrites your overall high score; possible improvement request

### ISSUE THREAD

**Issue by Juli4nMitch3ll** [Miodec/monkeytype#489]
I was messing around and set my custom to "a a a a a a a a" to see what I could get, I was unaware this overwrote your profile's high score. I feel custom text shouldn't change your profile's high score, as it can be easily manipulated to be made stupidly-high in 10 seconds. I understand this isn't really a bug but I'm annoyed that my stupid self now can't see my actual high score xD.

Thank you for reading this! Love monkey type btw! 😄

**Comment by Miodec** [comment]
You can easily filter out custom test results with the advanced / current settings filters on the account page. That way you can avoid viewing those high wpm results

**Comment by Juli4nMitch3ll** [comment]
Thank you so much!
