### ISSUE TITLE
Refactor Cloud Functions 

### ISSUE THREAD

**Issue by CharlieADavies** [Miodec/monkeytype#493]
Right now, the source code in places is a bet messy; for example `functions/index.js` is >2000 LOC with massive chunks that have been commented out. Splitting it up into a few separate more focused files would make that part of the project much more approachable. 

I'm willing to do the work for the first step of splitting it up into some more approachable files on the functions side of things.

**Comment by Miodec** [comment]
Sounds like a good idea!

**Comment by kalyantm** [comment]
@CharlieADavies @Miodec Anyone working on this? I would be happy to pick it up :smile:

**Comment by CharlieADavies** [comment]
I am working on this slowly. It'll be a few more days till I have anything much though.
________________________________

**Comment by Miodec** [comment]
No longer using cloud functions.
