### ISSUE TITLE
Something went wrong: ReferenceError: can't access lexical declaration 'visibleTableLines' before initialization

### ISSUE THREAD

**Issue by GioSDA** [Miodec/monkeytype#494]
Can't access typing test and can't see any profile statistics. 
![somethingwentwrong](https://user-images.githubusercontent.com/37423957/97523018-652cff00-195e-11eb-8af4-ba733ae130a5.PNG)

Problem is fixed upon deleting cookies.

**Comment by Miodec** [comment]
You just had old files cached. Won't happen again if you fixed it
