### ISSUE TITLE
Show top keymap row for some layouts that use them (for example one handed layouts)

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#496]
I've been using Monkeytype to learn keyboard layouts with using the keymap to see where the new keys are. However, the keymap on Monkeytype only shows the first three layers of keys when many keyboard layouts on Monkeytype change all four layers of them (the top row that usually contains numbers). Could you add an option to turn on and off the top layer?

**Comment by Miodec** [comment]
Added a field to each layout that says if the top row should be shown

**Comment by TheeKevin** [comment]
thanks :)
