### ISSUE TITLE
A new keyboard layout called OETA

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#497]
There's only two one handed keyboard layouts on Monkey type. One if you consider switching keys around for the other hand not a different keyboard layout. So could you add in a new one handed keyboard layout called OETA? 

The original one is shown in this video

https://www.youtube.com/watch?v=wKW0igiby2g

You can find the newest/most modified keyboard layout at exactly 46 seconds in this video

https://www.youtube.com/watch?v=4p226qoBuLo

So if you can add both keyboard layouts then maybe the first one could be called OETA and the second one OETAv2?

**Comment by DreymaR** [comment]
Y.A.K.L.  ¯\_(ツ)_/¯

**Comment by TheeKevin** [comment]
What's the meaning of Y.A.K.L?

**Comment by pingshunhuangalex** [comment]
![image](https://user-images.githubusercontent.com/17170199/97767788-9a119f80-1b72-11eb-9ae9-b352e8df9acc.png)

**Comment by TheeKevin** [comment]
at least 15 is better than 14 right? Who cares if there's 10 one handed keyboard layouts? Then anyone can choose the one they like the best

**Comment by pingshunhuangalex** [comment]
I'm all for it mate, just answering your question above.
That's how the keeb community keeps thriving, so keep those good suggestions coming.

**Comment by TheeKevin** [comment]
ayy yeah you too man

you got suggestions on how to make monkeytype better?

**Comment by Miodec** [comment]
Currently the problem is we can't change the location of backspace, shift and control like that to support OETA

**Comment by TheeKevin** [comment]
Oh I don't mind that. I really only want OETA for the keyboard layout. For all the tool keys you mentioned I don't require them to be in the exact spot that the creator has them (as the creator has the keyboard layout for general purpose use but I only want it for typing). I can have them in the usual spots on a regular keyboard layout.

**Comment by Miodec** [comment]
What about numbers? The first column? There is a lot of blank keys on that layout.

**Comment by TheeKevin** [comment]
@Miodec about numbers if you were to look at the newest keyboard layout version you'd see a key called "num layer" in which it toggles the usual number layer (it replaces the keys on the top layer to become numbers) on and off. As for the blank keys I wouldn't know what to do with them. If you can't recreate the "num layer" key I'll ask the creator where to put the numbers on those blank keys.

**Comment by TheeKevin** [comment]
Okay I'm gonna close this issue because it seems like your not going to do this any time soon. I can understand that because the things that the OETA keyboard layout demands (function keys in different places and a new num key) are a lot just for a keyboard layout that not many people are even going to use.
