### ISSUE TITLE
Add hover text to graph in test records

### ISSUE THREAD

**Issue by Marco-Pagani** [Miodec/monkeytype#506]
The behavior of the graph icon in your test history is slightly different from the other two icons in the info section. The language and mode icons show info on hover and do nothing on click:

![Example of first icon](https://i.ibb.co/BsnqqS1/image.png)

Meanwhile the speed graph does nothing on hover but shows the graph on click. It would be helpful to make clearer to users what this icon represents by adding some hover text, say, **_click to view graph_** or simply _**view graph**_.

I'm happy to implement this myself, I would however like some input on what the text should be to remain consistent.

**Comment by Miodec** [comment]
Yeah `View graph` sounds good.
