### ISSUE TITLE
Dvorak one handed is incorrect (either the layout or the keymap)

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#507]
The bottom of row of Dvorak one hand is different from the keymap that is showed it's slightly shifted to the left because one letter is missing on the bottom left of it.

**Comment by Miodec** [comment]
Hard refresh and try again, i made some changes to it recently

**Comment by TheeKevin** [comment]
@Miodec thanks so much for adding my suggestion in! Quick question. Are you going to add in the toggle feature for the top row of the keymap? I'm sure that some people will think it'll be too cluttered and wouldn't matter as many keyboard layouts don't change the top row (dvorak, colemak, and qwerty are some examples)
