### ISSUE TITLE
Site Update/Force refresh clears test mode and configs

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#508]
I always use a `time 60` mode. However recently, either after a site update or a force refresh, my test mode will always fall back to `word 50` mode somehow. Not sure if it's expected...

**Comment by Miodec** [comment]
Shouldn't happen - it should default to your last selected mode. Is it consistent?

**Comment by pingshunhuangalex** [comment]
It's been happening quite a lot recently. Sometimes when the initial loading is too slow and I started typing (before setting is fetched?) This could also happen. Haven't found a clear pattern yet

**Comment by Miodec** [comment]
So when the page initially loads it will load the local config and then when the user signs in the account config is downloaded, compared and applied (if different). Db config will not be applied if the local config changed before db config was loaded.

Getting some kind of pattern would be great, because currently i cant reproduce this

**Comment by pingshunhuangalex** [comment]
Just ran into the bug again without hard refresh (probably no site update either?) Will keep looking for clues but the bug is definitely there

**Comment by Miodec** [comment]
How many settings are cleared? All of them? Some of them?

**Comment by pingshunhuangalex** [comment]
The synced setting seems to be alright, only the test mode and config like `time 60` for example

**Comment by pingshunhuangalex** [comment]
I saw the whole process just now. It tends to happen after I leave the site for a while and come back.

On load, the test mode is actually right, and then I can see the site fetching my data with the spinning wheel and it somehow changes the test mode to `word 50` as if it's saved somewhere. Still don't know the reason for it just yet

**Comment by Miodec** [comment]
The delayed loading is your account config being loaded from the database. If the account config is different to your local config that is applied.

**Comment by pingshunhuangalex** [comment]
I understand, which could mean either some outdated/ghost is applying user's account only intermittently OR my account is somehow uploading/overwriting a test mode config I don't use from time to time

**Comment by Miodec** [comment]
Youre not the only one, and i it happened to me too just now. Its very weird

**Comment by pingshunhuangalex** [comment]
Haven't seen it again since the update. Feel free to close this if you feel confident. Thanks.
