### ISSUE TITLE
Funbox: Random letters

### ISSUE THREAD

**Issue by Orcomp** [Miodec/monkeytype#510]
A funbox option, which could be useful to memorize a keyboard layout, is random letters and spaces. 

Bonus option: users can specify the pool of characters to include, alpha, uppercase, numeric, ponctuation, custom etc...

**Comment by TheeKevin** [comment]
I believe that this option already exists. The funbox called "gibberish" does what you want with random letters and spaces. As for the bonus option you could use the custom option and spam a bunch of letters and punctuation in it and turn on the "random" option.

**Comment by Orcomp** [comment]
@TheeKevin that works perfectly thanks. (Some how I didn't mentally associate "gibberish" with "random"... go figure)
