### ISSUE TITLE
I can't tell what's happening here but I'm sure something's wrong.

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#511]
I'm sure that this has something to do with the way Monkeytype calculates wpm and accuracy with anything below half of 1% gets automatically rounded to 0 but still. This doesn't seem right because he still got over 1% accuracy.

https://www.youtube.com/watch?v=onoDAeNiReY

This one is just something I don't know

https://www.youtube.com/watch?v=mDyNXmotbjU

(of course he could've went into inspect and changed the coding around but I don't know if that's the case here)

**Comment by Miodec** [comment]
Im not sure what you mean. Everything seems as it should be. In the first video he didn't press a single correct character so its 0.

As for the second you will always get infinite for 1 letter tests.

**Comment by TheeKevin** [comment]
@Miodec Ah I see. In hindsight I see now where my error in thinking was. In the first one I didn't know the theme so I couldn't tell if he was typing incorrectly or not. In the second I didn't realize that having infinite wpm exists on Monkey type with one letter tests. Well thank you for informing me on this :)
