### ISSUE TITLE
Small issues and small ideas

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#529]
- The "on" for Blind Mode is invisible (don't know if this is on purpose)
- Make quotes have varying levels of difficulty (such as harder words and more punctuation or easier words and less punctuation) and have a feature where you can choose your own difficulty of quote. (I know that generally long quotes are harder but there aren't really "easy" long quotes)
- A feature where the user can see all the quotes and can choose which ones they want to type
- Maybe let the user suggest/add quotes for more variety 
- Minimum Accuracy feature (same way as minimum wpm) for people that think expert is too easy but master is too hard
- Master Mode acts exactly like Expert Mode sometimes

(if you need video verifying some of these issues then I can provide them)

**Comment by Miodec** [comment]
- No 'on' for blind mode is intentional
- Im not really sure how I would grade quotes based on difficulty as its really subjective.
- Possibly in the future
- Adding quotes is somewhere in the plans, but I'm getting side tracked with other stuff - its not super important.
- Seems too similar to expert and master but could add it.
- Im not sure what that means exactly.

**Comment by TheeKevin** [comment]
- Okay that's understandable 
- Maybe you could grade quotes based on an algorithm? (for example words that don't get used often and are long are considered harder)
- I'm glad you considered it
- I'm glad you considered it and I understand if you need to work on bugs/multiplayer over this small idea
- I think this is somewhat a good idea for people who can easily see their mistakes whenever they make them but they can't be using Master Mode due to it being way too hard so if they want a goal of something like 98% accuracy then it could be a good trainer
- What I mean by this is that for me Master Mode isn't failing me immediately when I make a mistake and instead only fails me whenever I hit space on a mistake (exactly like how expert mode acts) and whenever I make a mistake on "time" mode it just freezes

(as always if you can't reproduce the last issue I can send you a video)

**Comment by Miodec** [comment]
If you find this master mode issue and get it repeatedly open a new bug request. As for the update logs going back only so much I think its just a limitation of the github API. If you want to view all the changes you can see them in the release history on the github page.
