### ISSUE TITLE
Replay text from history

### ISSUE THREAD

**Issue by ivanjermakov** [Miodec/monkeytype#532]
Option in the text history list to replay it

**Comment by TheeKevin** [comment]
I believe that you can do this by hitting "repeat test" unless you mean something else.

**Comment by Miodec** [comment]
The second button will repeat the test with the same text.

**Comment by ivanjermakov** [comment]
I mean replay from account tab text history, not after the text completion.
![image](https://user-images.githubusercontent.com/26609879/98297442-73fe5c00-1fc5-11eb-9e39-3e2f47875717.png)

**Comment by Miodec** [comment]
The problem with that is that i would need to store the words history for each result, and that would introduce a lot of extra data. That plus the amount of users and results completed daily I'm just afraid of the cost implications of this.

**Comment by ivanjermakov** [comment]
What if you just load this text (quote 2469 for example) skipping the "text complete" screen. It won't require storing anything, but will give the ability to replay text from history.

**Comment by Miodec** [comment]
Well, this would only work for quote mode though.

**Comment by ivanjermakov** [comment]
Yes, there is history only for quotes
