### ISSUE TITLE
Can I submit the font I like to Monkeytype?

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#538]
I have my own choice of font which I use for my daily coding. Just wondering if monkeytype is happy to add it for me?

**Comment by Miodec** [comment]
We only add google fonts at the moment just because its very easy to do so

**Comment by pingshunhuangalex** [comment]
Feel free to close the ticket if it won't be addressed soon. It's just a `good to have` to me.

**Comment by Miodec** [comment]
Well, what font is it?

**Comment by pingshunhuangalex** [comment]
`Tsentsiu Mono HG` v1.059, probably too difficult to find a valid online source nowadays
