### ISSUE TITLE
Language dependent punctuation

### ISSUE THREAD

**Issue by ThinkerXT** [Miodec/monkeytype#539]
In Spanish there are upside down exclamation mark ¡ and question mark ¿ as well
In Arabic there are inverted question mark ؟ and comma ، and semicolon ؛ but never ? and , and ;
So let's make the automatic punctuation dependent on the language.
I also suggest adding the semicolon ; to the English punctuation.

**Comment by ZER0-X** [comment]
> In Arabic there are inverted question mark ؟ and comma ، and semicolon ؛ but never ? and , and ;

Also in programming languages there is some punctuation not used extensively in spoken languages, like: `<`, `>`, `/`, `\`, `|`, `*`, `~`, `^`, `$`, `#`, `=`, `+`, `&`.

**Comment by Miodec** [comment]
Added in 9fe5d76745e0d6e2e79bc7c215757ead129d578f
