### ISSUE TITLE
Double refresh on initial rendering is coming back again

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#542]
If I enter the site right now (1.5.7), I can notice a quick test refresh after things are initialised.

**Comment by Miodec** [comment]
I think there was an issue where one of the settings was not loading properly. Try now and tell me if it happens again.

**Comment by pingshunhuangalex** [comment]
All good now. Thanks

**Comment by pingshunhuangalex** [comment]
The issue comes back starting from 1.5.7 and it's still there in 1.5.8

**Comment by pingshunhuangalex** [comment]
Gone after hard refresh (this hard refresh thing after every update starts to get annoying...)
