### ISSUE TITLE
CSS not loading for the privacy policy

### ISSUE THREAD

**Issue by cursorweb** [Miodec/monkeytype#560]
Browser: Edge (Chromium)
Operating System: Windows
Cookies: None (inPrivate window and when logged in)
***
https://monkeytype.com/privacy-policy does not appear to have any styling other than the CSS variables, making it harder to read.
![image](https://user-images.githubusercontent.com/29520825/98577789-15193b00-2282-11eb-9857-9f719fae8a8b.png)

**Comment by Miodec** [comment]
Fixed, will be live on next deployment.

**Comment by pingshunhuangalex** [comment]
@Miodec clicking on the logo in policy page doesn't take you back to the homepage. Actually, there's no way to go back in that page using element on the page. No big deal tho.
