### ISSUE TITLE
replay of the test you just did for improvement and seeing what you did wrong

### ISSUE THREAD

**Issue by krosis2706** [Miodec/monkeytype#564]

**Comment by Miodec** [comment]
Maybe in the future if the replay data doesn't take up too much space.

**Comment by angularorbit** [comment]
> Maybe in the future if the replay data doesn't take up too much space.

TBH, you may as well discard the replay later on. I don't think the RAM this minimalist website takes will be impacted by timestamps of a few hundred clicks.

Also consider adding an option to export it as a gif or asciinema. Not sure how that could be accomplished.

**Comment by MysteriousLog6** [comment]
Well can it be a replay of our keystrokes?

**Comment by lukew3** [comment]
#1125 closes

**Comment by MysteriousLog6** [comment]
true
