### ISSUE TITLE
Letter training mode

### ISSUE THREAD

**Issue by jadkhoury** [Miodec/monkeytype#572]
Would be great to have letter training mode. 
For example, I'm always mistype the letter X so I'd like to train on this letter in particular. 
Could be implemented for the languages available with 1k and 10k words dictionaries, by selecting the subset of words containing the letter to train, and then running everything normally on this .

**Comment by Miodec** [comment]
Might take a while for this to be added since its not super high priority. But for now you can use this site https://gfruit.github.io/typing/words-filter.html to generate a word list with your desired letters (and other cool parameters). You can then just paste in that word list into the custom mode.

You can also press the practise missed words button after the test is over.

**Comment by jadkhoury** [comment]
Thanks for the reply ! Will try your suggestion.

**Comment by TheeKevin** [comment]
This could be added with in #44 because you could make a letter training mode out of the list of most mistyped letters and such.

**Comment by jadkhoury** [comment]
I thought about using mistyped words, but the problem is you rarely encounter a Z (never if you stay in English 200), so the huge list of mistyped words would only contain 1 or 2 words with Z, and training on that list would not really make you train on the letter Z that much.

**Comment by jadkhoury** [comment]
When it comes to functionality, the word filter linked by Miodec is exatcly what I had in mind.

**Comment by TheeKevin** [comment]
@jadkhoury Ah I see. Well if you've already gotten what you wanted should you close this issue?

**Comment by kevinzhao07** [comment]
Can try to implement something like this!

**Comment by Miodec** [comment]
@kevinzhao07 This is already available through custom mode and words filter.

**Comment by kittydoor** [comment]
Although this is technically possible with external tools, the discoverability of it is quite low for a new user unless they come upon this issue. Perhaps it's better to reopen this issue with the caveat "will not implement" "prs welcome"?
