### ISSUE TITLE
Dev training mode / language 

### ISSUE THREAD

**Issue by jadkhoury** [Miodec/monkeytype#573]
Could be implemented as an additional language / dictionary that mixes 
- usual English words
- common code words (main, struct, double, int, float4x4, switch ...)
- common code characters (& | ( ) {} [] ; '' "" _ - + = ` )

I know that there are some websites where you can train at typing actual code but it's not really as fun and engaging as MonkeyType.

**Comment by Miodec** [comment]
Duplicate of #535
