### ISSUE TITLE
Impossible to create an account on local dev

### ISSUE THREAD

**Issue by Marco-Pagani** [Miodec/monkeytype#577]
Following the steps in `CONTRIBUTING.md` allows you to build the site locally, however it is not possible to create an account as there is no local firestore db. When starting up your local copy the following error occurs:
```
...
[1] !  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
[1] !  functions: The Firebase Authentication emulator is not running, so calls to Firebase Authentication will affect production.
...
```

 It would be helpful to add instructions to create this so that the account page can be accessed locally.

**Comment by Miodec** [comment]
Try going to the firebase console https://console.firebase.google.com , on the left select firestore, and initialise it.

**Comment by Miodec** [comment]
DId you manage to get it working?

**Comment by Miodec** [comment]
Closing for now. Let me know if its still an issue.
