### ISSUE TITLE
Refactoring dependencies to modern practices

### ISSUE THREAD

**Issue by Marco-Pagani** [Miodec/monkeytype#579]
This may be better treated as part of #495 so just let me know if so.

As part of refactoring the frontend code I believe it would be helpful to switch from static js files to npm, that way dependencies can stay updated and be centrally managed and easily understood.

As part of this I would also like to switch from moment.js to [date-fns](https://date-fns.org/). Moment is no longer being actively developed and is considered legacy, and it also a very heavy library for the few things it's used for. Chart.js is removing moment as of V3 but currently allows you to replace it via plugins, so I can do that as well as replace moment in the frontend code.

I think this along with the other refactoring will go a long way to making the project more maintainable and easier to approach for new users.

**Comment by Marco-Pagani** [comment]
I can handle this myself, so if you think it makes sense feel free to assign me

**Comment by typerqeo** [comment]
Any updates here @Marco-Pagani?

**Comment by Marco-Pagani** [comment]
Sorry, had some other projects to attend to this week. The bulk of the work is done here, but now that #582 is merged I need to rebase and make sure my commits behave before I make a pr. Will update soon
