### ISSUE TITLE
Fix lint warnings

### ISSUE THREAD

**Issue by typerqeo** [Miodec/monkeytype#583]
This probably deserves its own issue. You can see the list of warnings when you run `npm run build`.

**Comment by Miodec** [comment]
![image](https://user-images.githubusercontent.com/13181393/110581220-04aa9b80-8162-11eb-8ec9-ccfe4d26afb9.png)

Decided to chart all the interlocked dependencies to better understand where to start. Still don't know where to start, But ill definitely get there.
