### ISSUE TITLE
Won't load on 3 separate browsers

### ISSUE THREAD

**Issue by calrobertlee** [Miodec/monkeytype#596]
First time trying out monkeytype but the webpage will not load on any of my browsers:
- Chrome
- Brave
- Safari

I turned off all my browser extensions

I am using a Mac Mini 2018 on Catalina 10.15.5

Would love to check out this website but I can't even see it!

**Comment by Q-gabe** [comment]
Hi, I can confirm this as well. Stack trace looks points at the cookie being malformed.

<img width="553" alt="Screenshot 2020-11-18 at 12 36 40 AM" src="https://user-images.githubusercontent.com/41467676/99418662-3939e380-2936-11eb-979c-7abcd397705c.png">

**Comment by Miodec** [comment]
Clear cache, should be good now. Sorry about that

**Comment by calrobertlee** [comment]
Thanks! Works now
