### ISSUE TITLE
Possible issue with inconsistent caret position when hide extra letters enabled

### ISSUE THREAD

**Issue by someotherotherguy** [Miodec/monkeytype#597]
I noticed that the position of the caret can be misleading when using the delete key to go back to a previous word with extra letters enabled. Take for example this situation with extra letters not enabled:
![IMG_1954](https://user-images.githubusercontent.com/25231791/99460613-0287ad00-28e5-11eb-803d-688bdcbd4fd4.jpeg)
Here, I have just typed the extra letter 'k' so the caret is positioned directly at the end of the word. If I don't correct the answer and instead press space, it looks like this:
![IMG_1953](https://user-images.githubusercontent.com/25231791/99460407-a91f7e00-28e4-11eb-8304-194e5d6809d2.jpeg)
The cursor is clearly positioned right before the letter 'b' in 'brown', so when I press backspace the caret goes to right back to being after the second 'k' in the mistyped word and it looks exactly the same as the first image:
![IMG_1954](https://user-images.githubusercontent.com/25231791/99460613-0287ad00-28e5-11eb-803d-688bdcbd4fd4.jpeg)
This all makes sense: the caret is first at the end of 'quickk', then after pressing space it is at the beginning of 'brown', then deleting the space returns to the initial situation.

However, if hide extra letters is enabled, the final situation is actually different from the first. Here is the same exact series of actions with hide extra letters enabled:
![IMG_1955](https://user-images.githubusercontent.com/25231791/99461198-30b9bc80-28e6-11eb-88bd-7933252f849d.jpeg)
![IMG_1957](https://user-images.githubusercontent.com/25231791/99461237-4b8c3100-28e6-11eb-970e-2cd0aa955e2d.jpeg)
![IMG_1959](https://user-images.githubusercontent.com/25231791/99461288-63fc4b80-28e6-11eb-9a4e-608c88de0213.jpeg)
In the final image, when backspace is pressed, the caret does not return to the right of the mistyped word 'quickk' like in the first image even though the space has been deleted. The logical positions of the caret in both are identical (as with the first and last situation without hide extra letters enabled above), but the visual position is different. This leads to situations where the user may believe the caret is at the beginning of a word, when it is in fact at the end the previous word which has one or more extra letters at the end. The caret only returns to the end of the previous mistyped word when the extra letters are deleted.

Hopefully this explanation is clear, please let me know if you have questions.

**Comment by Miodec** [comment]
That is the drawback of enabling hide extra letters. Im not sure what would be a solution to this.

**Comment by someotherotherguy** [comment]
Well in theory, when the user deletes the space, the visual position of the caret should match visual position from before the user pressed space, because they are logically the same. My guess is that there is a different behavior for updating the visual position when backspace is pressed that leads to this visual disparity. I don't know if the same behavior is used regardless of hide extra letters being enabled/disabled, or if it is different; but that is probably where the issue lies. If I knew the what and where the logic is for handling a backspace when hide extra letters is enabled, I might be able to figure out what is going on.

**Comment by someotherotherguy** [comment]
Okay, I went ahead and cloned the repo in order to debug this. I found where the issue occurs (in the updateCaretPosition() function which starts on line 1413 of [src/js/script.js](https://github.com/Miodec/monkeytype/blob/01e98fcf7880152138093a039426003079ac1444/src/js/script.js#L1413)):
```javascript
function updateCaretPosition() {
// ...
  let inputLen = currentInput.length;
  let currentLetterIndex = inputLen - 1;
  if (currentLetterIndex == -1) {
    currentLetterIndex = 0;
  }
  try {
    let currentLetter= document
      .querySelector("#words .active")
      .querySelectorAll("letter")[currentLetterIndex];

    if ($(currentLetter).length == 0) return;
```
When hide extra letters is enabled, if currentInput has extra letters, then currentLetterIndex will be out of the bounds of the node list of letter elements returned by the document query. Needless to say, it is out of bounds because the .active element does not have those extra letters when hide extra letters enabled. So currentLetter is undefined, and the final if statement in the snippet is true and the function returns without updating the caret position.

I would suggest comparing inputLen to the length of the node list, and if the input length is greater, set currentLetter to the last letter in the list:
```javascript
// ...
  try {
    let currentWordNodeList = document
      .querySelector("#words .active")
      .querySelectorAll("letter");
    let currentLetter = currentWordNodeList[currentLetterIndex];
    if (inputLen > currentWordNodeList.length) {
      currentLetter = currentWordNodeList[currentWordNodeList.length-1];
    }
     
    if ($(currentLetter).length == 0) return;
```
If this looks like a decent solution, then I will go ahead and create a pull request.

**Comment by Miodec** [comment]
Merged pr.
