### ISSUE TITLE
Show extra letters with word highlight mode

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#600]
A problem I had mentioned with you typing "worldeee" then it showing only "world_world world world" was due to Word Highlight being turned on.

Even if you turn off "hide extra letters" it doesn't show the extra letters you typed.

**Comment by Miodec** [comment]
Thats just the standard behaviour of word highlight mode, follows the way 10ff and other websites do it.

**Comment by TheeKevin** [comment]
Could you perhaps maybe default turn on the hide extra letters when you select word highlight but once you turn the hide extra letters option off you can see the extra letters.

Since I would love to see how many mistakes I made so I can correct them easily and it doesn't make sense to have an option that does something or nothing depending on what your highlight is.

**Comment by Miodec** [comment]
Alright, sound like a fair idea now that you can hide extra letters
