### ISSUE TITLE
i cant figure out how to run it properly please help

### ISSUE THREAD

**Issue by Charlie2006** [Miodec/monkeytype#612]

**Comment by bereketsemagn** [comment]
Hey, Charlie! Could you elaborate on what's wrong with your situation? Are you needing assistance to create an account? Pair it to discord? Or what's up?

**Comment by thehamkercat** [comment]
> Hey, Charlie! Could you elaborate on what's wrong with your situation? Are you needing assistance to create an account? Pair it to discord? Or what's up?

he wants to selfhost it
and there is no documentation

**Comment by Miodec** [comment]
`CONTRIBUTING.md` should have all the info needed.
