### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Gabe-H** [Miodec/monkeytype#613]
![image](https://user-images.githubusercontent.com/50390056/99897611-c8edd380-2c4f-11eb-9a08-971ecbdc6e32.png)
![image](https://user-images.githubusercontent.com/50390056/99897628-e753cf00-2c4f-11eb-8d69-6b90a386e9f1.png)

On loading, screen is blank, says 'verifying', then the error in screenshot 1. Happening for other users too.
Second screenshot is the console of Chrome Windows 10 `87.0.4280.66 (Official Build) (64-bit) (cohort: 87_66_Win)`

**Comment by Gabe-H** [comment]
Blocking and re-allowing cookies for let it work again

**Comment by pingshunhuangalex** [comment]
Yeah, 9 out of 10 the website makes any changes, you need to do a hard refresh to make it work (`ctrl-shift-r`)

**Comment by Gabe-H** [comment]
@pingshunhuangalex Ah, gotcha
