### ISSUE TITLE
! and ? should have a space before them in French

### ISSUE THREAD

**Issue by Rougemoot** [Miodec/monkeytype#622]
Doing a test with random words with punctuation in French, we get !s qnd ?s, and in French typography you should put a space before them, so I guess there should be a space in the test as well.

It's also the case with colons but I can't remember if there already is a space or not.

Edit: colons and semi-colons *do* need to have a space added before them.

**Comment by Miodec** [comment]
Fixed

**Comment by Fred-Vatin** [comment]
> Doing a test with random words with punctuation in French, we get !s qnd ?s, and in French typography you should put a space before them, so I guess there should be a space in the test as well.
> 
> It's also the case with colons but I can't remember if there already is a space or not.
> 
> Edit: colons and semi-colons _do_ need to have a space added before them.

In French typography, double punctuation marks are preceded by a non-breaking space, but the type of space depends on the character:

- An exclamation mark (!), question mark (?), and semicolon (;) require a thin non-breaking space before them.
- A colon (:) requires a regular non-breaking space before it.

Standard non-breaking spaces are also used to keep elements bound together, such as between numbers and their units or nouns (e.g., 10 pages, 5 km), after honorific titles (M., Dr), within dates (15 January), and inside French quotation marks (« and »). Therefore, the test should include these spaces accordingly.
