### ISSUE TITLE
Account Creation Date not functioning

### ISSUE THREAD

**Issue by bereketsemagn** [Miodec/monkeytype#624]
When a user creates an account on https://monkeytype.com, it shows that their account was created 1 days ago, however even if the account was made a few minutes or hours ago, it still shows this. 

A possible fix could be; is the default when a user creates an account set to 1 day? 
Not sure what the issue is, I'll try to look into myself as well.

**Comment by typerqeo** [comment]
That's because `ceil()` is being used here https://github.com/Miodec/monkeytype/blob/master/src/js/account.js#L264

It might make sense to use `floor()` or show finer granularity.

**Comment by bereketsemagn** [comment]
Hey, @typerqeo 

Yeah, I actually noticed that as well in the `account.js` section. It should be changed to floor(), I do agree.
However, thanks for stopping by!
