### ISSUE TITLE
Request: Danish - 1000 most used words - List provided in comment

### ISSUE THREAD

**Issue by nobel15** [Miodec/monkeytype#629]
som jeg hans at han var til på er med de være på en har dette fra ved hot ord men hvad nogle er det du eller havde den af til og en i vi kan ud andre var som gøre deres tid hvis vil hvordan sagde en hver fortælle gør sæt tre ønsker luft godt også spille lille ende sætte hjem læse hånd havn stor stave tilføje selv jord her skal stor høj sådan følg handling hvorfor spørge mænd ændring gik lys slags off brug hus billede prøv os igen dyr punkt mor verden nær bygge selv jord far enhver ny arbejde del tage få sted lavet leve hvor efter tilbage lidt kun runde mand år kom vis hver god mig giver vores under navn meget gennem bare formular sætning stor tænke sige hjælpe lav linje afvige tur årsag meget betyde før træk højre dreng gamle også samme hun alle der når op brug Deres måde om mange derefter dem skrive ville ligesom så disse hende lang gøre ting se ham to har se mere dag kunne gå komme gjorde nummer lyd nej mest mennesker min løbet kende vand end opkald første der kan ned side været nu finde hoved stå egen side bør land fundet svar skole vokse undersøgelse stadig lære plante dæksel mad sol fire mellem stat holde øje aldrig sidste lad tænkte by træ krydse gård hårdt begyndelse måske historie sav langt hav tegne venstre sent køre ikke mens presse tæt nat real liv få nord bog bære tog videnskab spise værelse ven begyndte idé fisk bjerg stoppe en gang basen høre hest cut sikker ser farve ansigt træ main åben synes sammen næste hvid børn begynde fik gang eksempel lethed papir gruppe altid musik dem både mark ofte brev indtil mile flod bil fødder pleje sekund nok plain pige sædvanlig unge klar ovenfor nogensinde rød liste selv føler snak fugl snart krop hund familie direkte udgøre forlade sang måle dør produkt sort kort talord klasse vind spørgsmål ske komplet skib område halvdelen sten ordre brand syd problem stykke fortalt vidste pass siden top hele konge gade tommer formere intet kursus ophold hjul fuld kraft blå objekt beslutte overflade dyb månen ø fod systemet travlt test rekord båd fælles guld mulig planet stedet tør spekulerer grine tusinde siden løb tjek spil form sidestille varmt miss bragt varme sne dæk bringe ja fjernt fylde øst maling sprog blandt enhed magt by bøde vis flyve falde føre råb mørk maskine notat vente plan figur stjerne kasse navneord felt hvile korrekt stand pund gjort skønhed køretur stod indeholder forside undervise uge endelig gav grøn oh hurtig udvikle havet varm fri minut stærk særlige sind bag klar hale producere kendsgerning rum hørt bedst time bedre sand i løbet af hundrede fem huske trin tidligt holde vest jorden interesse nå hurtigt verbum synge lytte seks tabel rejser mindre formiddag ti simpelt flere vokal mod krig lægge mod mønster langsom centrum elsker person, penge tjene synes vej kort regn regel regere træk kold varsel stemme energi jagt sandsynlig seng bror æg tur celle tro måske pick pludselige tælle firkantet årsag længde repræsentere kunst emne regionen størrelse variere bosætte tale vægt generelt is stof cirkel pair omfatter kløft stavelse filt store kugle endnu bølge drop hjerte am til stede tung dans motor stilling armen bred sejl materiale fraktion skov sidde løb vindue butik sommer tog søvn bevise enlig ben motion væg fangst monteringstid ønske himmel bord glæde vinter Lør skriftlig vild redskab holdt glas græs ko job kant tegn besøg fortid blød sjov lyse gas vejr måned millioner bære slut glad håber blomst iklæde mærkelig væk handel melodi tur kontor modtage række mund eksakt symbolet dø mindst besvær råbe undtagen skrev frø tone slutte tyder ren pause dame værftet stige dårlig slag olie blod røre voksede procent mix hold ledning omkostninger tabt brun slid haven lige sendt vælge faldt passe flow retfærdig bank indsamle spare kontrol decimal øre andet helt brød tilfælde midten dræbe søn sø øjeblik skala højt fjeder observere barn lige ud konsonant nation ordbog mælk hastighed metode orgel betale alder sektion kjole sky overraskelse stille sten lille klatre køligt konstruktion dårlig parti eksperiment bund nøgle jern enkelt stick flad tyve hud smil krølle hul hoppe barn otte landsby Mød rod købe hæve løse metal hvorvidt skub syv afsnit tredje skal Held hår beskrive kok gulv enten resultat brænde bakke sikker kat århundrede overveje typen lov bit kyst kopi sætning lydløs høj sandet jord rulle temperatur finger industri værdi kamp løgn slå ophidse naturlig udsigt fornuft kapital vil ikke stol fare frugt rig tyk soldat proces operere praksis særskilt svært læge venligst beskytte middag afgrøde moderne elementet hit studerende hjørne parti forsyning hvis lokalisere ring karakter insekt fanget periode angive radio talte atomet menneske historie effekt elektrisk forventer knogle skinne forestille give enige således blid kvinde kaptajn gætte nødvendig skarp vinge skabe nabo vask flagermus snarere mængden majs sammenligne digt streng klokke afhænge kød gnide rør berømt dollaren strøm frygt syn tynd trekant verden skynde chef koloni ur minen slips indtaste større frisk Søg sende gul pistol tillade udskriv død plet ørken kulør strøm elevator steget ankommer mester spor forælder kysten opdeling ark stof begunstige forbinde indlæg tilbringe akkord fedt glad originale aktie stationen far brød oplade korrekt bar tilbud segmentet slave ænder øjeblikkelig marked grad befolke chick kære fjende svar drikke forekomme støtte tale natur rækkevidde damp bevægelse sti væske log betød kvotient tænder skallen hals ilt sukker død temmelig færdighed kvinder årstid opløsning magneten sølv tak gren kamp endelse især figen bange enorm søster stål diskutere fremad lignende guide erfaring Baseret æble købte ledede tonehøjde frakke masse kort bånd reb slip sejr drømme aften betingelse foder værktøj samlede grundlæggende lugt dal heller ikke dobbelt sæde fortsætte blok diagram hat sælge succes selskab fratrække begivenhed særlig aftale svømme sigt modsat kone sko skulder spredning arrangere lejr opfinde bomuld Født bestemme kvart ni lastbil støj niveau mulighed samle butik strækning smide skinne ejendom kolonne molekyle Vælg forkert grå gentagelse kræver bred forberede salt næse flertal vrede fordring kontinent

**Comment by nullaf** [comment]
#634
