### ISSUE TITLE
Notifications too quick

### ISSUE THREAD

**Issue by RealCyGuy** [Miodec/monkeytype#638]
The notifications drop down for half a second then go back up.

**Comment by RealCyGuy** [comment]
https://github.com/Miodec/monkeytype/blob/b875d7933f4663209d5d05343951796869f37f39/src/js/misc.js#L191

**Comment by typerqeo** [comment]
https://github.com/Miodec/monkeytype/pull/641 should fix it

**Comment by Miodec** [comment]
Merged pr that fixed it
