### ISSUE TITLE
Be able to customize the keymap on the keymap itself 

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#651]
By customizing I mean the static, react, or next features of the keymap. It's annoying to go to the settings constantly to change the keymap. So an idea would be that you could do what you already did and maybe put the keymap thing in the spacebar or you could put it with the other features that are on top of the words your typing.

**Comment by pingshunhuangalex** [comment]
I think that beats the purpose of minimalism by surfacing everything to the homepage cuz different features can be important to different people. Personally having 3 status on top of the paragraph is already too much for my taste. That's the reason why we have the command line coming to the rescue.

**Comment by Miodec** [comment]
I agree with @pingshunhuangalex, i think using the command line for this is fine.

**Comment by TheeKevin** [comment]
Yeah thanks that's a good idea. I'll try using the command line.
