### ISSUE TITLE
58008 accountant mode with numpad?

### ISSUE THREAD

**Issue by Gabe-H** [Miodec/monkeytype#657]
Doesn't recognize any input from numpad, which is kind of a bummer for the 58008 funbox mode. In the console, I can log a keydown event when the focus is anywhere else on the screen, but once the typing field is focused, numpad keys return an error.

**Comment by Miodec** [comment]
Whats the error?

**Comment by Gabe-H** [comment]
![image](https://user-images.githubusercontent.com/50390056/100909656-dbeb7980-3481-11eb-8970-28523fbde670.png)

**Comment by Miodec** [comment]
im pushing a fix right now

**Comment by Miodec** [comment]
Clear cache and try again, it should be working

**Comment by Gabe-H** [comment]
Works, thanks!
