### ISSUE TITLE
SpeechSynthesis: Reads the next word outloud

### ISSUE THREAD

**Issue by omonkulov** [Miodec/monkeytype#665]
Would you be able to add SpeechSynthesis to read the words for the user so the user doesn't have to look at the monitor
and can just type it out? It would help improve not only typing but improve spelling. Why not kill two birds with one stone. 

Also, I looked for a website that has SpeechSynthesis but wasn't able to find any... so if implemented this would be the first typing website with speech. 

Thank you.

**Comment by TheeKevin** [comment]
This is somewhat implemented already using the "tts" funbox if that helps you.

**Comment by Miodec** [comment]
Yeah im not sure what the benefit of speaking the words is. At higher speeds it will only be a distraction. And as @TheeKevin said you can use the tts funbox to get a something simmilar to what you're looking for.
