### ISSUE TITLE
filter by quote length

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#670]

**Comment by RealCyGuy** [comment]
like with the tool icon?

**Comment by TheeKevin** [comment]
@RealCyGuy I believe he means filtering with the graph as quote length isn't a filter on the graph page yet. Also, monkeytypegeorge is a bot so you won't get a response from him .

**Comment by Miodec** [comment]
Thats correct @TheeKevin

**Comment by TheeKevin** [comment]
Should this be closed since the feature has been added?
