### ISSUE TITLE
Profile page, show "error-rate" instead of accuracy

### ISSUE THREAD

**Issue by Carreau** [Miodec/monkeytype#673]
First, let me thanks you for working on this and making it open source. 

I realized that accuracy is often close to 100%, near the top of the graph, this can make it relatively hard to see small variation. At the same time it is often overlapping with the typing speed which can hover in the same range; and make the scale on the side confusing. 

Have you considered on the profile page to show typing speed and error-rate (100%-accuracy) instead; this would make the two graphs more distinguishable ?

Thanks.

**Comment by Miodec** [comment]
This is an interesting suggestion, ill have a look into it

**Comment by Miodec** [comment]
Added

**Comment by Carreau** [comment]
Awesome ! is it deployed ? I don't find a toggle or option.

**Comment by Miodec** [comment]
Its enabled by default on the account page @Carreau

**Comment by Carreau** [comment]
Ahhhh ! Nice, there was probably some caching on my end. Time to get that to zero now :-)
