### ISSUE TITLE
Min WPM requires you to finish the first word in under 1 second 

### ISSUE THREAD

**Issue by DaneEvans** [Miodec/monkeytype#675]
if you set any value for min wpm, then it is assessed on a per second basis, and seemingly only considers whole words. 
This isn't an issue if there is a short word to start, but if you get unlucky it is rather difficult, and can require a WPM much greater than the limit that you have set.

**Comment by Miodec** [comment]
Im not sure whats a good solution to this - ignore min wpm until the first word is completed?

**Comment by Miodec** [comment]
Min wpm will now ignore first 3 words
