### ISSUE TITLE
Original Graph

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#677]
I do like the idea of using error-rate rather than using the amount of correct keys so the accuracy and speed wouldn't overlap or be so close to each other but I still kind of liked the original graph so could you make it toggleable from the original graph to using error-rate.

**Comment by pingshunhuangalex** [comment]
The chart looks quite confusing IMO. Everthing is still accuracy including hover over tooltip, except for the axis title which is the only clue that's telling people the value displayed is something else...

**Comment by TheeKevin** [comment]
Yeah I agree. I think you should be able to toggle it from accuracy to error rate where the accuracy graph is just the original graph but the error rate displays the actual error rate instead of accuracy.
