### ISSUE TITLE
Have pace caret not follow accuracy

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#678]
The pace caret is helpful for accuracy but if your not focusing on accuracy and only raw speed the pace caret is just going to speed across your typing and you wouldn't get a good idea of how well your doing on raw speed. So what I'm asking is if you can have a feature where the pace caret doesn't follow accuracy and is just a line that goes at a certain wpm.

**Comment by Miodec** [comment]
The pace caret will not follow accuracy if you enable `blind mode`.
