### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#679]
On the Monkeytype community discord server there's challenges and even somewhat of a leaderboard (just the fastest wpm a person can do with the challenge but still) so maybe you could migrate those challenges to Monkeytype instead of those challenges just laying on the discord server. I know it would be a big task to try to implement all those challenges into Monkeytype so you could just do a page of all the challenges and that would probably satisfy everyone because it's easy enough to recreate those challenges with the Monkeytype.

**Comment by Miodec** [comment]
Im not sure if adding them to the website is needed, since you need to be in the discord server anyway to receive a reward for completing the challenges. All though having some sort of way to quickly start challenges (with a custom link or something) would be nice.

**Comment by TheeKevin** [comment]
I see you've added custom links to quick start challenges. Is that only going to be for the discord server or are you actually going to implement those links inside of Monkeytype itself?

**Comment by Miodec** [comment]
Just the discord server for now.
