### ISSUE TITLE
Word progress doesn't work with nospace

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#692]
First, the word progress doesn't update since nospace makes it so there's only one word so that's kind of a bug.

Second, I think you should use character progress instead of words when your using nospace

**Comment by Miodec** [comment]
![image](https://user-images.githubusercontent.com/13181393/101674807-df1dd100-3a50-11eb-82e2-4f7d96b584a6.png)

Extra info from Discord.

**Comment by Miodec** [comment]
Fixed

**Comment by TheeKevin** [comment]
alrighty thanks
