### ISSUE TITLE
Unable to hide accuracy from showing, the setting does not update.

### ISSUE THREAD

**Issue by erikgroving** [Miodec/monkeytype#696]
**Describe the bug**
Per title

**To Reproduce**
Open monkey type, go to settings, attempt to set accuracy to hide.

**Expected behavior**
Expect the ability to set accuracy to hide

**Screenshots**
![image](https://user-images.githubusercontent.com/7717331/101809479-995f1800-3ae5-11eb-9c58-a75c79d90e18.png)

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Miodec** [comment]
Clear cache and try again. Should be working fine
