### ISSUE TITLE
Random code language respecting syntax

### ISSUE THREAD

**Issue by gabrielbeauchemin** [Miodec/monkeytype#702]
I just discovered your website and it is really amazing, good job!

Problematic: The code language (JavaScript, python, c++, ...) generation is so different than real life code that it does not really practice speed typing them.

Solution 1: Generate random code that respect the syntax of the language.

Solution 2: If solution 1 is too much time-consuming, add the punctuations of the language in the generation. (ex. for JavaScript, add the following symbols: [, ], {, }, =, +, -, ;, ', ", `, <, >, ...). When we code, some of these punctuations are very often, so ignoring them does not help the typer to improve.

Thank you!

**Comment by Miodec** [comment]
Generating random code is a big project on its own. I could just do a kind of dirty approach where enabling punctuation mode with  a code language will add all the 'coding' symbols

**Comment by Miodec** [comment]
Added

**Comment by gabrielbeauchemin** [comment]
I agree that generating random language for all languages is a big project...! Thanks!
