### ISSUE TITLE
Cannot choose c++ language

### ISSUE THREAD

**Issue by klementtan** [Miodec/monkeytype#705]
**Describe the bug**
Error when choosing `c++` as language

Error message: `c++` failed regex check

**To Reproduce**
1. Go to settings 
2. Navigate to language
3. Click on `c++`

**Expected behavior**
`c++` slected

**Screenshots**
![image](https://user-images.githubusercontent.com/49265907/101977871-bb929a80-3c8b-11eb-95ba-d8f358555287.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by Miodec** [comment]
Should be fixed after you clear cache.
