### ISSUE TITLE
Custom theme lost and revert to preset theme every time the website gets an update

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#707]
**Describe the bug**
Custom theme lost and revert to preset theme every time the website gets an update

**Expected behavior**
Custom theme not lost every time the website gets an update

**Comment by Miodec** [comment]
Thats weird, because custom themes are just stored in your cookie / account config, and your data is not directly affected by updates.

**Comment by pingshunhuangalex** [comment]
The color setting is not lost, it's just always reverted to the most recent preset one. Similar issues occur before when interacting with other things too. Some config/toggle controlling custom theme has some issues

**Comment by pingshunhuangalex** [comment]
This issue seems to be gone with the 1.6.7 updates. Thanks.
