### ISSUE TITLE
Always logged out on Safari

### ISSUE THREAD

**Issue by joe-scotto** [Miodec/monkeytype#708]
**Describe the bug**
When logging in with "Remember Me" on Safari, I will always get logged out after closing my browser.

**To Reproduce**
1. Login with "Remember Me" selected on Safari
2. Close browser.
3. You're now logged out.

**Expected behavior**
"Remember Me" should keep me logged in.

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser: Safari 14.0.1

**Comment by Miodec** [comment]
Isn't happening to me on the same version of safari and macos. Do you have any extensions that could be causing this? Check the browser console for any errors aswell.

**Comment by joe-scotto** [comment]
It was AdGuard deleting 3rd party cookies after 180 minutes. I whitelisted Monkeytype and now it is working as expected.
