### ISSUE TITLE
"swedish" and "swedish_1k" undefined

### ISSUE THREAD

**Issue by xenforq** [Miodec/monkeytype#712]
**Describe the bug**
If you select either "swedish" or "swedish_1k" and return to the landing page, you kindly get prompted with the error saying; "Error getting language: undefined"

**To Reproduce**
1. Go to the settings
2. Select either "swedish" or "swedish_1k"
3. Return to the landing page

**Expected behavior**
After selecting one of the two language options you should be getting right into being able to use said language to practice, however, that is not what happens.

**Desktop:**
 - OS: Windows 10
 - Browser: Brave
 - Version: v1.18.70 (chromium: 87.0.4280.101)

**Additional context**
As Swedish was recently added to Monkeytype as seen on [PR-#711](https://github.com/Miodec/monkeytype/pull/711)—I could expect this to be a back-end issue with it not being up-to-date yet on the web server. I guess we'll have to see.

**Comment by minerscale** [comment]
I'm not exactly sure what's going on here. I can reproduce it fine but I can't figured out what I did wrong... I guess we wait?

**Comment by minerscale** [comment]
Okay, found the bug. Left a trailing comma at the end of the word list, causing the JSON to be unparsable. Fixing now.
