### ISSUE TITLE
PB cursor won't get activated on the first test

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#719]
Since 1.6.6, PB cursor won't get activated on the very first test after I visit the site. It'll only show up after I start my second one.

**Comment by Miodec** [comment]
There is no way around it - if you start a test before your account data finishes downloading (which has your pb's stored). The pace caret will not work.

**Comment by pingshunhuangalex** [comment]
That doesn't feel right...
- we can pull key settings first, maybe in a dedicated batch
- we can show a loading state that makes sure the test won't get started before all the key settings are obtained
- we can keep PB setting in local storage or cache as a fallback and update it every time the setting is synced

The experience is also weird cuz I wait for a long time till the spinning wheel is gone at the account section, but PB still wouldn't kick in. It feels like you are not applying the PB setting after it's fetched.

Anyway, I think this is a very common thing to do for most of the website that has settings, not sure why there's no way around it

**Comment by Miodec** [comment]
Nevermind, something is wrong. I've waited for the account to finish loading and it didnt work.

**Comment by Miodec** [comment]
As for your other points:

 - Pulling key settings wont make a change because the config is applied very very quickly. The delay mainly comes from firebase autologin taking its sweet time.
 - By showing a loading state before the account is finished loading i essentially lock the user out of the website for a good 5 seconds - not good for UX.
 - Keeping PB setting in storage maybe could work, but will be out of date if you got a new pb on another device.

**Comment by pingshunhuangalex** [comment]
- Pull the login bit out of the main page, maybe even have a dedicated login page to have a UI separation if it's out of your control
- The UX is not good in the first place. I'm not saying we should lock the user out, but the issue that needs to be addressed here is either make things not load for 5s OR find a way to let PB kick in even when the user has already started typing
- If it's not in another device, it's just not. The client should just wait until the syncing kicks in. Not sure why this should be the reason to stop making improvement on this front cuz it'll still help cases when the user is not using a new device

**Comment by Miodec** [comment]
Bug fixed.
