### ISSUE TITLE
Character "^" combined with a letter doesn't work

### ISSUE THREAD

**Issue by louispelarrey** [Miodec/monkeytype#724]
When I put the character "ê" on my keyboard, it says I'm wrong, I'v got no idea why because on other websites everything just works perfectly.

![image](https://user-images.githubusercontent.com/70629775/102417310-b8850a80-3ffb-11eb-84af-c5f6c473f40c.png)

 - Windows
 - Chrome
 - Version Latest
 - Ducky Channel One 2 Mini Azerty

**Comment by louispelarrey** [comment]
![image](https://user-images.githubusercontent.com/70629775/102417875-e454c000-3ffc-11eb-83b5-3fa3bac1b9b9.png)

In azerty version, the key at the right of **P** letter is **^** and **¨** in uppercase
So you have to first press **^** and after the vowel you want to put the **^** on

**Comment by Miodec** [comment]
Make sure layout override is set to default.
