### ISSUE TITLE
Final WPM differs from WPM of last second

### ISSUE THREAD

**Issue by iokiou** [Miodec/monkeytype#730]
Issue persists in both regular and incognito browsing mode.

**Description**
Final WPM may differ significantly and unjustifiably from the WPM of the last second. It actually differs quite often for even more than 1 word, but in the following case the difference is significant and obvious.

**How I figured out - Possible steps to reproduce**
I have set a WPM auto-failure threshold at 105 WPM, while keeping accuracy auto-failure off.

![inconsistent-wpm-autofail-1b](https://user-images.githubusercontent.com/26504755/102490492-31717a00-406f-11eb-9aad-ff6b54ec6a29.png) _Picture 1: Configuration_

I started a test typing fast but my performance started deteriorating. As my WPM fell below 105, the test failed as expected. You may see in the attached screenshot that at second 3 my WPM was 112 and had a downward trend. At the last second (4), my WPM was 102 which is under the configured threshold.
However, the final WPM for the test was 114 WPM, which does not seem right and does not justify why the test failed.

![inconsistent-wpm-autofail-1a](https://user-images.githubusercontent.com/26504755/102490513-3a624b80-406f-11eb-9f9c-1e3cb9bef208.png) _Picture 2: Results_

One may claim that I was able to build up my WPM after second 4, at a fraction of the fifth second (eg. at second 4.4) and the test took some time to fail. This claim can be easily rejected by removing auto-failure and taking a fixed-time test, as described in the steps below.

**Steps to reproduce**
Another way to reproduce the error is the following:
1. Start a timed typing test of 15 seconds.
2. Type at a high speed (eg. 110-120WPM) and high accuracy (90+%).
3. When you have 7 seconds left, start typing really slow (~25WPM).

If you are (un)lucky enough, you will notice a difference of 2+ WPM between the final WPM and the WPM of the last second. The difference is there all the time, but because of rounding it may not be so obvious if it's 1 WPM or less.

![inconsistent-wpm-2](https://user-images.githubusercontent.com/26504755/102490665-6978bd00-406f-11eb-822e-54472ad48d03.png) _Picture 3: Results after executing the aforementioned steps_

**Expected behavior**
Final WPM should match the WPM of the last second in a timed test.

**System**
 - OS: 
	- Edition: Windows 10 Home 
	- Version: 20H2
	- Build: 19042.685
	- Type: 64-bit
 - Browser:
	- Brand: Google Chrome
	- Version: 87.0.4280.88
	- Build: Official
	- Type: 64-bit
 - Monkeytype Version: v1.6.6

**Comment by Miodec** [comment]
Should be adjusted in the next update (will be pushed out today)
