### ISSUE TITLE
Incorrect theme toggle behaviour with custom theme

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#736]
With the recent 1.6.7 update, doing a `shift-click` will toggle the custom theme which is nice. However, when I'm already on custom theme, clicking on the theme toggle and click away (without changing the theme) will result in the theme set to a preset one.

IMO, the ideal solution is to:
- make the custom theme one option in the toggle menu (so no subtle `shift-click` is needed
- do not touch the preset/custom theme mode if users just click on the button without making any changes

**Comment by Miodec** [comment]
Following your ideal solution is kinda difficult with rewriting custom themes since they are a bit different to normal themes, but I made it so just clicking the button will not automatically disable the custom theme
