### ISSUE TITLE
Monkeytype lacks UTF-8 support for language inputs

### ISSUE THREAD

**Issue by xenforq** [Miodec/monkeytype#737]
**Describe the bug**
UTF-8 is not properly working, at least for the languages "swedish" and "swedish_1k". Letters such as "åäö" should work properly but Monkeytype decides to detect these characters as they would be on a US-layout keyboard.

**To Reproduce**
1. Go to the settings
2. Select either "swedish" or "swedish_1k"
3. Type using the words option
4. Try to type a word containing "å", "ä" or "ö"
5. See the results

**Expected behavior**
The letters from frequent Scandinavian alphabets should work just the same as any letter in the English alphabet, obviously.

**Screenshots**
![img](https://user-images.githubusercontent.com/56734956/102590319-aa74de00-4110-11eb-81fa-8c968cc79d05.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: v1.18.70 (chromium: 87.0.4280.101)

**Additional context**
n/a

**Comment by Miodec** [comment]
Try to disable layout override and try again. This should work.

**Comment by xenforq** [comment]
Oop, that fixed it. My apologies.
