### ISSUE TITLE
Pressing space in the middle of a word does not show or act as an error when 'stop on word' set

### ISSUE THREAD

**Issue by AJ-Williams1** [Miodec/monkeytype#738]
When the 'stop on error' mode is set to 'word', and you press space in the middle of a word, it is not typed or counted as an error.

**Steps to reproduce the behavior:**
1. Use the command-line or settings panel to set 'stop on error' to 'word'
2. While in a test, press space in the middle of a word
3. Note that the space is not typed
4. After the test, note that the error is not counted

**Expected behavior**
I think the character that should have been typed should turn red (as it does when you type a wrong letter), and you should not be able to move on to the next word until you correct the error. In other words, it should behave just like any other mistyped character.

**Desktop:**
 - OS: Arch Linux
 - Browser: Brave
 - Version 1.13.86

This behavior may be on purpose, but if so, it would be nice to have a setting to toggle it.

**Comment by Miodec** [comment]
Added.

**Comment by SeerLite** [comment]
@Miodec Hi!
A tip: You can put something like `closes #<issue>` in the message of a commit that resolves a specific issue, and GitHub will close it automatically and make a link from the issue.
This makes it easy for people who are searching the issue tracker and want to see what commit solved specific issues. Basically it helps keeping the issue tracker organized.

Of course, you don't have to do this if you don't want to! I'm just saying in case you didn't know about it.

**Comment by Miodec** [comment]
Haha yeah, i know about it - just keep forgetting to do it.
