### ISSUE TITLE
Two monkeytype websites?

### ISSUE THREAD

**Issue by Xtian90** [Miodec/monkeytype#744]
Saw two monkeytype websites, one is www.monkeytype.com, and another one is monkeytype.com, i visited two of that and on the other website it says i still havent logged in on that, so what's going on with this two websites?

**Comment by xenforq** [comment]
It seems as if the Monkeytype web server is configured to recognize `www.monkeytype.net` and `monkeytype.net` as two separate sites. 

This can be fixed with a simple CNAME record via Cloudflare on their end.

**Comment by Xtian90** [comment]
> It seems as if the Monkeytype web server is configured to recognize `www.monkeytype.com` and `monkeytype.com` as two separate sites.
> 
> This can be fixed with a simple CNAME record via Cloudflare on their end.

**Comment by Xtian90** [comment]
> It seems as if the Monkeytype web server is configured to recognize `www.monkeytype.com` and `monkeytype.com` as two separate sites.
> 
> This can be fixed with a simple CNAME record via Cloudflare on their end.

**Comment by Xtian90** [comment]
Im very sorry if i closed your comment im still new... i was supposed to reply

**Comment by Miodec** [comment]
Yeah as @xenforq said, it was a problem with the dns. I added a CNAME record, it should be good
