### ISSUE TITLE
Continuation of #744

### ISSUE THREAD

**Issue by xenforq** [Miodec/monkeytype#752]
**Did you make sure to clear cache before opening an issue?**
Yes. I even tried on a separate device.

**Describe the bug**
"monkeytype.com" and "www.monkeytype.com" are recognized as two separate websites on the webserver.

**To Reproduce**
1. Open two new tabs using each of the domains
2. Save some custom settings on one
3. Refresh the other site
4. See the results

**Expected behavior**
"www.monkeytype.com" should just be an alias for "monkeytype.com". Both of the two should lead to the same site no matter what, really.

**Screenshots**
Me visiting "monkeytype.com":

![monkeytype.com](https://user-images.githubusercontent.com/56734956/102871015-28e9bc80-443e-11eb-9974-d3e2f8eb4b1b.png)

Me visiting "www.monkeytype.com":

![www.monkeytype.com](https://user-images.githubusercontent.com/56734956/102871061-3acb5f80-443e-11eb-9acc-fbaaf39bf761.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: v1.18.70 (chromium: 87.0.4280.101)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 14.2
 - Browser: Safari
 - Version: 14.0.1

**Additional context**
I see that Monkeytype is running behind Cloudflare, so solving this should technically be pretty easy. The screenshot below shows the DNS setup that will make "www.monkeytype.com" and "monkeytype.com" the same website.

![cloudflare-config](https://user-images.githubusercontent.com/56734956/102898356-b0005a00-4469-11eb-96ef-71d6181eb7f9.png)

**Comment by Miodec** [comment]
Its weird, because ive already done that before closing the other issue.

![image](https://user-images.githubusercontent.com/13181393/102916026-c2cf5a80-447a-11eb-9198-bfc9d68d97bc.png)

**Comment by xenforq** [comment]
> Its weird, because ive already done that before closing the other issue.
> 
> ![image](https://user-images.githubusercontent.com/13181393/102916026-c2cf5a80-447a-11eb-9198-bfc9d68d97bc.png)

It must be a matter of time then for DNS to update everywhere. I guess someone will reopen this issue if it persists.
