### ISSUE TITLE
Login not persistent after reloading monkeytype web page

### ISSUE THREAD

**Issue by 766F6964** [Miodec/monkeytype#757]
**Describe the bug**
The login does not seem to be persistant in ungoogled-chromium when reloading the page after 2 or 3 finished typing tests.
I am certain this is not a browser related problem, because the session cookie is still set after reloading, and on other websites, I am still logged in when relaoding the page with F5. This problem only occurs on monkeytype.com.

**To Reproduce**
1. Open ungoogled-chromium.
2. Go to https://monkeytype.com/login and sign in.
3. Do a typing test. I did the time 30sec one.
4. When done, press F5 to reload the page - essentially to start another typing test.
5. Notice you are not logged in anymore. (If you are still logged in, repeat step 2 and 3 a few times)

**Expected behavior**
I expect to still be signed in, after reloading the page with F5.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: ungoogled-chromium Version 
 - Version: 87.0.4280.88 (Official Build) Arch Linux (64-bit)

**Comment by Miodec** [comment]
As per #708, maybe its an extension doing something you're not expecting?

As for restarting the test, its much quicker to press `tab + enter` or just `tab` with quick tab mode enabled, to avoid the page loading time.

**Comment by ajkachnic** [comment]
This is just speculation, as I'm not too familiar with ungoogled-chromium, but it could be do that ungoogled-chromium is blocking google cookies, and MonkeyType uses Firebase authentication, leading to this issue. This could be entirely wrong, but felt it might be worth mentioning

**Comment by 766F6964** [comment]
> This is just speculation, as I'm not too familiar with ungoogled-chromium, but it's possible that ungoogled-chromium is blocking google related cookies, and MonkeyType uses Firebase authentication, leading to this issue. This could be entirely wrong, but felt it might be worth mentioning

This might very well be the case. Some analytics and site-related requests got blocked:

```
GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT
monkeytype.com/:30 GET https://monkeytype.com/cdn-cgi/bm/cv/669835187/api.js net::ERR_BLOCKED_BY_CLIENT
monkeytype.js:40 loading cookie config
monkeytype.js:41 applying cookie config
monkeytype.js:41 saving cookie config
firebase-analytics.js:1 GET https://www.googletagmanager.com/gtag/js?l=dataLayer net::ERR_BLOCKED_BY_CLIENT
vt @ firebase-analytics.js:1
```

**Comment by Miodec** [comment]
These are just the ad and analytics, so shouldnt affect login

**Comment by Miodec** [comment]
Still an issue?
