### ISSUE TITLE
No Ads are shown on Safari 14.0.2

### ISSUE THREAD

**Issue by Ranoiaetep** [Miodec/monkeytype#768]
**Describe the bug**
No Ads are shown on Safari 14.0.2 on when `Enable ads` are set to either `On` or `Sellout`

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Browser: Safari
 - Version: 14.0.2 (16610.3.7.1.9)

**Additional context**
Turning on/off `Prevent cross-site tracking` in Safari doesn't seem to have effects on it.

**Comment by TheeKevin** [comment]
Unless the ad's have been fixed at some point isn't this the problem?

![Screenshot 2021-01-05 at 9 52 33 AM](https://user-images.githubusercontent.com/58377021/103674482-0aa2b700-4f3c-11eb-82b0-c5860d3f0fef.png)

It's been unavailable since November 6th of 2020

**Comment by Miodec** [comment]
As mentioned in another issue, ads got limited couple of days ago because of 'invalid traffic concerns'. Not sure what to do about it :/
