### ISSUE TITLE
Word joiner not correctly handled in "Remove Fancy Typography"

### ISSUE THREAD

**Issue by arthurl** [Miodec/monkeytype#783]
Expected: [word joiner](https://en.wikipedia.org/wiki/Word_joiner)  should be stripped from custom text when "Remove Fancy Typography" is enabled.

Current behaviour: not stripped.

Why I care: I like to use the custom text feature to type out paragraphs of prose from ebooks. Properly formatted ebooks will have a sprinkling of word-joiners, most commonly just before an em-dash (e.g. "[I went below⁠—not without a full presentiment of evil.](https://standardebooks.org/ebooks/edgar-allan-poe/short-fiction/text/ms-found-in-a-bottle)").

**Comment by Miodec** [comment]
Fixed in dd8855654dcba71fa993d9b9f2dc145b9af532ac. Should be live soon.
