### ISSUE TITLE
When switching from settings to account panel filters get reset.

### ISSUE THREAD

**Issue by Provola23** [Miodec/monkeytype#788]
**Describe the bug**
When switching from settings to account panel filters get reset.

**To Reproduce**
1. Go to `Settings`.
2. Click on `Account`.
3. Enjoy!

**Expected behavior**
Not resetting filters.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Version: 89 Dev

This also happens when not changing anything in the settings panel.

**Comment by Miodec** [comment]
Very simmilar to #786 so ill close this one.
