### ISSUE TITLE
Built in word filter to practise weak letters

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#789]

**Comment by TheeKevin** [comment]
I don't want to mistake this as something else entirely but isn't this an extension of #44?

**Comment by kevinzhao07** [comment]
Hey Miodec, 
I would love to try to implement something like this locally and show you. What were you planning? Are you thinking of seeing which words were most frequently mistyped and filter more words that would contains those letters?

**Comment by Miodec** [comment]
Old issue, already added!
