### ISSUE TITLE
Sometimes the 1 word English test is valid and gets registered on the profile even if I did 300wpm.

### ISSUE THREAD

**Issue by Provola23** [Miodec/monkeytype#792]
**Describe the bug**
Sometimes the 1 word English test is valid and gets registered on my profile even if I did 300wpm.

**To Reproduce**
1. Start a one word typing test
2. Do it fast
3. Enjoy

**Expected behavior**
A 1 word test should be invalid.

**Screenshots**
![Gets registered even if it's one word ](https://i.imgur.com/hdQfZ8C.png "Screenshot")

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Mozilla Firefox
 - Version: 84

**Comment by Miodec** [comment]
Thats fine. All tests below 350 wpm are considered valid, no matter the mode.
