### ISSUE TITLE
Missing Text from Behaviour Menu (Blind Mode)

### ISSUE THREAD

**Issue by cwangsanata** [Miodec/monkeytype#793]
**Describe the bug**
The Blind Mode settings toggle is missing text when turning it on, unlike the other menu settings.

**To Reproduce**
1. Go to the settings tab.
2. Scroll down to blind mode
3. See that the button is missing the word 'on'.

**Expected behaviour**
The word 'on' should be on the button

**Screenshots**
![BugReport](https://user-images.githubusercontent.com/75346952/103488722-06538e00-4dc4-11eb-9c8d-8b166b6806e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version  87.0.4280.88 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Not a bug. Its a little joke - the button is blind.

**Comment by cwangsanata** [comment]
Definition of not a bug, but a feature.

Imma bit slow huh.
