### ISSUE TITLE
Pressing space in the middle of any word skips the entire word.

### ISSUE THREAD

**Issue by zebbyjz** [Miodec/monkeytype#794]
If you type a single letter of the word and mistakenly enter space, it skips over the whole word. Not sure if it was intended to be that way but it gets very frustrating when you accidentally press space and miss the entire word. Is there an option to turn it off that  I am missing?

**Comment by Miodec** [comment]
Yes, its intended. You can enable `stop on error: word` to get the behaviour you are probably looking for.
