### ISSUE TITLE
Portuguese language isn't working

### ISSUE THREAD

**Issue by OldMope** [Miodec/monkeytype#795]
**Describe the bug**

When you select hte portuguese language and try play it the site shows the following error "Error getting language: undefined" and switch to english automatically 

**To Reproduce**
Just  select the portuguese language and try play it

**Possible Cause**

Perhaps the portuguese.json code is wrong in the third line ("_comment": "Sourced from: "https://www.wordandphrase.info/port",)

There's and extra quotation mark that may have caused the bug

**Comment by Miodec** [comment]
Fixed.
