### ISSUE TITLE
Ads not visible

### ISSUE THREAD

**Issue by joshuathooyavan** [Miodec/monkeytype#796]
**Describe the bug**

**To Reproduce**
1. Go to settings page or command-line, turn on Ads to either On or Sellout
2. Refresh the page
3. The UI resizes, but does not display any ads.

**Expected behavior**
Ads should be visible.

**Screenshots**
Ads disabled:
![image](https://user-images.githubusercontent.com/52509691/103507567-1fd8f200-4e25-11eb-89c4-f0dbb8b8dca2.png)

Ads set to On (notice the extra space at the bottom where there would be an ad):
![image](https://user-images.githubusercontent.com/52509691/103507646-45fe9200-4e25-11eb-9a8b-d2e48c1a3208.png)

Ads set to Sellout:
![image](https://user-images.githubusercontent.com/52509691/103507603-2ff0d180-4e25-11eb-88eb-ad2671b5d8ec.png)

**Desktop**
 - OS: Windows Version 2004
 - Browser: Chrome
 - Version: 87

**Additional context**
- Changing the setting from the Settings page doesn't make any difference.
- I am refreshing the page after changing the setting, still doesn't show ads.
- Ads are not visible on any of the pages (Settings, Profile, etc still don't show ads, but all pages seem to be resized accordingly)
- #768 is probably from the same problem

**Comment by Miodec** [comment]
They got enabled early december and then limited again couple days ago. Not really sure what to do about these 'invalid traffic concerns' thye keep giving me as the reason :<

**Comment by TheeKevin** [comment]
So the 'invalid traffic concerns' are the click farms and bots right?

Have you ever thought of trying to combat the invalid traffic concerns using some software?

**Comment by Miodec** [comment]
Yeah, im sure what could be done.

**Comment by TheeKevin** [comment]
I don't know if this could help but maybe it might?

https://www.monetizemore.com/blog/how-fix-ad-serving-limits-adsense/#:~:text=Invalid%20traffic%20concerns&text=Different%20types%20of%20invalid%20traffic,and%20clicks%20from%20click%20farms.
