### ISSUE TITLE
Cannot save any test with language 'code c++'

### ISSUE THREAD

**Issue by Alenygam** [Miodec/monkeytype#797]
**Describe the bug**
Cannot save any test with language `code c++`

**To Reproduce**
1. Start a test with language `code c++`
2. Complete the test
3. Enjoy error

**Expected behavior**
The test should be saved normally.

**Screenshots**
![Screenshot of the issue](https://i.imgur.com/p3SF7cR.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 84

**Comment by Miodec** [comment]
Fixed in 254a0414a524471401b374ce602e003479ddf179
