### ISSUE TITLE
With Minimum font Size Set, live percentage causes reflows

### ISSUE THREAD

**Issue by Aghassi** [Miodec/monkeytype#799]
**Did you make sure to clear cache before opening an issue?**
Yes

**Describe the bug**
On Firefox, setting the minimum font size of 30 on a 27" 1440p monitor causes the live percentage to reflow the text in the typing box. This is disruptive when trying to do the test.

**To Reproduce**
1. Set minimum font size in your browser to 30
2. Enable live wpm and accuracy
3. Take a test

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Miodec** [comment]
All sorts of things seem to break at this sort of font size. Try to increase the page width in the settings, should help with reflowing.
