### ISSUE TITLE
Settings reset after Practice missed words

### ISSUE THREAD

**Issue by eduardboghian** [Miodec/monkeytype#815]
**Describe the bug**
I use the timer on 30s including Numbers and Punctuation. After Practicing the mistyped words, the Numbers and Punctuation are not selected anymore

**To Reproduce**
1. Go to 'Practice with time with Number and Punctuation'
2. Mistype 
3. Practice mistyped
4. Back to practice and see the preferences are not selected anymore

**Expected behavior**
To go back to practice with my selections still selected

**Desktop (please complete the following information):**

**Comment by SeerLite** [comment]
Looks like you submitted the same issue twice?

**Comment by eduardboghian** [comment]
Yes. I was redirected to 404 after submitting 814. That's why I made 815. I
just closed 814

**Comment by eduardboghian** [comment]
The problem is not resolved yet!

**Comment by Miodec** [comment]
Its not deployed yet
