### ISSUE TITLE
Quotes PB not being for each quote 

### ISSUE THREAD

**Issue by Jonny-exe** [Miodec/monkeytype#816]
I think quotes PB should be for quote length instead of quote id. This would help with PB pace caret in quotes.
Instead of having a PB for each exact quote you would have one for all same length quotes. 

Let me know if this sounds good.
If this sounds good I would happily do it.

**Comment by TheeKevin** [comment]
I understand your idea but the problem with that is some quotes have really easy vocabulary to type or really few words as they can vary a lot even if they're considered the same size so then if you get a really good score on something with few words your PB is going to be larger than the speed that you can regularly type. It can also just inflate your scores on quotes.

**Comment by Miodec** [comment]
I think its fine the way it is, I agree with @TheeKevin
