### ISSUE TITLE
Typing apostrophes (') does not register

### ISSUE THREAD

**Issue by OgunHva** [Miodec/monkeytype#822]
**Describe the bug**
I can't type the apostrophes when typing quotes. I have tried it in the default layout and QWERTY but still get the same result. I tried it on both Chrome and Opera. The keyboard layout I use is US international.

**Expected behavior**
Typing words like that's, can't, won't do not register the apostrophe key.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Opera

**Comment by galius-on-github** [comment]
That's how US International works! To achieve an apostrophe, type `'` followed by `␣` (a space).

**Comment by OgunHva** [comment]
@galius-on-github, I know, but it will not register for me on Monkeytype. When I type the `'` key with space then nothing happens.  It does work on other websites.

**Comment by OgunHva** [comment]
@galius-on-github Sorry my description was wrong, that does work, but what I mean is when I want to type `don't` by doing `'` followed by typing the letter `t` then it should do the apostrophe, right? Monkeytype does not register this for me. On other websites, this does work.

**Comment by Miodec** [comment]
This is a problem with the core of the website and will require a rewrite - has been an issue for a while now. There are other open issues relating to the same thing, so ill close this one. Just know that it might take some time to update this. Sorry.
