### ISSUE TITLE
View percentile

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#825]
Show how the result compares to other users.

**Comment by boogalewie** [comment]
Hey, I had a good idea for this, maybe show on one frequency distribution graph two curves for the general population and the monkeytype userbase.
Thanks,
-Lewie.

**Comment by kevinzhao07** [comment]
I can try something like this. How would I get a mock database to work with?

**Comment by Miodec** [comment]
@kevinzhao07 if you follow the `contributing.md` file you should be able to set up a local database.
