### ISSUE TITLE
enter key bug

### ISSUE THREAD

**Issue by aviegdown** [Miodec/monkeytype#828]
**Describe the bug**
while holding tab then pressing enter, this make enter work as underlline instead of restart test (tab > enter). I know that we suppose to (press tab and then enter) not (press enter while holding tab), but this clearly unexpected behavior.

**To Reproduce**
1. Go to 'typing session on any mode'
2. Type 2-3 characters
3. Hold tab and press enter

**Expected behavior**
should work as restart test (tab > enter)

**Screenshots**
![weird](https://user-images.githubusercontent.com/72583750/104418698-e97c3f00-55a9-11eb-8a2d-add49caea1f8.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser firefox
 - Version stable 84.0.2
 
**Additional context**

**Comment by karimk123** [comment]
Yes I have the same bug, using Brave 85 and windows 10

**Comment by szabog** [comment]
The same issue here.

**Software specifications:**

- **OS:** Windows 10 x64 v1909 (Build 18363)
- **Web browser:** Mozilla Firefox 84.0.2 (64-bit)
- **MonkeyType version:** 1.6.11

**MonkeyType configuration:**

```
{"theme":"nord","customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":1,"language":"english","fontSize":"2","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"capsLockBackspace":false,"layout":"default","savedLayout":"default","confidenceMode":"off","indicateTypos":false,"timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"letter","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLayout":"qwerty","fontFamily":"Source_Code_Pro","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false}
```

**Digital proof of the issue (video):**
https://user-images.githubusercontent.com/51328402/104447350-f1cd7d80-559b-11eb-9bf5-4b2e4f3ba013.mp4

**Comment by krsntn** [comment]
I facing the same issue. I noticed that it only works (tab & enter to restart) when the cursor is on starting of any word. It stop working when the cursor is on middle or end of any word.

**Comment by Miodec** [comment]
This is fixed now. Clear cache to get the newest code.
