### ISSUE TITLE
Quick tab not working

### ISSUE THREAD

**Issue by cursorweb** [Miodec/monkeytype#841]
**Did you make sure to clear cache before opening an issue?**
No, tested in inPrivate as well.

**Describe the bug**
With quick tab enabled, you still cannot use tab to enter the next test, it focuses on the next test button instead.

**To Reproduce**
1. Go to settings
2. Turn on quick tab
3. Type
4. Press Tab
5. See error

**Expected behavior**
Originally, pressing tab on the results would go on to the next test, however this feature now doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/29520825/104609329-8f7e8680-5648-11eb-815c-3991bc186321.png)
When pressing tab, this now happens.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft edge (chromium)
 - Version 87.0.664.75 (Official build) (64-bit)

**Additional context**

**Comment by Miodec** [comment]
Should be fixed now.
