### ISSUE TITLE
Timer not visible with new stealth theme

### ISSUE THREAD

**Issue by Ahmad-A0** [Miodec/monkeytype#847]
Stealth theme hides timer.

**Serika Dark**
![image](https://user-images.githubusercontent.com/71089234/104746397-2467a980-5747-11eb-8c90-cd9326797ab6.png)

**Stealth**
![image](https://user-images.githubusercontent.com/71089234/104746495-452fff00-5747-11eb-9c45-6fadbbfdff4e.png)

The timer is grayscale like the  theme background, so it cannot be seen.

**Comment by Miodec** [comment]
Merged
