### ISSUE TITLE
Hitting the delete key inputs the word "Delete"

### ISSUE THREAD

**Issue by pat-rapidai** [Miodec/monkeytype#852]
**Problem**
Hitting the `delete` key types out the word `Delete`

**To Reproduce**
1. Start any typing test
2. Press the `delete` key
3. Observe that the word `Delete` is inputted

**Expected behavior**
Probably nothing unless there's an option to move your cursor as well. Then I would expect the action to remove the character following the cursor.

**Screenshots**
![d](https://user-images.githubusercontent.com/59983125/104820948-3734b980-57ed-11eb-95ec-697bf4ab56a8.gif)

**Desktop**
 - OS: macOS Catalina 10.15.7
 - Browser: chrome
 - Version: 87.0.4280.141

**Comment by Miodec** [comment]
Fixed
