### ISSUE TITLE
Page transition not Correct

### ISSUE THREAD

**Issue by avi123nash** [Miodec/monkeytype#863]
**Did you make sure to clear cache before opening an issue?**
Yes

**Describe the bug**
When at typing test page, clicking login icon the user is redirected to login page. When clicked on `Privacy Policy` and then clicked on browsers back button, the typing test screen appears for a short duration and then the login page page.

**To Reproduce**
1. Load the monkeyType screen where we see the typing test layout
2. Click on login icon at the top
3. Now Click on Privacy Policy just below the version
4. Now Click browsers back button and see the issue

**Expected behavior**
On clicking the browsers back button the login screen should appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AfonsoVReis** [comment]
This is also happening when you refresh the page  when you are on a route other than "/", i suspect that this is  happening because you are defaulting your `pageTest` to active  in `<div class="page pageTest active">`.
