### ISSUE TITLE
Returning Chrome Users message tooltip cuts from the top

### ISSUE THREAD

**Issue by avi123nash** [Miodec/monkeytype#864]
**Did you make sure to clear cache before opening an issue?**
Yes

**Describe the bug**
When merchandise message is closed, the page moves to the top. The Message seen when hovered over `Returning Chrome Users` cuts from the top

**To Reproduce**
1. Clear browser cookies first, then reload monkeyType page.
2. goto login page and click on cancel on merchandise message shown at the top of the screen.
3. Move the cursor over to the Returning Chrome Users link
4. See UI issue

**Expected behavior**
The message should be seen Correctly

**Screenshots**
<img width="959" alt="bubble_notif_issue" src="https://user-images.githubusercontent.com/14849738/105171478-49438e80-5b44-11eb-8414-ea940b4b5e2f.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Miodec** [comment]
Removed message
