### ISSUE TITLE
Not able to type Polish regional characters

### ISSUE THREAD

**Issue by Esemesek** [Miodec/monkeytype#873]
**To Reproduce**
1. Add a Polish keyboard map to your system
2. Change language to Polish
3. Change test type to `Time`
4. Try typing Polish regional characters with `Right Alt/Option + l,o,z,x,c,s,n,e`

**Expected behavior**
One of the regional characters should be typed (łóżźćśńę)

**Screenshots**
![image](https://user-images.githubusercontent.com/9092510/105475603-d2230d00-5c9f-11eb-857d-743277d19de8.png)

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141

**Additional context**
It seems like `Right Alt` key is not working correctly. Whenever I click `Alt + z` I expect `ż` symbol to be typed, but instead of it, I get `z` character.

**Comment by Esemesek** [comment]
Following up on this issue:
I have investigated it a little bit more and it seems like everything works when I run `monkeytype` in development mode: `npm run start:dev`. I made some additional checks and:
- Cleaning site cache didn't' help.
- Running chrome in incognito mode didn't help.
- Running the app on Microsoft Edge also did not help.

**Comment by Esemesek** [comment]
After some more investigation, it seems like there was something wrong with my system config and chrome config thus closing the issue.

**Comment by renkam** [comment]
I am experiencing exactly the same on Debian Linux with Chrome.

**Comment by xPrzybyLx** [comment]
I am experiencing this still on `v1.12` on `Vivaldi 4.3.2439.39 ` browser.

@Esemesek How did You solve this issue?

**Comment by Miodec** [comment]
Guys make sure you disable the layout emulator in the settings.
