### ISSUE TITLE
Words not showing and no buttons working except leaderboard

### ISSUE THREAD

**Issue by karimk123** [Miodec/monkeytype#886]
**Describe the bug**
I randomly went to the website and found nothing visible except for the top bar and the only thing working is the leader board button. When i tried to go from another browser or in incognito mode the issue isnt there.

**To Reproduce**
1. Go to 'monkeytype.com'

**Screenshots**

![image](https://user-images.githubusercontent.com/64856262/105756963-fdcf1d00-5f55-11eb-82b5-980a0feeaea1.png)

 - OS: [Windows 10]
 - Browser [Brave browser]
 - Version [e.g. 87]
 - theme: rgb

**Additional context**
this looks like its caused by something in the user preferences because when i tried it in the same browser but in incognito mode it was normal.

**Comment by aaronireland** [comment]
I am experiencing the same thing on Mac OS X

- OS: macOS Catalina Version 10.15.7
- Browser: Google Chrome Version 88.0.4324.96 (Official Build) (x86_64)
- Theme: Solarized Dark (I tried about a dozen actually)

I did note in the es console:

`DevTools failed to load SourceMap: Could not parse content for https://monkeytype.com/js/moment.min.js.map: Unexpected token < in JSON at position 0`

Along with many logged instances of `clearing keyboard active` from `monkeytype.js:274` (not sure if that's normal/expected though)

**Comment by DaBear57** [comment]
I was experiencing this as well on Brave and Ubuntu until I turned off Brave's shields for the site. Still no clue why it happened, though.

**Comment by jnsntm** [comment]
Same issue.

- OS: macOS BigSur 11.1
- Browser: Safari 14.0.2
- Theme: Honey

**Comment by Miodec** [comment]
Clear cache. Its todays update not showing you the words element.
