### ISSUE TITLE
End screen character count

### ISSUE THREAD

**Issue by ksu-tech** [Miodec/monkeytype#902]
**Did you make sure to clear cache before opening an issue?**
Sometimes your browser has old files cached and the bug you are experiencing might be already fixed, or a side effect of a new update. If you've already tried that, please delete this section. If you don't know how to do that, this website should help: https://clear-my-cache.com/

**Describe the bug**
When typing a letter wrong and then hitting backspace and typing it correctly, I find that when i finish it says I have no incorrect/mistyped words.

**To Reproduce**
1. Start a typing test
2. Mistype a letter
3. Backspace and type correctly
4. End screen shows no incorrect chars

**Expected behavior**
i would still like to see my incorrect characters even if i corrected them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [chrome]
 - Browser [chrome]
 - Version [latest stable build]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Miodec** [comment]
Thats by design, character count only counts the characters after the test was finished.

**Comment by ksu-tech** [comment]
ok
