### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by turkeyphant** [Miodec/monkeytype#906]
**Describe the bug**
Can't type at all. 

**To Reproduce**
1. Go to site
2. Tap to focus on text box 
3. Nothing happen when you type 

**Expected behavior**
Characters entered by keyboard are not recognised 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 
 - Browser Chrome 
 - SwiftKey 

**Smartphone (please complete the following information):**
 - Device: galaxy s10e
 - OS: android 10
 - Browser chrome
 - Version 88

**Comment by ThatOneCalculator** [comment]
This is a typing test designed for keyboards, and reads keyboard input not by bringing up an input field. I doubt it will ever work on mobile devices, and for good reason.

**Comment by turkeyphant** [comment]
Wasn't aware it was designed only for keyboards (where should I have read this?) It works fine on iOS.

**Comment by TheeKevin** [comment]
@ThatOneCalculator Monkeytype does actually work on mobile devices. Such as iOS as @turkeyphant said. Since Miodec wants to allow everyone to use the site. So I think at some point Android could be usable on Monkeytype.

**Comment by turkeyphant** [comment]
Yeah, I can't agree with the premise that excluding Android users is intentional.

**Comment by Miodec** [comment]
Yeah Android not the primary target platform but its also not by design that its not working at the moment. There are plenty of issues about this already and it will get fixed eventually, but its not high on the priority list.
