### ISSUE TITLE
Nospace not working

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#914]
**Did you make sure to clear cache before opening an issue?**

Yes 

**Describe the bug**

The bug is that once you have nospace on it doesn't really work. It forces you to type in a space after every word.

**To Reproduce**
Turn on the funbox on any languge.

**Expected behavior**
Nospace doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/58377021/106651295-31f79e80-6551-11eb-92a3-973ee02f357c.png)

**Desktop (please complete the following information):**
 - OS: [Chrome OS]
 - Browser [Google Chrome]

**Comment by SeerLite** [comment]
Haha, it's caused by #905 / #909. The nospace funbox simulates spaces by triggering the events, and they're getting ignored.

**Comment by TheeKevin** [comment]
Ah I see. Well since this issue is already known then I'll close this issue.
