### ISSUE TITLE
Exporting typing results as a csv

### ISSUE THREAD

**Issue by one-loop** [Miodec/monkeytype#919]
Please use GitHub Discussions:
https://github.com/Miodec/monkeytype/discussions
It would be nice if you could implement a feature to export your results as a csv, so that people can work with their data and do some more advanced data analysis with it. I think keybr has this feature, and it would be good if you can add it to monkey type also

**Comment by kevinzhao07** [comment]
Hey one-loop,
What were you thinking for exporting csv? Would stats specifically would it contain?

**Comment by Miodec** [comment]
This is potentially going to be included as a Patreon perk so I would not worry about it until I get Patreon integration working.

**Comment by khanghugo** [comment]
this is my briefest attempt at exporting, not the best but it works
https://github.com/khanghugo/monkeytype_client_side_graph_export
