### ISSUE TITLE
Enter does not work in code quotes

### ISSUE THREAD

**Issue by Crote** [Miodec/monkeytype#926]
**Describe the bug**
When trying to type a code quote, pressing enter results in a "Uncaught TypeError" in the console.

The downwards arrow indicating an error _does_ change color, but the cursor does not move to the next line. Subsequent enters result in red underscores indicating a typo.

Deleting the "enter" changes the color of the arrow back, and re-pressing enter results in exactly the same behaviour.

**To Reproduce**
1. Set language to "code javascript"
2. Set mode to "quote"
3. Try to type the full quote

**Expected behavior**
I should be able to complete the code, but I can't progress past the first line.

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browsers: Chromium 87 and Firefox 83

**Additional context**
Developer console contains `Uncaught TypeError: event.originalEvent is undefined` and links to what seems to be this line:
https://github.com/Miodec/monkeytype/blob/4ee2ae20c2481b147220fb9fa94b29f5b3828abb/src/js/script.js#L4842

**Comment by Miodec** [comment]
Should be all good now
