### ISSUE TITLE
Counter will be stuck at 30 if any key is pressed while page is loading

### ISSUE THREAD

**Issue by MysteriousLog6** [Miodec/monkeytype#932]
**Describe the bug**
When any key is pressed before the page has finished loading the counter will be stuck and even if you start typing it will stay stuck
**To Reproduce**
1.Open the website "monkeytype.com"
2.While page is loading type something randomly
3.Once the page has finished loading try typing 
4.The countdown is stuck 

**Expected behavior**
The counter should start the countdown as soon as any letter is typed.

**Screenshots**
![image](https://user-images.githubusercontent.com/63236194/107111136-7b0e6200-6873-11eb-8887-339e469ece5f.png)
![image](https://user-images.githubusercontent.com/63236194/107111142-92e5e600-6873-11eb-9878-49691967e577.png)

**Desktop (please complete the following information):**
 - OS: Windows (Works on any OS that supports a physical keyboard)
 - Browser: Chrome (Using chromium based Edge)
 - Version: 88

**Comment by Miodec** [comment]
Fixed

**Comment by MysteriousLog6** [comment]
Bug still exists in V1.7.4

**Comment by MysteriousLog6** [comment]
Bug still exists on 1.7.4
