### ISSUE TITLE
Clear funbox classes when taking a screenshot

### ISSUE THREAD

**Issue by uShldGetCeleste** [Miodec/monkeytype#937]
**Screenshot doesn't work with nausea enabled**
When nausea is enabled the screenshot doesn't work properly

**To Reproduce**
1. Enable nausea in funbox
2. Do a typing test
3. Take a screenshot
4. view broken screenshot

**Expected behavior**
Should show a screenshot that shows your stats for that typing test

**Screenshots**
![image](https://user-images.githubusercontent.com/68669265/107178889-61b00780-6992-11eb-9e12-f0ac7a884987.png)
![image](https://user-images.githubusercontent.com/68669265/107178917-712f5080-6992-11eb-8900-a6ecaccb366c.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome Beta
 - Version: Browser - 89.0.4389.40, OS - 1909

**Comment by MysteriousLog6** [comment]
This might be because the website just takes a snap of whatever is on the browser tab.

**Comment by Miodec** [comment]
Funbox styles are now disabled on the result screen.
