### ISSUE TITLE
Accented characters not working with Brazilian keyboard (ABNT2 layout) in Linux

### ISSUE THREAD

**Issue by marcovirtual** [Miodec/monkeytype#938]
**Describe the bug**
I've been using MonkeyType for many weeks without a problem, usually with the portuguese list of words. But recently I noticed that, whenever I type words with accented characters (such as `também`), MonkeyType does not register the accented character at all, marking it as incorrect. This happens only in the MonkeyType website on Linux. If I type on another browser tab, or in my native text editor, the accented characters are registered correctly. Also, under Windows it works fine.

**To Reproduce**
1. Choose portuguese word list
2. Check default keyboard layout
3. Type the accented word when it comes up.
4. See error.

**Expected behavior**
MonkeyType should register accented characters correctly in Arch Linux.

**Screenshots**
![image](https://user-images.githubusercontent.com/13058480/107254401-0a537b00-6a16-11eb-8161-39d26b0b1318.png)

**Desktop:**
 - OS: Arch Linux
 - Browser: Brave
 - Version: 1.18.78 Chromium: 87.0.4280.141 (Official Build) unknown (64-bit)

**Comment by Miodec** [comment]
Yeah linux doesnt like the current implementation of the input system and doesn't accept accented characters for some reason. There are issues about this already and will need a rewrite.
