### ISSUE TITLE
Caps Lock indicator does not detect the actual state of the key but rather the change

### ISSUE THREAD

**Issue by rvbcldud** [Miodec/monkeytype#943]
**Describe the bug**
When you press the Caps Lock button when there is no Caps Lock indicator (regardless of whether it is activated or not), it will activate it... and vice versa. Also, when the website is refreshed it will default to no Caps Lock indicator

**To Reproduce**
1. Go to https://monkeytype.com/
2. Press the Caps Lock Button
3. Refresh the page

**Expected behavior**
When you first load the website there should be no Caps Lock indicator until you press Caps Lock. Once you refresh the page, this indicator will go away regardless of whether Caps Lock is activated or not

**Screenshots**
Before pressing Caps Lock
![image](https://user-images.githubusercontent.com/32994909/107481146-96f35b80-6b32-11eb-8775-90fdc9e4c10b.png)
After Pressing Caps Lock
![image](https://user-images.githubusercontent.com/32994909/107481207-af637600-6b32-11eb-8ab1-57eab2a412b8.png)
After refreshing the page
![image](https://user-images.githubusercontent.com/32994909/107481239-bb4f3800-6b32-11eb-97ae-19d569bd6b9b.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Browser: Chromium
 - Version: 83.0.4103.116

**Additional context**

**Comment by rvbcldud** [comment]
Lines 4940 through 4950 of the file...master/src/js/script.js seems to be the relevant code.
```js
keypressStats.duration.current = performance.now();
  try {
    if (
      !config.capsLockBackspace &&
      event.originalEvent.getModifierState("CapsLock")
    ) {
      showCapsWarning();
    } else {
      hideCapsWarning();
    }
  } catch {}
```

**Comment by rvbcldud** [comment]
It is also important to mention that it correctly displays the state of the Caps Lock button after another key is pressed. This is due to the surrounding function of the aforementioned code:
```js
$(document).keydown(function (event) {
}
```
Perhaps moving or copying lines 4940 - 4950 to a function that updates when you first enter the site would be a fix. I have not contributed to this product or looked at much code other than what I have provided, so I am sure the more experienced contributors will have an apt suggestion. Thanks.

**Comment by Miodec** [comment]
As far as i know getting the state of Caps Lock without a single key event is impossible in js - so this is the only way of doing this.
