### ISSUE TITLE
More diacritics in french words

### ISSUE THREAD

**Issue by bphd** [Miodec/monkeytype#945]
Selected words only have rarely an "é" or an "è", but definitively not all the [Diacritiques utilisés en français](https://fr.wikipedia.org/wiki/Diacritiques_utilis%C3%A9s_en_fran%C3%A7ais) 

The generated word should have more often diacritics and capital letter in order for you to work more parts of the keyboard

For now, only the "custom" mode permit you to insert those type of words. Plus you can't save a personal set of word, so you have to repeat each times

**Comment by Miodec** [comment]
You can use larger word lists like `french_1k`, and enable `punctuation` mode.
