### ISSUE TITLE
Results screen graph bug

### ISSUE THREAD

**Issue by rsquires1988** [Miodec/monkeytype#948]
Got a graphical bug happening on my results screens.  Wondering if it's because I'm on an ultrawide monitor.  Seems to have started after the Feb. 2nd update.  Mousing over any of the numbers to the sides of the graph changes the splotch's shape until the mouse moves over the graph again, and the splotch is shaped differently every time, seemingly dependent on the graph's contours.  After certain tests, mousing over the graph would remove the splotch, and moving the mouse off of it brought it back.

![image](https://user-images.githubusercontent.com/63078967/107665156-09069600-6c42-11eb-9bff-1d2dec29214e.png)

**Comment by Miodec** [comment]
Does it happen in other browsers?

**Comment by rsquires1988** [comment]
Hard to say. The screenshot's from Chrome 88.0.4324.150 64-bit (current build), but after restarting my computer for a Windows update, the problem seems to be fixed.  I tried Edge, and it works fine there, but that was after the update as well.  Maybe a lack of available system or video memory could have caused it?  I hadn't rebooted in a while and had 20+ tabs open, with other programs running as well.  Not sure if Chrome does some kind of graphical throttling in those cases.

**Comment by rsquires1988** [comment]
Occasionally the splotch would have areas with a gradient as well, usually after taking a longer test.

**Comment by MysteriousLog6** [comment]
> Occasionally the splotch would have areas with a gradient as well, usually after taking a longer test.

I  have had this on other Websites If I were to keep a lot of programs open(Visual Studio, Chromium Edge(15tabs))
It is a video memory bug (Happens when the video memory is too little so it will just delete parts of the pixel)
