### ISSUE TITLE
Zen Mode Disappears With Pace Caret

### ISSUE THREAD

**Issue by danii** [Miodec/monkeytype#956]
If you enable the pace caret and switch to zen mode, nothing displays, but is still there in the background. E.g. if you press shift + enter, the result screen still shows up.

To Reproduce
-------------------
1. Go to the main page, with pace caret set to "None"
2. Click on zen, everything is there
3. Either go to settings, change the pace caret to *anything other than None*, and go back
  - If you configured this through the command line, pressing tab & enter to restart the test is necessary
4. Zen mode is gone! Nothing displays

## Other Bits
- Try pressing shift + enter on the now glitched zen mode to see that the result screen still displays
- Configure the pace caret back to *None*, and go back
- If you configured that through the command line, pressing tab & enter is required. More proof everything still is working and there, but just isn't displayed

Expected Behavior
-------------------------
Zen mode to display as normal, probably without a pace caret even if it was set, as a pace caret does not make much sense in zen mode.

Screenshots & Video
---------------------------
This screenshot links to a demo video:
[![Play demo video...](https://love.catboys.space/SX2crzqgJW.png)](https://love.catboys.space/NeABlF8GeN.mp4)

Not sure if this puts me more in a state of zen or less.
![Nothing showing up on the zen mode screen.](https://danii-really.loves.catboys.space/r0Jk52fyz_.png)

Tested Browsers & Operating Systems
---------------------------------------------------
Manjaro Linux 20.2.1 x86_64 (64-bit) (Code Name Nambia) @ Kernel 5.10.13-2 @ Firefox 85.0.1
Arch Linux x86_64 (64-bit) @ Kernel 5.10.15-arch1-1 @ Firefox 85.0.2
Windows 10 Enterprise x86_64 (64-bit) @ 10.0.17763 Build 17763 @ Firefox 84.0.2

**Comment by Miodec** [comment]
Alright, disabled pace caret with zen.
