### ISSUE TITLE
Counter will be stuck if you type while website is loading

### ISSUE THREAD

**Issue by MysteriousLog6** [Miodec/monkeytype#959]
**Describe the bug**
Bug has been said to be fixed but still exists (I did clear cache)
The Counter will be stuck if you type anything while page is loading.
**To Reproduce**
1. Go to 'monkeytype.com'
2.While page is loading press any letter on your keyboard
3.Counter will be stuck

**Expected behavior**
The counter should start countdown
**Screenshots**
![image](https://user-images.githubusercontent.com/63236194/107907738-7edc6b80-6f7a-11eb-8ab7-128d3ab59432.png)

**Desktop:**
 - OS: Windows 10 OS Version 2009 (Build 19042.804)
 - Browser: Chrome(Edge Chromium)
 - Version: 88.0.705.68 (Official build) (64-bit)

**Additional context**
Was said to be fixed but still exists.

**Comment by MysteriousLog6** [comment]
Will check the file loaded first (Index.html and then follow the process and see what causes it)

**Comment by Miodec** [comment]
Fixed. Live soon.

**Comment by MysteriousLog6** [comment]
Yep it is fixed just checked.
