### ISSUE TITLE
Caps lock cannot be held down

### ISSUE THREAD

**Issue by AlexApps99** [Miodec/monkeytype#976]
**Describe the bug**
Holding down backspace will delete multiple characters, while holding down caps lock will only delete one

**To Reproduce**
Type in some letters, hold down caps lock

**Expected behavior**
Same as backspace

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version 88

**Comment by Miodec** [comment]
Im assuming with caps lock backspace enabled. I cant reproduce it, holding caps lock is repeating backspace for me correctly. Maybe its a Linux issue?

**Comment by AlexApps99** [comment]
That is possible, in that case the only way to fix it would be to add a setting to emulate the key "held" behavior that backspace has on all systems, since libinput or X have it disabled on Caps for some reason

**Comment by Miodec** [comment]
I guess maybe you could use other software to rebind it system wide instead of just on the website?

**Comment by AlexApps99** [comment]
I guess, but that beats the whole point of the option

**Comment by Miodec** [comment]
I guess the whole option doesnt make sense because why would you use caps lock backspace only on monkeytype. If you are going to get used to caps backspace why not just rebind it system wide.

**Comment by AlexApps99** [comment]
True
