### ISSUE TITLE
Missing "On" text under Settings, Behaviour

### ISSUE THREAD

**Issue by bassamanator** [Miodec/monkeytype#992]
![image](https://user-images.githubusercontent.com/61985779/108270026-d9bdc080-713c-11eb-8e0f-d9b5fff60f5f.png)

Tested under Firefox 85.0.1
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.15-1-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Comment by Miodec** [comment]
Intentional joke - the button is blind.
