### ISSUE TITLE
Custom Fonts work great on Mac but not on Windows 10

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#995]
**Describe the bug**
So excited about the new custom fonts feature. Tried it on Mac and it worked like a charm. However, when I tried the same font in Windows 10, it didn't load the font properly and just use the browser default fone as a fallback.

The font is a font collection file, i.e. `.ttc`

**Comment by Miodec** [comment]
Can't verify this, im on windows and they work for me.

**Comment by pingshunhuangalex** [comment]
Can you try with this font? https://drive.google.com/file/d/0B3laO4yuXZrnUkpyWXhaSjZyT2s/view?usp=sharing

It should look like this (Pay attention to character width, letter `r` and `0`:
![image](https://user-images.githubusercontent.com/17170199/108440178-b6168980-72a6-11eb-9491-540fdcf0bc69.png)

But instead, it looks like this:
![image](https://user-images.githubusercontent.com/17170199/108440018-849dbe00-72a6-11eb-8283-fde139154e26.png)

**Comment by Miodec** [comment]
So far it looks like a Windows Chrome issue. I tested on firefox and it works.

**Comment by pingshunhuangalex** [comment]
If there's no hack you can do on a site level, feel free to close the ticket. Probably a long shot if it's on the Chrome level. Thanks.

**Comment by Miodec** [comment]
I mean, i tried to set the font manually, just in css and that didnt work either - so to me it feels like a chrome bug.

**Comment by pingshunhuangalex** [comment]
Yeah make sense. A bug report would be nice. Thanks.

**Comment by Toby222** [comment]
Extracting the ttc into separate ttf files and installing those worked for me.

I tried repackaging them to see if it's a "turn it off and back on again" but that only made fontforge crash.

**Comment by pingshunhuangalex** [comment]
What settings did you use to split the fonts collection @Toby222? I thought about the same thing and tried to split the font with Fontforge before I opened the ticket, but all my trials ended up with broken fonts (.ttf)

**Comment by Toby222** [comment]
I don't know much about fontforge so...
I just opened the .ttc file you provided with the desktop application on Windows, which said this
![image](https://user-images.githubusercontent.com/14962962/108696558-00e00d80-7502-11eb-9894-1231bcc626e4.png)
Selected one of the fonts, selected `Generate Fonts...`
![image](https://user-images.githubusercontent.com/14962962/108696671-2705ad80-7502-11eb-9596-84d55153f655.png)
And then generated a TrueType font from that (ignoring the validation errors that show up, and eventaully realizing I could just turn off validation)
![image](https://user-images.githubusercontent.com/14962962/108696793-4e5c7a80-7502-11eb-8422-9bf0028e5ff4.png)

In the end I was left with those files up there, provided here:
https://tobot.tech/files/tsentsiu

**Comment by pingshunhuangalex** [comment]
Right, tried that too and it looks like lots of non-Romanian characters are gone after installing, so didn't go with that.

The font is quite old cuz it's no longer maintained a long time ago, probably doesn't live to the modern standards. Still surprised to see why it looks all different in Win10, Mac and Electron Apps. Just doesn't make sense to me...

**Comment by pingshunhuangalex** [comment]
Closing it since there's not much MonkeyType could do. Already switched to another font and it worked, so I'll call it a day.
